// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package formaldehydeconcentrationmeasurement is the generated definition of the Matter FormaldehydeConcentrationMeasurement cluster
// (0x042B, revision 5, derived from ConcentrationMeasurement), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package formaldehydeconcentrationmeasurement

import "github.com/SukramJ/go-fabric/cluster/spec"

// Cluster identity.
const (
	ClusterID uint32 = 0x042B
	Name             = "FormaldehydeConcentrationMeasurement"
	Revision  uint16 = 5
)

// Attribute ids.
const (
	AttrMeasuredValue              uint32 = 0x0000 // single, MEA, R V, X
	AttrMinMeasuredValue           uint32 = 0x0001 // single, MEA, R V, X F
	AttrMaxMeasuredValue           uint32 = 0x0002 // single, MEA, R V, X F
	AttrPeakMeasuredValue          uint32 = 0x0003 // single, PEA, R V, X
	AttrPeakMeasuredValueWindow    uint32 = 0x0004 // elapsed-s, PEA, R V
	AttrAverageMeasuredValue       uint32 = 0x0005 // single, AVG, R V, X
	AttrAverageMeasuredValueWindow uint32 = 0x0006 // elapsed-s, AVG, R V
	AttrUncertainty                uint32 = 0x0007 // single, [MEA], R V, F
	AttrMeasurementUnit            uint32 = 0x0008 // MeasurementUnitEnum, MEA, R V, F
	AttrMeasurementMedium          uint32 = 0x0009 // MeasurementMediumEnum, M, R V, F
	AttrLevelValue                 uint32 = 0x000A // LevelValueEnum, LEV, R V
)

// Feature is a FormaldehydeConcentrationMeasurement FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// FeatureMap bits.
const (
	FeatureNumericMeasurement Feature = 1 << 0 // MEA, O.a+
	FeatureLevelIndication    Feature = 1 << 1 // LEV, O.a+
	FeatureMediumLevel        Feature = 1 << 2 // MED, [LEV]
	FeatureCriticalLevel      Feature = 1 << 3 // CRI, [LEV]
	FeaturePeakMeasurement    Feature = 1 << 4 // PEA, [MEA]
	FeatureAverageMeasurement Feature = 1 << 5 // AVG, [MEA]
)

// LevelValueEnum is the LevelValueEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type LevelValueEnum uint8

// LevelValueEnum values.
const (
	LevelValueUnknown  LevelValueEnum = 0 // M
	LevelValueLow      LevelValueEnum = 1 // M
	LevelValueMedium   LevelValueEnum = 2 // MED
	LevelValueHigh     LevelValueEnum = 3 // M
	LevelValueCritical LevelValueEnum = 4 // CRI
)

// LevelValueEnumDef describes LevelValueEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var LevelValueEnumDef = &spec.Enum{Name: "LevelValueEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Unknown", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Low", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "Medium", Conformance: spec.Conformance{Text: "MED", Op: spec.ConfName, Name: "MED"}},
	{Value: 3, Name: "High", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 4, Name: "Critical", Conformance: spec.Conformance{Text: "CRI", Op: spec.ConfName, Name: "CRI"}},
}}

// MeasurementMediumEnum is the MeasurementMediumEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type MeasurementMediumEnum uint8

// MeasurementMediumEnum values.
const (
	MeasurementMediumAir   MeasurementMediumEnum = 0 // M
	MeasurementMediumWater MeasurementMediumEnum = 1 // M
	MeasurementMediumSoil  MeasurementMediumEnum = 2 // M
)

// MeasurementMediumEnumDef describes MeasurementMediumEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var MeasurementMediumEnumDef = &spec.Enum{Name: "MeasurementMediumEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Air", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Water", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "Soil", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// MeasurementUnitEnum is the MeasurementUnitEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type MeasurementUnitEnum uint8

// MeasurementUnitEnum values.
const (
	MeasurementUnitPpm  MeasurementUnitEnum = 0 // MEA
	MeasurementUnitPpb  MeasurementUnitEnum = 1 // MEA
	MeasurementUnitPpt  MeasurementUnitEnum = 2 // MEA
	MeasurementUnitMgm3 MeasurementUnitEnum = 3 // MEA
	MeasurementUnitUgm3 MeasurementUnitEnum = 4 // MEA
	MeasurementUnitNgm3 MeasurementUnitEnum = 5 // MEA
	MeasurementUnitPm3  MeasurementUnitEnum = 6 // MEA
	MeasurementUnitBqm3 MeasurementUnitEnum = 7 // MEA
)

// MeasurementUnitEnumDef describes MeasurementUnitEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var MeasurementUnitEnumDef = &spec.Enum{Name: "MeasurementUnitEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Ppm", Conformance: spec.Conformance{Text: "MEA", Op: spec.ConfName, Name: "MEA"}},
	{Value: 1, Name: "Ppb", Conformance: spec.Conformance{Text: "MEA", Op: spec.ConfName, Name: "MEA"}},
	{Value: 2, Name: "Ppt", Conformance: spec.Conformance{Text: "MEA", Op: spec.ConfName, Name: "MEA"}},
	{Value: 3, Name: "Mgm3", Conformance: spec.Conformance{Text: "MEA", Op: spec.ConfName, Name: "MEA"}},
	{Value: 4, Name: "Ugm3", Conformance: spec.Conformance{Text: "MEA", Op: spec.ConfName, Name: "MEA"}},
	{Value: 5, Name: "Ngm3", Conformance: spec.Conformance{Text: "MEA", Op: spec.ConfName, Name: "MEA"}},
	{Value: 6, Name: "Pm3", Conformance: spec.Conformance{Text: "MEA", Op: spec.ConfName, Name: "MEA"}},
	{Value: 7, Name: "Bqm3", Conformance: spec.Conformance{Text: "MEA", Op: spec.ConfName, Name: "MEA"}},
}}

// Definition is the FormaldehydeConcentrationMeasurement cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Base: "ConcentrationMeasurement",
	Features: []spec.Feature{
		{Name: "MEA", Title: "NumericMeasurement", Bit: 0, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "LEV", Title: "LevelIndication", Bit: 1, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "MED", Title: "MediumLevel", Bit: 2, Conformance: spec.Conformance{Text: "[LEV]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "LEV"}}}},
		{Name: "CRI", Title: "CriticalLevel", Bit: 3, Conformance: spec.Conformance{Text: "[LEV]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "LEV"}}}},
		{Name: "PEA", Title: "PeakMeasurement", Bit: 4, Conformance: spec.Conformance{Text: "[MEA]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "MEA"}}}},
		{Name: "AVG", Title: "AverageMeasurement", Bit: 5, Conformance: spec.Conformance{Text: "[MEA]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "MEA"}}}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrMeasuredValue, Name: "MeasuredValue",
			Type:        spec.Type{Name: "single", Kind: spec.KindFloat32},
			Conformance: spec.Conformance{Text: "MEA", Op: spec.ConfName, Name: "MEA"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
			Constraint:  spec.Constraint{Text: "minMeasuredValue to maxMeasuredValue", Min: &spec.Bound{Ref: "minMeasuredValue"}, Max: &spec.Bound{Ref: "maxMeasuredValue"}},
		},
		{
			ID: AttrMinMeasuredValue, Name: "MinMeasuredValue",
			Type:        spec.Type{Name: "single", Kind: spec.KindFloat32},
			Conformance: spec.Conformance{Text: "MEA", Op: spec.ConfName, Name: "MEA"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
		},
		{
			ID: AttrMaxMeasuredValue, Name: "MaxMeasuredValue",
			Type:        spec.Type{Name: "single", Kind: spec.KindFloat32},
			Conformance: spec.Conformance{Text: "MEA", Op: spec.ConfName, Name: "MEA"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Constraint:  spec.Constraint{Text: "min minMeasuredValue", Min: &spec.Bound{Ref: "minMeasuredValue"}},
		},
		{
			ID: AttrPeakMeasuredValue, Name: "PeakMeasuredValue",
			Type:        spec.Type{Name: "single", Kind: spec.KindFloat32},
			Conformance: spec.Conformance{Text: "PEA", Op: spec.ConfName, Name: "PEA"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
			Constraint:  spec.Constraint{Text: "minMeasuredValue to maxMeasuredValue", Min: &spec.Bound{Ref: "minMeasuredValue"}, Max: &spec.Bound{Ref: "maxMeasuredValue"}},
		},
		{
			ID: AttrPeakMeasuredValueWindow, Name: "PeakMeasuredValueWindow",
			Type:        spec.Type{Name: "elapsed-s", Kind: spec.KindUint, Bits: 32},
			Conformance: spec.Conformance{Text: "PEA", Op: spec.ConfName, Name: "PEA"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "max 604800", Max: &spec.Bound{Int: 604800}},
		},
		{
			ID: AttrAverageMeasuredValue, Name: "AverageMeasuredValue",
			Type:        spec.Type{Name: "single", Kind: spec.KindFloat32},
			Conformance: spec.Conformance{Text: "AVG", Op: spec.ConfName, Name: "AVG"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
			Constraint:  spec.Constraint{Text: "minMeasuredValue to maxMeasuredValue", Min: &spec.Bound{Ref: "minMeasuredValue"}, Max: &spec.Bound{Ref: "maxMeasuredValue"}},
		},
		{
			ID: AttrAverageMeasuredValueWindow, Name: "AverageMeasuredValueWindow",
			Type:        spec.Type{Name: "elapsed-s", Kind: spec.KindUint, Bits: 32},
			Conformance: spec.Conformance{Text: "AVG", Op: spec.ConfName, Name: "AVG"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "max 604800", Max: &spec.Bound{Int: 604800}},
		},
		{
			ID: AttrUncertainty, Name: "Uncertainty",
			Type:        spec.Type{Name: "single", Kind: spec.KindFloat32},
			Conformance: spec.Conformance{Text: "[MEA]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "MEA"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
		},
		{
			ID: AttrMeasurementUnit, Name: "MeasurementUnit",
			Type:        spec.Type{Name: "MeasurementUnitEnum", Kind: spec.KindEnum, Bits: 8, Enum: MeasurementUnitEnumDef},
			Conformance: spec.Conformance{Text: "MEA", Op: spec.ConfName, Name: "MEA"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
		},
		{
			ID: AttrMeasurementMedium, Name: "MeasurementMedium",
			Type:        spec.Type{Name: "MeasurementMediumEnum", Kind: spec.KindEnum, Bits: 8, Enum: MeasurementMediumEnumDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
		},
		{
			ID: AttrLevelValue, Name: "LevelValue",
			Type:        spec.Type{Name: "LevelValueEnum", Kind: spec.KindEnum, Bits: 8, Enum: LevelValueEnumDef},
			Conformance: spec.Conformance{Text: "LEV", Op: spec.ConfName, Name: "LEV"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
		},
	},
}

func init() { spec.Register(Definition) }
