// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package softwarediagnostics

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, ThreadMetricsStruct{Id: uint64(1), Name: spectest.Ptr("x"), StackFreeCurrent: spectest.Ptr(uint32(1)), StackFreeMinimum: spectest.Ptr(uint32(1)), StackSize: spectest.Ptr(uint32(1))}, spec.DecodeStruct[ThreadMetricsStruct])
	spectest.RoundTripCommand(t, Definition, CmdResetWatermarks, spec.Request, ResetWatermarksRequest{})
	spectest.RoundTripEvent(t, Definition, EventSoftwareFault, SoftwareFaultEvent{Id: uint64(1), Name: spectest.Ptr("x"), FaultRecording: spectest.Ptr([]byte{1})})
	spectest.RoundTripAttribute(t, Definition, AttrThreadMetrics, spec.List[ThreadMetricsStruct]([]ThreadMetricsStruct{ThreadMetricsStruct{Id: uint64(1), Name: spectest.Ptr("x"), StackFreeCurrent: spectest.Ptr(uint32(1)), StackFreeMinimum: spectest.Ptr(uint32(1)), StackSize: spectest.Ptr(uint32(1))}}))
}
