// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package energyevsemode

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, ModeOptionStruct{Label: "x", Mode: uint8(1), ModeTags: []ModeTagStruct{ModeTagStruct{MfgCode: spectest.Ptr(uint16(1)), Value: ModeTag(0)}}}, spec.DecodeStruct[ModeOptionStruct])
	spectest.RoundTrip(t, ModeTagStruct{MfgCode: spectest.Ptr(uint16(1)), Value: ModeTag(0)}, spec.DecodeStruct[ModeTagStruct])
	spectest.RoundTripCommand(t, Definition, CmdChangeToMode, spec.Request, ChangeToModeRequest{NewMode: uint8(1)})
	spectest.RoundTripCommand(t, Definition, CmdChangeToModeResponse, spec.Response, ChangeToModeResponse{Status: ModeChangeStatus(0), StatusText: "x"})
	spectest.RoundTripAttribute(t, Definition, AttrSupportedModes, spec.List[ModeOptionStruct]([]ModeOptionStruct{ModeOptionStruct{Label: "x", Mode: uint8(1), ModeTags: []ModeTagStruct{ModeTagStruct{MfgCode: spectest.Ptr(uint16(1)), Value: ModeTag(0)}}}, ModeOptionStruct{Label: "x", Mode: uint8(1), ModeTags: []ModeTagStruct{ModeTagStruct{MfgCode: spectest.Ptr(uint16(1)), Value: ModeTag(0)}}}}))
}
