// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package fixedlabel is the generated definition of the Matter FixedLabel cluster
// (0x0040, revision 1, derived from Label), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package fixedlabel

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0040
	Name             = "FixedLabel"
	Revision  uint16 = 1
)

// Attribute ids.
const (
	AttrLabelList uint32 = 0x0000 // list[LabelStruct], M, R V, N
)

// Feature is a FixedLabel FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// LabelStruct is the LabelStruct struct.
type LabelStruct struct {
	Label string // 0: string, M, max 16
	Value string // 1: string, M, max 16
}

// EncodeTLV implements spec.Encodable.
func (v LabelStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutString(enc, tlv.ContextTag(0), v.Label)
	spec.PutString(enc, tlv.ContextTag(1), v.Value)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *LabelStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "LabelStruct",
		spec.Bind(0, "Label", true, &v.Label, spec.DecodeStringIn(0, 16)),
		spec.Bind(1, "Value", true, &v.Value, spec.DecodeStringIn(0, 16)),
	)
}

// LabelStructDef describes LabelStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var LabelStructDef = &spec.Struct{Name: "LabelStruct", Fields: []spec.Field{
	{ID: 0, Name: "Label", Type: spec.Type{Name: "string", Kind: spec.KindString}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 16", Max: &spec.Bound{Int: 16}}},
	{ID: 1, Name: "Value", Type: spec.Type{Name: "string", Kind: spec.KindString}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 16", Max: &spec.Bound{Int: 16}}},
}}

func decodeAttrLabelList(n spec.Node) (any, error) {
	v, err := spec.DecodeList(spec.DecodeStruct[LabelStruct])(n)
	return spec.List[LabelStruct](v), err
}

// Definition is the FixedLabel cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Base: "Label",
	Attributes: []spec.Attribute{
		{
			ID: AttrLabelList, Name: "LabelList",
			Type:        spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "LabelStruct", Kind: spec.KindStruct, Struct: LabelStructDef}}},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{NonVolatile: true},
			Decode:      decodeAttrLabelList,
		},
	},
}

func init() { spec.Register(Definition) }
