// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package servicearea

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, AreaInfoStruct{LocationInfo: spec.ValueOf(Locationdesc{LocationName: "x", FloorNumber: spec.ValueOf(int16(1)), AreaType: spec.ValueOf(uint8(1))}), LandmarkInfo: spec.ValueOf(LandmarkInfoStruct{LandmarkTag: uint8(1), RelativePositionTag: spec.ValueOf(uint8(1))})}, spec.DecodeStruct[AreaInfoStruct])
	spectest.RoundTrip(t, Locationdesc{LocationName: "x", FloorNumber: spec.ValueOf(int16(1)), AreaType: spec.ValueOf(uint8(1))}, spec.DecodeStruct[Locationdesc])
	spectest.RoundTrip(t, LandmarkInfoStruct{LandmarkTag: uint8(1), RelativePositionTag: spec.ValueOf(uint8(1))}, spec.DecodeStruct[LandmarkInfoStruct])
	spectest.RoundTrip(t, AreaStruct{AreaId: uint32(1), MapId: spec.ValueOf(uint32(1)), AreaInfo: AreaInfoStruct{LocationInfo: spec.ValueOf(Locationdesc{LocationName: "x", FloorNumber: spec.ValueOf(int16(1)), AreaType: spec.ValueOf(uint8(1))}), LandmarkInfo: spec.ValueOf(LandmarkInfoStruct{LandmarkTag: uint8(1), RelativePositionTag: spec.ValueOf(uint8(1))})}}, spec.DecodeStruct[AreaStruct])
	spectest.RoundTrip(t, MapStruct{MapId: uint32(1), Name: "x"}, spec.DecodeStruct[MapStruct])
	spectest.RoundTrip(t, ProgressStruct{AreaId: uint32(1), Status: OperationalStatusEnum(0), TotalOperationalTime: spectest.Ptr(spec.ValueOf(uint32(1))), EstimatedTime: spectest.Ptr(spec.ValueOf(uint32(1)))}, spec.DecodeStruct[ProgressStruct])
	spectest.RoundTripCommand(t, Definition, CmdSelectAreas, spec.Request, SelectAreasRequest{NewAreas: []uint32{uint32(1)}})
	spectest.RoundTripCommand(t, Definition, CmdSelectAreasResponse, spec.Response, SelectAreasResponse{Status: SelectAreasStatus(0), StatusText: "x"})
	spectest.RoundTripCommand(t, Definition, CmdSkipArea, spec.Request, SkipAreaRequest{SkippedArea: uint32(1)})
	spectest.RoundTripCommand(t, Definition, CmdSkipAreaResponse, spec.Response, SkipAreaResponse{Status: SkipAreaStatus(0), StatusText: "x"})
	spectest.RoundTripAttribute(t, Definition, AttrSupportedAreas, spec.List[AreaStruct]([]AreaStruct{AreaStruct{AreaId: uint32(1), MapId: spec.ValueOf(uint32(1)), AreaInfo: AreaInfoStruct{LocationInfo: spec.ValueOf(Locationdesc{LocationName: "x", FloorNumber: spec.ValueOf(int16(1)), AreaType: spec.ValueOf(uint8(1))}), LandmarkInfo: spec.ValueOf(LandmarkInfoStruct{LandmarkTag: uint8(1), RelativePositionTag: spec.ValueOf(uint8(1))})}}}))
	spectest.RoundTripAttribute(t, Definition, AttrSupportedMaps, spec.List[MapStruct]([]MapStruct{MapStruct{MapId: uint32(1), Name: "x"}}))
	spectest.RoundTripAttribute(t, Definition, AttrProgress, spec.List[ProgressStruct]([]ProgressStruct{ProgressStruct{AreaId: uint32(1), Status: OperationalStatusEnum(0), TotalOperationalTime: spectest.Ptr(spec.ValueOf(uint32(1))), EstimatedTime: spectest.Ptr(spec.ValueOf(uint32(1)))}}))
}
