// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package electricalenergymeasurement

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, CumulativeEnergyResetStruct{ImportedResetTimestamp: spectest.Ptr(spec.ValueOf(uint32(1))), ExportedResetTimestamp: spectest.Ptr(spec.ValueOf(uint32(1))), ImportedResetSystime: spectest.Ptr(spec.ValueOf(uint64(1))), ExportedResetSystime: spectest.Ptr(spec.ValueOf(uint64(1)))}, spec.DecodeStruct[CumulativeEnergyResetStruct])
	spectest.RoundTrip(t, EnergyMeasurementStruct{Energy: int64(1), StartTimestamp: spectest.Ptr(uint32(1)), EndTimestamp: spectest.Ptr(uint32(1)), StartSystime: spectest.Ptr(uint64(1)), EndSystime: spectest.Ptr(uint64(1)), ApparentEnergy: spectest.Ptr(int64(1)), ReactiveEnergy: spectest.Ptr(int64(1))}, spec.DecodeStruct[EnergyMeasurementStruct])
	spectest.RoundTrip(t, MeasurementAccuracyStruct{MeasurementType: MeasurementTypeEnum(0), Measured: true, MinMeasuredValue: int64(1), MaxMeasuredValue: int64(1), AccuracyRanges: []MeasurementAccuracyRangeStruct{MeasurementAccuracyRangeStruct{RangeMin: int64(1), RangeMax: int64(1), PercentMax: spectest.Ptr(uint16(1)), PercentMin: spectest.Ptr(uint16(1)), PercentTypical: spectest.Ptr(uint16(1)), FixedMax: spectest.Ptr(uint64(1)), FixedMin: spectest.Ptr(uint64(1)), FixedTypical: spectest.Ptr(uint64(1))}}}, spec.DecodeStruct[MeasurementAccuracyStruct])
	spectest.RoundTrip(t, MeasurementAccuracyRangeStruct{RangeMin: int64(1), RangeMax: int64(1), PercentMax: spectest.Ptr(uint16(1)), PercentMin: spectest.Ptr(uint16(1)), PercentTypical: spectest.Ptr(uint16(1)), FixedMax: spectest.Ptr(uint64(1)), FixedMin: spectest.Ptr(uint64(1)), FixedTypical: spectest.Ptr(uint64(1))}, spec.DecodeStruct[MeasurementAccuracyRangeStruct])
	spectest.RoundTripEvent(t, Definition, EventCumulativeEnergyMeasured, CumulativeEnergyMeasuredEvent{EnergyImported: spectest.Ptr(EnergyMeasurementStruct{Energy: int64(1), StartTimestamp: spectest.Ptr(uint32(1)), EndTimestamp: spectest.Ptr(uint32(1)), StartSystime: spectest.Ptr(uint64(1)), EndSystime: spectest.Ptr(uint64(1)), ApparentEnergy: spectest.Ptr(int64(1)), ReactiveEnergy: spectest.Ptr(int64(1))}), EnergyExported: spectest.Ptr(EnergyMeasurementStruct{Energy: int64(1), StartTimestamp: spectest.Ptr(uint32(1)), EndTimestamp: spectest.Ptr(uint32(1)), StartSystime: spectest.Ptr(uint64(1)), EndSystime: spectest.Ptr(uint64(1)), ApparentEnergy: spectest.Ptr(int64(1)), ReactiveEnergy: spectest.Ptr(int64(1))})})
	spectest.RoundTripEvent(t, Definition, EventPeriodicEnergyMeasured, PeriodicEnergyMeasuredEvent{EnergyImported: spectest.Ptr(EnergyMeasurementStruct{Energy: int64(1), StartTimestamp: spectest.Ptr(uint32(1)), EndTimestamp: spectest.Ptr(uint32(1)), StartSystime: spectest.Ptr(uint64(1)), EndSystime: spectest.Ptr(uint64(1)), ApparentEnergy: spectest.Ptr(int64(1)), ReactiveEnergy: spectest.Ptr(int64(1))}), EnergyExported: spectest.Ptr(EnergyMeasurementStruct{Energy: int64(1), StartTimestamp: spectest.Ptr(uint32(1)), EndTimestamp: spectest.Ptr(uint32(1)), StartSystime: spectest.Ptr(uint64(1)), EndSystime: spectest.Ptr(uint64(1)), ApparentEnergy: spectest.Ptr(int64(1)), ReactiveEnergy: spectest.Ptr(int64(1))})})
	spectest.RoundTripAttribute(t, Definition, AttrAccuracy, MeasurementAccuracyStruct{MeasurementType: MeasurementTypeEnum(0), Measured: true, MinMeasuredValue: int64(1), MaxMeasuredValue: int64(1), AccuracyRanges: []MeasurementAccuracyRangeStruct{MeasurementAccuracyRangeStruct{RangeMin: int64(1), RangeMax: int64(1), PercentMax: spectest.Ptr(uint16(1)), PercentMin: spectest.Ptr(uint16(1)), PercentTypical: spectest.Ptr(uint16(1)), FixedMax: spectest.Ptr(uint64(1)), FixedMin: spectest.Ptr(uint64(1)), FixedTypical: spectest.Ptr(uint64(1))}}})
}
