// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package temperaturecontrol is the generated definition of the Matter TemperatureControl cluster
// (0x0056, revision 1), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package temperaturecontrol

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0056
	Name             = "TemperatureControl"
	Revision  uint16 = 1
)

// Attribute ids.
const (
	AttrTemperatureSetpoint        uint32 = 0x0000 // temperature, TN, R V
	AttrMinTemperature             uint32 = 0x0001 // temperature, TN, R V, F
	AttrMaxTemperature             uint32 = 0x0002 // temperature, TN, R V, F
	AttrStep                       uint32 = 0x0003 // temperature, STEP, R V, F
	AttrSelectedTemperatureLevel   uint32 = 0x0004 // uint8, TL, R V
	AttrSupportedTemperatureLevels uint32 = 0x0005 // list[string], TL, R V
)

// Command ids.
const (
	CmdSetTemperature uint32 = 0x00 // request → status, M
)

// Feature is a TemperatureControl FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// FeatureMap bits.
const (
	FeatureTemperatureNumber Feature = 1 << 0 // TN, O.a
	FeatureTemperatureLevel  Feature = 1 << 1 // TL, O.a
	FeatureTemperatureStep   Feature = 1 << 2 // STEP, [TN]
)

// SetTemperatureRequest is the SetTemperature command payload.
type SetTemperatureRequest struct {
	TargetTemperature      *int16 // 0: temperature, TN, desc
	TargetTemperatureLevel *uint8 // 1: uint8, TL, desc
}

// EncodeTLV implements spec.Encodable.
func (v SetTemperatureRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutOptional(enc, tlv.ContextTag(0), v.TargetTemperature, spec.PutInt[int16])
	spec.PutOptional(enc, tlv.ContextTag(1), v.TargetTemperatureLevel, spec.PutUint[uint8])
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *SetTemperatureRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "SetTemperature",
		spec.Bind(0, "TargetTemperature", false, &v.TargetTemperature, spec.DecodeOptional(spec.DecodeInt[int16](16))),
		spec.Bind(1, "TargetTemperatureLevel", false, &v.TargetTemperatureLevel, spec.DecodeOptional(spec.DecodeUint[uint8](8))),
	)
}

func decodeSetTemperatureRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[SetTemperatureRequest](n)
}

// Definition is the TemperatureControl cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Features: []spec.Feature{
		{Name: "TN", Title: "TemperatureNumber", Bit: 0, Conformance: spec.Conformance{Text: "O.a", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: false, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "TL", Title: "TemperatureLevel", Bit: 1, Conformance: spec.Conformance{Text: "O.a", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: false, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "STEP", Title: "TemperatureStep", Bit: 2, Conformance: spec.Conformance{Text: "[TN]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "TN"}}}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrTemperatureSetpoint, Name: "TemperatureSetpoint",
			Type:        spec.Type{Name: "temperature", Kind: spec.KindInt, Bits: 16},
			Conformance: spec.Conformance{Text: "TN", Op: spec.ConfName, Name: "TN"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "minTemperature to maxTemperature", Min: &spec.Bound{Ref: "minTemperature"}, Max: &spec.Bound{Ref: "maxTemperature"}},
		},
		{
			ID: AttrMinTemperature, Name: "MinTemperature",
			Type:        spec.Type{Name: "temperature", Kind: spec.KindInt, Bits: 16},
			Conformance: spec.Conformance{Text: "TN", Op: spec.ConfName, Name: "TN"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "max maxTemperature - 1", Max: &spec.Bound{Expr: "{\"type\":\"-\",\"lhs\":{\"type\":\"reference\",\"name\":\"maxTemperature\"},\"rhs\":1}"}},
		},
		{
			ID: AttrMaxTemperature, Name: "MaxTemperature",
			Type:        spec.Type{Name: "temperature", Kind: spec.KindInt, Bits: 16},
			Conformance: spec.Conformance{Text: "TN", Op: spec.ConfName, Name: "TN"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
		},
		{
			ID: AttrStep, Name: "Step",
			Type:        spec.Type{Name: "temperature", Kind: spec.KindInt, Bits: 16},
			Conformance: spec.Conformance{Text: "STEP", Op: spec.ConfName, Name: "STEP"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "1 to maxTemperature - minTemperature", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Expr: "{\"type\":\"-\",\"lhs\":{\"type\":\"reference\",\"name\":\"maxTemperature\"},\"rhs\":{\"type\":\"reference\",\"name\":\"minTemperature\"}}"}},
		},
		{
			ID: AttrSelectedTemperatureLevel, Name: "SelectedTemperatureLevel",
			Type:        spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "TL", Op: spec.ConfName, Name: "TL"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "max 31", Max: &spec.Bound{Int: 31}},
		},
		{
			ID: AttrSupportedTemperatureLevels, Name: "SupportedTemperatureLevels",
			Type:        spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "string", Kind: spec.KindString}}},
			Conformance: spec.Conformance{Text: "TL", Op: spec.ConfName, Name: "TL"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "max 32[max 16]", Max: &spec.Bound{Int: 32}, Entry: &spec.Constraint{Text: "max 16", Max: &spec.Bound{Int: 16}}},
		},
	},
	Commands: []spec.Command{
		{
			ID: CmdSetTemperature, Name: "SetTemperature", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "TargetTemperature", Type: spec.Type{Name: "temperature", Kind: spec.KindInt, Bits: 16}, Conformance: spec.Conformance{Text: "TN", Op: spec.ConfName, Name: "TN"}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "TargetTemperatureLevel", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "TL", Op: spec.ConfName, Name: "TL"}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
			},
			Decode: decodeSetTemperatureRequest,
		},
	},
}

func init() { spec.Register(Definition) }
