// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package basicinformation is the generated definition of the Matter BasicInformation cluster
// (0x0028, revision 6), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package basicinformation

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0028
	Name             = "BasicInformation"
	Revision  uint16 = 6
)

// Attribute ids.
const (
	AttrDataModelRevision     uint32 = 0x0000 // uint16, M, R V, F
	AttrVendorName            uint32 = 0x0001 // string, M, R V, F
	AttrVendorId              uint32 = 0x0002 // vendor-id, M, R V, F
	AttrProductName           uint32 = 0x0003 // string, M, R V, F
	AttrProductId             uint32 = 0x0004 // uint16, M, R V, F
	AttrNodeLabel             uint32 = 0x0005 // string, M, RW VM, N
	AttrLocation              uint32 = 0x0006 // string, M, RW VA, N
	AttrHardwareVersion       uint32 = 0x0007 // uint16, M, R V, F
	AttrHardwareVersionString uint32 = 0x0008 // string, M, R V, F
	AttrSoftwareVersion       uint32 = 0x0009 // uint32, M, R V, F
	AttrSoftwareVersionString uint32 = 0x000A // string, M, R V, F
	AttrManufacturingDate     uint32 = 0x000B // string, O, R V, F
	AttrPartNumber            uint32 = 0x000C // string, O, R V, F
	AttrProductUrl            uint32 = 0x000D // string, O, R V, F
	AttrProductLabel          uint32 = 0x000E // string, O, R V, F
	AttrSerialNumber          uint32 = 0x000F // string, O, R V, F
	AttrLocalConfigDisabled   uint32 = 0x0010 // bool, O, RW VM, N
	AttrReachable             uint32 = 0x0011 // bool, O, R V
	AttrUniqueId              uint32 = 0x0012 // string, Rev >= v4, O, R V, F
	AttrCapabilityMinima      uint32 = 0x0013 // CapabilityMinimaStruct, M, R V, F
	AttrProductAppearance     uint32 = 0x0014 // ProductAppearanceStruct, [Rev >= v2], R V, F
	AttrSpecificationVersion  uint32 = 0x0015 // uint32, Rev >= v3, R V, F
	AttrMaxPathsPerInvoke     uint32 = 0x0016 // uint16, Rev >= v3, R V, F
	AttrConfigurationVersion  uint32 = 0x0018 // uint32, Rev >= v6, R V, N
)

// Event ids.
const (
	EventStartUp          uint32 = 0x00 // critical, M
	EventShutDown         uint32 = 0x01 // critical, O
	EventLeave            uint32 = 0x02 // info, O
	EventReachableChanged uint32 = 0x03 // info, Reachable
)

// Feature is a BasicInformation FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// CapabilityMinimaStruct is the CapabilityMinimaStruct struct.
type CapabilityMinimaStruct struct {
	CaseSessionsPerFabric            uint16  // 0: uint16, M, 3 to 10000
	SubscriptionsPerFabric           uint16  // 1: uint16, M, 3 to 10000
	SimultaneousInvocationsSupported *uint16 // 2: uint16, Rev >= v6, 1 to 10000
	SimultaneousWritesSupported      *uint16 // 3: uint16, Rev >= v6, 1 to 10000
	ReadPathsSupported               *uint16 // 4: uint16, Rev >= v6, 9 to 10000
	SubscribePathsSupported          *uint16 // 5: uint16, Rev >= v6, 3 to 10000
}

// EncodeTLV implements spec.Encodable.
func (v CapabilityMinimaStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.CaseSessionsPerFabric)
	spec.PutUint[uint16](enc, tlv.ContextTag(1), v.SubscriptionsPerFabric)
	spec.PutOptional(enc, tlv.ContextTag(2), v.SimultaneousInvocationsSupported, spec.PutUint[uint16])
	spec.PutOptional(enc, tlv.ContextTag(3), v.SimultaneousWritesSupported, spec.PutUint[uint16])
	spec.PutOptional(enc, tlv.ContextTag(4), v.ReadPathsSupported, spec.PutUint[uint16])
	spec.PutOptional(enc, tlv.ContextTag(5), v.SubscribePathsSupported, spec.PutUint[uint16])
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *CapabilityMinimaStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "CapabilityMinimaStruct",
		spec.Bind(0, "CaseSessionsPerFabric", true, &v.CaseSessionsPerFabric, spec.DecodeUintIn[uint16](16, 3, 10000)),
		spec.Bind(1, "SubscriptionsPerFabric", true, &v.SubscriptionsPerFabric, spec.DecodeUintIn[uint16](16, 3, 10000)),
		spec.Bind(2, "SimultaneousInvocationsSupported", false, &v.SimultaneousInvocationsSupported, spec.DecodeOptional(spec.DecodeUintIn[uint16](16, 1, 10000))),
		spec.Bind(3, "SimultaneousWritesSupported", false, &v.SimultaneousWritesSupported, spec.DecodeOptional(spec.DecodeUintIn[uint16](16, 1, 10000))),
		spec.Bind(4, "ReadPathsSupported", false, &v.ReadPathsSupported, spec.DecodeOptional(spec.DecodeUintIn[uint16](16, 9, 10000))),
		spec.Bind(5, "SubscribePathsSupported", false, &v.SubscribePathsSupported, spec.DecodeOptional(spec.DecodeUintIn[uint16](16, 3, 10000))),
	)
}

// CapabilityMinimaStructDef describes CapabilityMinimaStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var CapabilityMinimaStructDef = &spec.Struct{Name: "CapabilityMinimaStruct", Fields: []spec.Field{
	{ID: 0, Name: "CaseSessionsPerFabric", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "3 to 10000", Min: &spec.Bound{Int: 3}, Max: &spec.Bound{Int: 10000}}, Default: float64(3)},
	{ID: 1, Name: "SubscriptionsPerFabric", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "3 to 10000", Min: &spec.Bound{Int: 3}, Max: &spec.Bound{Int: 10000}}, Default: float64(3)},
	{ID: 2, Name: "SimultaneousInvocationsSupported", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "Rev >= v6", Op: spec.ConfRevision, Rev: 6}, Constraint: spec.Constraint{Text: "1 to 10000", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 10000}}},
	{ID: 3, Name: "SimultaneousWritesSupported", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "Rev >= v6", Op: spec.ConfRevision, Rev: 6}, Constraint: spec.Constraint{Text: "1 to 10000", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 10000}}},
	{ID: 4, Name: "ReadPathsSupported", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "Rev >= v6", Op: spec.ConfRevision, Rev: 6}, Constraint: spec.Constraint{Text: "9 to 10000", Min: &spec.Bound{Int: 9}, Max: &spec.Bound{Int: 10000}}},
	{ID: 5, Name: "SubscribePathsSupported", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "Rev >= v6", Op: spec.ConfRevision, Rev: 6}, Constraint: spec.Constraint{Text: "3 to 10000", Min: &spec.Bound{Int: 3}, Max: &spec.Bound{Int: 10000}}},
}}

// ColorEnum is the ColorEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type ColorEnum uint8

// ColorEnum values.
const (
	ColorBlack   ColorEnum = 0  // M
	ColorNavy    ColorEnum = 1  // M
	ColorGreen   ColorEnum = 2  // M
	ColorTeal    ColorEnum = 3  // M
	ColorMaroon  ColorEnum = 4  // M
	ColorPurple  ColorEnum = 5  // M
	ColorOlive   ColorEnum = 6  // M
	ColorGray    ColorEnum = 7  // M
	ColorBlue    ColorEnum = 8  // M
	ColorLime    ColorEnum = 9  // M
	ColorAqua    ColorEnum = 10 // M
	ColorRed     ColorEnum = 11 // M
	ColorFuchsia ColorEnum = 12 // M
	ColorYellow  ColorEnum = 13 // M
	ColorWhite   ColorEnum = 14 // M
	ColorNickel  ColorEnum = 15 // M
	ColorChrome  ColorEnum = 16 // M
	ColorBrass   ColorEnum = 17 // M
	ColorCopper  ColorEnum = 18 // M
	ColorSilver  ColorEnum = 19 // M
	ColorGold    ColorEnum = 20 // M
)

// ColorEnumDef describes ColorEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var ColorEnumDef = &spec.Enum{Name: "ColorEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Black", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Navy", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "Green", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 3, Name: "Teal", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 4, Name: "Maroon", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 5, Name: "Purple", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 6, Name: "Olive", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 7, Name: "Gray", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 8, Name: "Blue", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 9, Name: "Lime", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 10, Name: "Aqua", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 11, Name: "Red", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 12, Name: "Fuchsia", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 13, Name: "Yellow", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 14, Name: "White", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 15, Name: "Nickel", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 16, Name: "Chrome", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 17, Name: "Brass", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 18, Name: "Copper", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 19, Name: "Silver", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 20, Name: "Gold", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// ProductAppearanceStruct is the ProductAppearanceStruct struct.
type ProductAppearanceStruct struct {
	Finish       ProductFinishEnum        // 0: ProductFinishEnum, M
	PrimaryColor spec.Nullable[ColorEnum] // 1: ColorEnum, M, X
}

// EncodeTLV implements spec.Encodable.
func (v ProductAppearanceStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[ProductFinishEnum](enc, tlv.ContextTag(0), v.Finish)
	spec.PutNullable(spec.PutUint[ColorEnum])(enc, tlv.ContextTag(1), v.PrimaryColor)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ProductAppearanceStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ProductAppearanceStruct",
		spec.Bind(0, "Finish", true, &v.Finish, spec.DecodeUint[ProductFinishEnum](8)),
		spec.Bind(1, "PrimaryColor", true, &v.PrimaryColor, spec.DecodeNullable(spec.DecodeUint[ColorEnum](8))),
	)
}

// ProductAppearanceStructDef describes ProductAppearanceStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var ProductAppearanceStructDef = &spec.Struct{Name: "ProductAppearanceStruct", Fields: []spec.Field{
	{ID: 0, Name: "Finish", Type: spec.Type{Name: "ProductFinishEnum", Kind: spec.KindEnum, Bits: 8, Enum: ProductFinishEnumDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{ID: 1, Name: "PrimaryColor", Type: spec.Type{Name: "ColorEnum", Kind: spec.KindEnum, Bits: 8, Enum: ColorEnumDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Quality: spec.Quality{Nullable: true}},
}}

// ProductFinishEnum is the ProductFinishEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type ProductFinishEnum uint8

// ProductFinishEnum values.
const (
	ProductFinishOther    ProductFinishEnum = 0 // M
	ProductFinishMatte    ProductFinishEnum = 1 // M
	ProductFinishSatin    ProductFinishEnum = 2 // M
	ProductFinishPolished ProductFinishEnum = 3 // M
	ProductFinishRugged   ProductFinishEnum = 4 // M
	ProductFinishFabric   ProductFinishEnum = 5 // M
)

// ProductFinishEnumDef describes ProductFinishEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var ProductFinishEnumDef = &spec.Enum{Name: "ProductFinishEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Other", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Matte", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "Satin", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 3, Name: "Polished", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 4, Name: "Rugged", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 5, Name: "Fabric", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// StartUpEvent is the StartUp event payload.
type StartUpEvent struct {
	SoftwareVersion uint32 // 0: uint32, M
}

// EncodeTLV implements spec.Encodable.
func (v StartUpEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint32](enc, tlv.ContextTag(0), v.SoftwareVersion)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *StartUpEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "StartUp",
		spec.Bind(0, "SoftwareVersion", true, &v.SoftwareVersion, spec.DecodeUint[uint32](32)),
	)
}

// ShutDownEvent is the ShutDown event payload.
type ShutDownEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v ShutDownEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ShutDownEvent) DecodeTLV(n spec.Node) error { return spec.DecodeFields(n, "ShutDown") }

// LeaveEvent is the Leave event payload.
type LeaveEvent struct {
	FabricIndex uint8 // 0: fabric-idx, M, 1 to 254
}

// EncodeTLV implements spec.Encodable.
func (v LeaveEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint8](enc, tlv.ContextTag(0), v.FabricIndex)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *LeaveEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "Leave",
		spec.Bind(0, "FabricIndex", true, &v.FabricIndex, spec.DecodeUintIn[uint8](8, 1, 254)),
	)
}

// ReachableChangedEvent is the ReachableChanged event payload.
type ReachableChangedEvent struct {
	ReachableNewValue bool // 0: bool, M
}

// EncodeTLV implements spec.Encodable.
func (v ReachableChangedEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutBool(enc, tlv.ContextTag(0), v.ReachableNewValue)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ReachableChangedEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ReachableChanged",
		spec.Bind(0, "ReachableNewValue", true, &v.ReachableNewValue, spec.DecodeBool),
	)
}

func decodeStartUpEvent(n spec.Node) (any, error) { return spec.DecodeStruct[StartUpEvent](n) }

func decodeShutDownEvent(n spec.Node) (any, error) { return spec.DecodeStruct[ShutDownEvent](n) }

func decodeLeaveEvent(n spec.Node) (any, error) { return spec.DecodeStruct[LeaveEvent](n) }

func decodeReachableChangedEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[ReachableChangedEvent](n)
}

func decodeAttrCapabilityMinima(n spec.Node) (any, error) {
	return spec.DecodeStruct[CapabilityMinimaStruct](n)
}

func decodeAttrProductAppearance(n spec.Node) (any, error) {
	return spec.DecodeStruct[ProductAppearanceStruct](n)
}

// Definition is the BasicInformation cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Attributes: []spec.Attribute{
		{
			ID: AttrDataModelRevision, Name: "DataModelRevision",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
		},
		{
			ID: AttrVendorName, Name: "VendorName",
			Type:        spec.Type{Name: "string", Kind: spec.KindString},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "max 32", Max: &spec.Bound{Int: 32}},
		},
		{
			ID: AttrVendorId, Name: "VendorId",
			Type:        spec.Type{Name: "vendor-id", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
		},
		{
			ID: AttrProductName, Name: "ProductName",
			Type:        spec.Type{Name: "string", Kind: spec.KindString},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "max 32", Max: &spec.Bound{Int: 32}},
		},
		{
			ID: AttrProductId, Name: "ProductId",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
		},
		{
			ID: AttrNodeLabel, Name: "NodeLabel",
			Type:        spec.Type{Name: "string", Kind: spec.KindString},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "max 32", Max: &spec.Bound{Int: 32}},
		},
		{
			ID: AttrLocation, Name: "Location",
			Type:        spec.Type{Name: "string", Kind: spec.KindString},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeAdminister},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "2", Value: &spec.Bound{Int: 2}},
			Default:     "XX",
		},
		{
			ID: AttrHardwareVersion, Name: "HardwareVersion",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Default:     float64(0),
		},
		{
			ID: AttrHardwareVersionString, Name: "HardwareVersionString",
			Type:        spec.Type{Name: "string", Kind: spec.KindString},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "1 to 64", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 64}},
		},
		{
			ID: AttrSoftwareVersion, Name: "SoftwareVersion",
			Type:        spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
			Default:     float64(0),
		},
		{
			ID: AttrSoftwareVersionString, Name: "SoftwareVersionString",
			Type:        spec.Type{Name: "string", Kind: spec.KindString},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "1 to 64", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 64}},
		},
		{
			ID: AttrManufacturingDate, Name: "ManufacturingDate",
			Type:        spec.Type{Name: "string", Kind: spec.KindString},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "8 to 16", Min: &spec.Bound{Int: 8}, Max: &spec.Bound{Int: 16}},
		},
		{
			ID: AttrPartNumber, Name: "PartNumber",
			Type:        spec.Type{Name: "string", Kind: spec.KindString},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "max 32", Max: &spec.Bound{Int: 32}},
		},
		{
			ID: AttrProductUrl, Name: "ProductUrl",
			Type:        spec.Type{Name: "string", Kind: spec.KindString},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "max 256", Max: &spec.Bound{Int: 256}},
		},
		{
			ID: AttrProductLabel, Name: "ProductLabel",
			Type:        spec.Type{Name: "string", Kind: spec.KindString},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "max 64", Max: &spec.Bound{Int: 64}},
		},
		{
			ID: AttrSerialNumber, Name: "SerialNumber",
			Type:        spec.Type{Name: "string", Kind: spec.KindString},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "max 32", Max: &spec.Bound{Int: 32}},
		},
		{
			ID: AttrLocalConfigDisabled, Name: "LocalConfigDisabled",
			Type:        spec.Type{Name: "bool", Kind: spec.KindBool},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Default:     false,
		},
		{
			ID: AttrReachable, Name: "Reachable",
			Type:        spec.Type{Name: "bool", Kind: spec.KindBool},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Default:     true,
		},
		{
			ID: AttrUniqueId, Name: "UniqueId",
			Type:        spec.Type{Name: "string", Kind: spec.KindString},
			Conformance: spec.Conformance{Text: "Rev >= v4, O", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfRevision, Rev: 4}, {Op: spec.ConfOptional}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "max 32", Max: &spec.Bound{Int: 32}},
		},
		{
			ID: AttrCapabilityMinima, Name: "CapabilityMinima",
			Type:        spec.Type{Name: "CapabilityMinimaStruct", Kind: spec.KindStruct, Struct: CapabilityMinimaStructDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Decode:      decodeAttrCapabilityMinima,
		},
		{
			ID: AttrProductAppearance, Name: "ProductAppearance",
			Type:        spec.Type{Name: "ProductAppearanceStruct", Kind: spec.KindStruct, Struct: ProductAppearanceStructDef},
			Conformance: spec.Conformance{Text: "[Rev >= v2]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfRevision, Rev: 2}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Decode:      decodeAttrProductAppearance,
		},
		{
			ID: AttrSpecificationVersion, Name: "SpecificationVersion",
			Type:        spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32},
			Conformance: spec.Conformance{Text: "Rev >= v3", Op: spec.ConfRevision, Rev: 3},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
			Default:     float64(0),
		},
		{
			ID: AttrMaxPathsPerInvoke, Name: "MaxPathsPerInvoke",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "Rev >= v3", Op: spec.ConfRevision, Rev: 3},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}},
			Default:     float64(1),
		},
		{
			ID: AttrConfigurationVersion, Name: "ConfigurationVersion",
			Type:        spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32},
			Conformance: spec.Conformance{Text: "Rev >= v6", Op: spec.ConfRevision, Rev: 6},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}},
			Default:     float64(1),
		},
	},
	Events: []spec.Event{
		{
			ID: EventStartUp, Name: "StartUp", Priority: spec.PriorityCritical,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "SoftwareVersion", Type: spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeStartUpEvent,
		},
		{
			ID: EventShutDown, Name: "ShutDown", Priority: spec.PriorityCritical,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeShutDownEvent,
		},
		{
			ID: EventLeave, Name: "Leave", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "FabricIndex", Type: spec.Type{Name: "fabric-idx", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "1 to 254", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 254}}},
			},
			Decode: decodeLeaveEvent,
		},
		{
			ID: EventReachableChanged, Name: "ReachableChanged", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "Reachable", Op: spec.ConfName, Name: "Reachable"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "ReachableNewValue", Type: spec.Type{Name: "bool", Kind: spec.KindBool}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeReachableChangedEvent,
		},
	},
}

func init() { spec.Register(Definition) }
