// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package laundrywashermode is the generated definition of the Matter LaundryWasherMode cluster
// (0x0051, revision 3, derived from ModeBase), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package laundrywashermode

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0051
	Name             = "LaundryWasherMode"
	Revision  uint16 = 3
)

// Attribute ids.
const (
	AttrSupportedModes uint32 = 0x0000 // list[ModeOptionStruct], M, R V, F
	AttrCurrentMode    uint32 = 0x0001 // uint8, M, R V, N
	AttrStartUpMode    uint32 = 0x0002 // uint8, X, RW VO, X N
	AttrOnMode         uint32 = 0x0003 // uint8, X, RW VO, X N
)

// Command ids.
const (
	CmdChangeToMode         uint32 = 0x00 // request → ChangeToModeResponse, M
	CmdChangeToModeResponse uint32 = 0x01 // response, M
)

// Feature is a LaundryWasherMode FeatureMap bit.
type Feature uint32

// FeatureMap bits.
const (
	FeatureOnOff Feature = 1 << 0 // DEPONOFF, X
)

// ModeChangeStatus is the ModeChangeStatus enum8.
type ModeChangeStatus uint8

// ModeChangeStatus values.
const (
	ModeChangeStatusSuccess         ModeChangeStatus = 0
	ModeChangeStatusUnsupportedMode ModeChangeStatus = 1
	ModeChangeStatusGenericFailure  ModeChangeStatus = 2
	ModeChangeStatusInvalidInMode   ModeChangeStatus = 3
)

// ModeChangeStatusDef describes ModeChangeStatus.
var ModeChangeStatusDef = &spec.Enum{Name: "ModeChangeStatus", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Success"},
	{Value: 1, Name: "UnsupportedMode"},
	{Value: 2, Name: "GenericFailure"},
	{Value: 3, Name: "InvalidInMode"},
}}

// ModeOptionStruct is the ModeOptionStruct struct.
type ModeOptionStruct struct {
	Label    string          // 0: string, M, max 64, F
	Mode     uint8           // 1: uint8, M, F
	ModeTags []ModeTagStruct // 2: list[ModeTagStruct], M, 1 to 8, F
}

// EncodeTLV implements spec.Encodable.
func (v ModeOptionStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutString(enc, tlv.ContextTag(0), v.Label)
	spec.PutUint[uint8](enc, tlv.ContextTag(1), v.Mode)
	spec.PutList(spec.PutStruct[ModeTagStruct])(enc, tlv.ContextTag(2), v.ModeTags)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ModeOptionStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ModeOptionStruct",
		spec.Bind(0, "Label", true, &v.Label, spec.DecodeStringIn(0, 64)),
		spec.Bind(1, "Mode", true, &v.Mode, spec.DecodeUint[uint8](8)),
		spec.Bind(2, "ModeTags", true, &v.ModeTags, spec.DecodeListIn(spec.DecodeStruct[ModeTagStruct], 1, 8)),
	)
}

// ModeOptionStructDef describes ModeOptionStruct.
var ModeOptionStructDef = &spec.Struct{Name: "ModeOptionStruct", Fields: []spec.Field{
	{ID: 0, Name: "Label", Type: spec.Type{Name: "string", Kind: spec.KindString}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Quality: spec.Quality{Fixed: true}, Constraint: spec.Constraint{Text: "max 64", Max: &spec.Bound{Int: 64}}},
	{ID: 1, Name: "Mode", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Quality: spec.Quality{Fixed: true}},
	{ID: 2, Name: "ModeTags", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "ModeTagStruct", Kind: spec.KindStruct, Struct: ModeTagStructDef}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Quality: spec.Quality{Fixed: true}, Constraint: spec.Constraint{Text: "1 to 8", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 8}}},
}}

// ModeTagStruct is the ModeTagStruct struct.
type ModeTagStruct struct {
	MfgCode *uint16 // 0: vendor-id, O, desc
	Value   ModeTag // 1: ModeTag, M
}

// EncodeTLV implements spec.Encodable.
func (v ModeTagStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutOptional(enc, tlv.ContextTag(0), v.MfgCode, spec.PutUint[uint16])
	spec.PutUint[ModeTag](enc, tlv.ContextTag(1), v.Value)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ModeTagStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ModeTagStruct",
		spec.Bind(0, "MfgCode", false, &v.MfgCode, spec.DecodeOptional(spec.DecodeUint[uint16](16))),
		spec.Bind(1, "Value", true, &v.Value, spec.DecodeUint[ModeTag](16)),
	)
}

// ModeTagStructDef describes ModeTagStruct.
var ModeTagStructDef = &spec.Struct{Name: "ModeTagStruct", Fields: []spec.Field{
	{ID: 0, Name: "MfgCode", Type: spec.Type{Name: "vendor-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
	{ID: 1, Name: "Value", Type: spec.Type{Name: "ModeTag", Kind: spec.KindEnum, Bits: 16, Enum: ModeTagDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// ModeTag is the ModeTag enum16.
type ModeTag uint16

// ModeTag values.
const (
	ModeTagAuto      ModeTag = 0
	ModeTagQuick     ModeTag = 1
	ModeTagQuiet     ModeTag = 2
	ModeTagLowNoise  ModeTag = 3
	ModeTagLowEnergy ModeTag = 4
	ModeTagVacation  ModeTag = 5
	ModeTagMin       ModeTag = 6
	ModeTagMax       ModeTag = 7
	ModeTagNight     ModeTag = 8
	ModeTagDay       ModeTag = 9
	ModeTagNormal    ModeTag = 16384
	ModeTagDelicate  ModeTag = 16385
	ModeTagHeavy     ModeTag = 16386
	ModeTagWhites    ModeTag = 16387
)

// ModeTagDef describes ModeTag.
var ModeTagDef = &spec.Enum{Name: "ModeTag", Bits: 16, Values: []spec.EnumValue{
	{Value: 0, Name: "Auto"},
	{Value: 1, Name: "Quick"},
	{Value: 2, Name: "Quiet"},
	{Value: 3, Name: "LowNoise"},
	{Value: 4, Name: "LowEnergy"},
	{Value: 5, Name: "Vacation"},
	{Value: 6, Name: "Min"},
	{Value: 7, Name: "Max"},
	{Value: 8, Name: "Night"},
	{Value: 9, Name: "Day"},
	{Value: 16384, Name: "Normal"},
	{Value: 16385, Name: "Delicate"},
	{Value: 16386, Name: "Heavy"},
	{Value: 16387, Name: "Whites"},
}}

// ChangeToModeRequest is the ChangeToMode command payload.
type ChangeToModeRequest struct {
	NewMode uint8 // 0: uint8, M, desc
}

// EncodeTLV implements spec.Encodable.
func (v ChangeToModeRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint8](enc, tlv.ContextTag(0), v.NewMode)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ChangeToModeRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ChangeToMode",
		spec.Bind(0, "NewMode", true, &v.NewMode, spec.DecodeUint[uint8](8)),
	)
}

// ChangeToModeResponse is the ChangeToModeResponse command payload.
type ChangeToModeResponse struct {
	Status     ModeChangeStatus // 0: ModeChangeStatus, M, desc
	StatusText string           // 1: string, [Status == Success], M, max 64
}

// EncodeTLV implements spec.Encodable.
func (v ChangeToModeResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[ModeChangeStatus](enc, tlv.ContextTag(0), v.Status)
	spec.PutString(enc, tlv.ContextTag(1), v.StatusText)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ChangeToModeResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ChangeToModeResponse",
		spec.Bind(0, "Status", true, &v.Status, spec.DecodeUint[ModeChangeStatus](8)),
		spec.Bind(1, "StatusText", true, &v.StatusText, spec.DecodeStringIn(0, 64)),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (ChangeToModeResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdChangeToModeResponse
}

func decodeChangeToModeRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[ChangeToModeRequest](n)
}

func decodeChangeToModeResponse(n spec.Node) (any, error) {
	return spec.DecodeStruct[ChangeToModeResponse](n)
}

func decodeAttrSupportedModes(n spec.Node) (any, error) {
	v, err := spec.DecodeListIn(spec.DecodeStruct[ModeOptionStruct], 2, 255)(n)
	return spec.List[ModeOptionStruct](v), err
}

// Definition is the LaundryWasherMode cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Base: "ModeBase",
	Features: []spec.Feature{
		{Name: "DEPONOFF", Title: "OnOff", Bit: 0, Conformance: spec.Conformance{Text: "X", Op: spec.ConfDisallowed}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrSupportedModes, Name: "SupportedModes",
			Type:        spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "ModeOptionStruct", Kind: spec.KindStruct, Struct: ModeOptionStructDef}}},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "2 to 255", Min: &spec.Bound{Int: 2}, Max: &spec.Bound{Int: 255}},
			Decode:      decodeAttrSupportedModes,
		},
		{
			ID: AttrCurrentMode, Name: "CurrentMode",
			Type:        spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
		},
		{
			ID: AttrStartUpMode, Name: "StartUpMode",
			Type:        spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "X", Op: spec.ConfDisallowed},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Quality:     spec.Quality{Nullable: true, NonVolatile: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
		},
		{
			ID: AttrOnMode, Name: "OnMode",
			Type:        spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "X", Op: spec.ConfDisallowed},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Quality:     spec.Quality{Nullable: true, NonVolatile: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
		},
	},
	Commands: []spec.Command{
		{
			ID: CmdChangeToMode, Name: "ChangeToMode", Direction: spec.Request,
			Response:    "ChangeToModeResponse",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "NewMode", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
			},
			Decode: decodeChangeToModeRequest,
		},
		{
			ID: CmdChangeToModeResponse, Name: "ChangeToModeResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "Status", Type: spec.Type{Name: "ModeChangeStatus", Kind: spec.KindEnum, Bits: 8, Enum: ModeChangeStatusDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "StatusText", Type: spec.Type{Name: "string", Kind: spec.KindString}, Conformance: spec.Conformance{Text: "[Status == Success], M", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfEq, Args: []spec.Conformance{{Op: spec.ConfName, Name: "Status"}, {Op: spec.ConfName, Name: "Success"}}}}}, {Op: spec.ConfMandatory}}}, Constraint: spec.Constraint{Text: "max 64", Max: &spec.Bound{Int: 64}}},
			},
			Decode: decodeChangeToModeResponse,
		},
	},
}

func init() { spec.Register(Definition) }
