// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package otasoftwareupdaterequestor

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, ProviderLocation{ProviderNodeId: uint64(1), Endpoint: uint16(1), FabricIndex: uint8(1)}, spec.DecodeStruct[ProviderLocation])
	spectest.RoundTripCommand(t, Definition, CmdAnnounceOtaProvider, spec.Request, AnnounceOtaProviderRequest{ProviderNodeId: uint64(1), VendorId: uint16(1), AnnouncementReason: AnnouncementReasonEnum(0), MetadataForNode: spectest.Ptr([]byte{1}), Endpoint: uint16(1)})
	spectest.RoundTripEvent(t, Definition, EventStateTransition, StateTransitionEvent{PreviousState: UpdateStateEnum(0), NewState: UpdateStateEnum(0), Reason: ChangeReasonEnum(0), TargetSoftwareVersion: spec.ValueOf(uint32(1))})
	spectest.RoundTripEvent(t, Definition, EventVersionApplied, VersionAppliedEvent{SoftwareVersion: uint32(1), ProductId: uint16(1)})
	spectest.RoundTripEvent(t, Definition, EventDownloadError, DownloadErrorEvent{SoftwareVersion: uint32(1), BytesDownloaded: uint64(1), ProgressPercent: spec.ValueOf(uint8(1)), PlatformCode: spec.ValueOf(int64(1))})
	spectest.RoundTripAttribute(t, Definition, AttrDefaultOtaProviders, spec.List[ProviderLocation]([]ProviderLocation{ProviderLocation{ProviderNodeId: uint64(1), Endpoint: uint16(1), FabricIndex: uint8(1)}}))
}
