// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package generalcommissioning

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, BasicCommissioningInfo{FailSafeExpiryLengthSeconds: uint16(1), MaxCumulativeFailsafeSeconds: uint16(1)}, spec.DecodeStruct[BasicCommissioningInfo])
	spectest.RoundTripCommand(t, Definition, CmdArmFailSafe, spec.Request, ArmFailSafeRequest{ExpiryLengthSeconds: uint16(1), Breadcrumb: uint64(1)})
	spectest.RoundTripCommand(t, Definition, CmdArmFailSafeResponse, spec.Response, ArmFailSafeResponse{ErrorCode: CommissioningErrorEnum(0), DebugText: "x"})
	spectest.RoundTripCommand(t, Definition, CmdSetRegulatoryConfig, spec.Request, SetRegulatoryConfigRequest{NewRegulatoryConfig: RegulatoryLocationTypeEnum(0), CountryCode: "xx", Breadcrumb: uint64(1)})
	spectest.RoundTripCommand(t, Definition, CmdSetRegulatoryConfigResponse, spec.Response, SetRegulatoryConfigResponse{ErrorCode: CommissioningErrorEnum(0), DebugText: "x"})
	spectest.RoundTripCommand(t, Definition, CmdCommissioningComplete, spec.Request, CommissioningCompleteRequest{})
	spectest.RoundTripCommand(t, Definition, CmdCommissioningCompleteResponse, spec.Response, CommissioningCompleteResponse{ErrorCode: CommissioningErrorEnum(0), DebugText: "x"})
	spectest.RoundTripCommand(t, Definition, CmdSetTcAcknowledgements, spec.Request, SetTcAcknowledgementsRequest{TcVersion: uint16(1), TcUserResponse: uint16(1)})
	spectest.RoundTripCommand(t, Definition, CmdSetTcAcknowledgementsResponse, spec.Response, SetTcAcknowledgementsResponse{ErrorCode: CommissioningErrorEnum(0)})
	spectest.RoundTripAttribute(t, Definition, AttrBasicCommissioningInfo, BasicCommissioningInfo{FailSafeExpiryLengthSeconds: uint16(1), MaxCumulativeFailsafeSeconds: uint16(1)})
}
