// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package thermostat

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, PresetStruct{PresetHandle: spec.ValueOf([]byte{1}), PresetScenario: PresetScenarioEnum(1), Name: spectest.Ptr(spec.ValueOf("x")), CoolingSetpoint: spectest.Ptr(int16(1)), HeatingSetpoint: spectest.Ptr(int16(1)), BuiltIn: spec.ValueOf(true)}, spec.DecodeStruct[PresetStruct])
	spectest.RoundTrip(t, PresetTypeStruct{PresetScenario: PresetScenarioEnum(1), NumberOfPresets: uint8(1), PresetTypeFeatures: PresetTypeFeaturesBitmap(1 << 0)}, spec.DecodeStruct[PresetTypeStruct])
	spectest.RoundTrip(t, ScheduleStruct{ScheduleHandle: spec.ValueOf([]byte{1}), SystemMode: SystemModeEnum(0), Name: spectest.Ptr("x"), PresetHandle: spectest.Ptr([]byte{1}), Transitions: []ScheduleTransitionStruct{ScheduleTransitionStruct{DayOfWeek: ScheduleDayOfWeekBitmap(1 << 0), TransitionTime: uint16(1), PresetHandle: spectest.Ptr([]byte{1}), SystemMode: spectest.Ptr(SystemModeEnum(0)), CoolingSetpoint: spectest.Ptr(int16(1)), HeatingSetpoint: spectest.Ptr(int16(1))}}, BuiltIn: spec.ValueOf(true)}, spec.DecodeStruct[ScheduleStruct])
	spectest.RoundTrip(t, ScheduleTransitionStruct{DayOfWeek: ScheduleDayOfWeekBitmap(1 << 0), TransitionTime: uint16(1), PresetHandle: spectest.Ptr([]byte{1}), SystemMode: spectest.Ptr(SystemModeEnum(0)), CoolingSetpoint: spectest.Ptr(int16(1)), HeatingSetpoint: spectest.Ptr(int16(1))}, spec.DecodeStruct[ScheduleTransitionStruct])
	spectest.RoundTrip(t, ScheduleTypeStruct{SystemMode: SystemModeEnum(0), NumberOfSchedules: uint8(1), ScheduleTypeFeatures: ScheduleTypeFeaturesBitmap(1 << 0)}, spec.DecodeStruct[ScheduleTypeStruct])
	spectest.RoundTrip(t, ThermostatSuggestionStruct{UniqueId: uint8(1), PresetHandle: []byte{1}, EffectiveTime: uint32(1), ExpirationTime: uint32(1)}, spec.DecodeStruct[ThermostatSuggestionStruct])
	spectest.RoundTrip(t, WeeklyScheduleTransitionStruct{TransitionTime: uint16(1), HeatSetpoint: spec.ValueOf(int16(1)), CoolSetpoint: spec.ValueOf(int16(1))}, spec.DecodeStruct[WeeklyScheduleTransitionStruct])
	spectest.RoundTrip(t, AtomicResponseAttributeStatusEntry{AttributeId: uint32(1), StatusCode: Status(0)}, spec.DecodeStruct[AtomicResponseAttributeStatusEntry])
	spectest.RoundTripCommand(t, Definition, CmdSetpointRaiseLower, spec.Request, SetpointRaiseLowerRequest{Mode: SetpointRaiseLowerModeEnum(0), Amount: int8(1)})
	spectest.RoundTripCommand(t, Definition, CmdAddThermostatSuggestionResponse, spec.Response, AddThermostatSuggestionResponse{UniqueId: uint8(1)})
	spectest.RoundTripCommand(t, Definition, CmdSetActiveScheduleRequest, spec.Request, SetActiveScheduleRequestRequest{ScheduleHandle: []byte{1}})
	spectest.RoundTripCommand(t, Definition, CmdSetActivePresetRequest, spec.Request, SetActivePresetRequestRequest{PresetHandle: spec.ValueOf([]byte{1})})
	spectest.RoundTripCommand(t, Definition, CmdAddThermostatSuggestion, spec.Request, AddThermostatSuggestionRequest{PresetHandle: []byte{1}, EffectiveTime: spec.ValueOf(uint32(1)), ExpirationInMinutes: uint16(30)})
	spectest.RoundTripCommand(t, Definition, CmdRemoveThermostatSuggestion, spec.Request, RemoveThermostatSuggestionRequest{UniqueId: uint8(1)})
	spectest.RoundTripCommand(t, Definition, CmdAtomicResponse, spec.Response, AtomicResponse{StatusCode: Status(0), AttributeStatus: []AtomicResponseAttributeStatusEntry{AtomicResponseAttributeStatusEntry{AttributeId: uint32(1), StatusCode: Status(0)}}, Timeout: spectest.Ptr(uint16(1))})
	spectest.RoundTripCommand(t, Definition, CmdAtomicRequest, spec.Request, AtomicRequestRequest{RequestType: uint8(1), AttributeRequests: []uint32{uint32(1)}, Timeout: spectest.Ptr(uint16(1))})
	spectest.RoundTripEvent(t, Definition, EventSystemModeChange, SystemModeChangeEvent{PreviousSystemMode: spectest.Ptr(SystemModeEnum(0)), CurrentSystemMode: SystemModeEnum(0)})
	spectest.RoundTripEvent(t, Definition, EventLocalTemperatureChange, LocalTemperatureChangeEvent{CurrentLocalTemperature: spec.ValueOf(int16(1))})
	spectest.RoundTripEvent(t, Definition, EventOccupancyChange, OccupancyChangeEvent{PreviousOccupancy: spectest.Ptr(OccupancyBitmap(1 << 0)), CurrentOccupancy: OccupancyBitmap(1 << 0)})
	spectest.RoundTripEvent(t, Definition, EventSetpointChange, SetpointChangeEvent{SystemMode: SystemModeEnum(0), Occupancy: spectest.Ptr(OccupancyBitmap(1 << 0)), PreviousSetpoint: spectest.Ptr(int16(1)), CurrentSetpoint: int16(1)})
	spectest.RoundTripEvent(t, Definition, EventRunningStateChange, RunningStateChangeEvent{PreviousRunningState: spectest.Ptr(RelayStateBitmap(1 << 0)), CurrentRunningState: RelayStateBitmap(1 << 0)})
	spectest.RoundTripEvent(t, Definition, EventRunningModeChange, RunningModeChangeEvent{PreviousRunningMode: spectest.Ptr(ThermostatRunningModeEnum(0)), CurrentRunningMode: ThermostatRunningModeEnum(0)})
	spectest.RoundTripEvent(t, Definition, EventActiveScheduleChange, ActiveScheduleChangeEvent{PreviousScheduleHandle: spectest.Ptr(spec.ValueOf([]byte{1})), CurrentScheduleHandle: spec.ValueOf([]byte{1})})
	spectest.RoundTripEvent(t, Definition, EventActivePresetChange, ActivePresetChangeEvent{PreviousPresetHandle: spectest.Ptr(spec.ValueOf([]byte{1})), CurrentPresetHandle: spec.ValueOf([]byte{1})})
	spectest.RoundTripAttribute(t, Definition, AttrPresetTypes, spec.List[PresetTypeStruct]([]PresetTypeStruct{PresetTypeStruct{PresetScenario: PresetScenarioEnum(1), NumberOfPresets: uint8(1), PresetTypeFeatures: PresetTypeFeaturesBitmap(1 << 0)}}))
	spectest.RoundTripAttribute(t, Definition, AttrScheduleTypes, spec.List[ScheduleTypeStruct]([]ScheduleTypeStruct{ScheduleTypeStruct{SystemMode: SystemModeEnum(0), NumberOfSchedules: uint8(1), ScheduleTypeFeatures: ScheduleTypeFeaturesBitmap(1 << 0)}}))
	spectest.RoundTripAttribute(t, Definition, AttrPresets, spec.List[PresetStruct]([]PresetStruct{PresetStruct{PresetHandle: spec.ValueOf([]byte{1}), PresetScenario: PresetScenarioEnum(1), Name: spectest.Ptr(spec.ValueOf("x")), CoolingSetpoint: spectest.Ptr(int16(1)), HeatingSetpoint: spectest.Ptr(int16(1)), BuiltIn: spec.ValueOf(true)}}))
	spectest.RoundTripAttribute(t, Definition, AttrSchedules, spec.List[ScheduleStruct]([]ScheduleStruct{ScheduleStruct{ScheduleHandle: spec.ValueOf([]byte{1}), SystemMode: SystemModeEnum(0), Name: spectest.Ptr("x"), PresetHandle: spectest.Ptr([]byte{1}), Transitions: []ScheduleTransitionStruct{ScheduleTransitionStruct{DayOfWeek: ScheduleDayOfWeekBitmap(1 << 0), TransitionTime: uint16(1), PresetHandle: spectest.Ptr([]byte{1}), SystemMode: spectest.Ptr(SystemModeEnum(0)), CoolingSetpoint: spectest.Ptr(int16(1)), HeatingSetpoint: spectest.Ptr(int16(1))}}, BuiltIn: spec.ValueOf(true)}}))
	spectest.RoundTripAttribute(t, Definition, AttrThermostatSuggestions, spec.List[ThermostatSuggestionStruct]([]ThermostatSuggestionStruct{ThermostatSuggestionStruct{UniqueId: uint8(1), PresetHandle: []byte{1}, EffectiveTime: uint32(1), ExpirationTime: uint32(1)}}))
}
