// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

package chipdm

import (
	"flag"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"testing"

	"github.com/SukramJ/go-fabric/parity"
	"github.com/SukramJ/go-fabric/schema"
)

// No build tag: the cross-check is part of every `go test ./...`. It reads
// CHIP's data model from a connectedhomeip checkout at test time (nothing of
// it is committed, ADR 0015) and skips, saying why, without one — unless
// GOFABRIC_CHIP_REQUIRED is set, as the CI job that provides the checkout
// sets it, which turns the skip into a failure.

var updateDoc = flag.Bool("update-chipdm-doc", false,
	"rewrite the generated block of docs/chip-datamodel-crosscheck.md")

const (
	repoRoot = "../.."
	docPath  = "docs/chip-datamodel-crosscheck.md"
	docBegin = "<!-- BEGIN GENERATED by internal/chipdm TestChipDataModelCrosscheck; do not edit -->"
	docEnd   = "<!-- END GENERATED -->"
)

func loadSnapshot(t *testing.T) (*Model, SnapshotInfo) {
	t.Helper()
	m, info, err := LoadSnapshot(parity.SchemaJSON())
	if err != nil {
		t.Fatal(err)
	}
	return m, info
}

// makeVar reads a `NAME ?= value` assignment of the Makefile.
func makeVar(t *testing.T, name string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(repoRoot, "Makefile"))
	if err != nil {
		t.Fatal(err)
	}
	m := regexp.MustCompile(`(?m)^` + regexp.QuoteMeta(name) + `\s*\?=\s*(\S+)\s*$`).FindSubmatch(data)
	if m == nil {
		t.Fatalf("the Makefile does not assign %s", name)
	}
	return string(m[1])
}

// chipRoot is the connectedhomeip checkout: GOFABRIC_CHIP_ROOT (the
// variable the chip-tool harness reads), else the sibling of the main
// checkout CLAUDE.md names (../connectedhomeip) — found through git's
// common directory, so a test run from a linked worktree finds it too —
// else the sibling of this tree.
func chipRoot() string {
	if root := os.Getenv("GOFABRIC_CHIP_ROOT"); root != "" {
		return root
	}
	if out, err := exec.Command("git", "-C", repoRoot, "rev-parse", "--path-format=absolute", "--git-common-dir").Output(); err == nil {
		main := filepath.Dir(strings.TrimSpace(string(out)))
		candidate := filepath.Join(main, "..", "connectedhomeip")
		if _, err := os.Stat(candidate); err == nil {
			return candidate
		}
	}
	return filepath.Join(repoRoot, "..", "connectedhomeip")
}

var chipOnce struct {
	sync.Once
	model *ChipModel
	skip  string
	err   error
}

// chipModel reads CHIP's data model at the pin once per test binary, or
// skips the calling test (fails it under GOFABRIC_CHIP_REQUIRED) when no
// checkout holds the pinned commit's data_model/<version>.
func chipModel(t *testing.T) *ChipModel {
	t.Helper()
	pin := makeVar(t, "CHIP_TEST_IMAGE_COMMIT")
	_, info := loadSnapshot(t)
	version := DataModelVersion(info.Revision)
	chipOnce.Do(func() {
		root := chipRoot()
		if _, err := exec.LookPath("git"); err != nil {
			chipOnce.skip = "git is not installed"
			return
		}
		if _, err := TreeID(root, pin, version); err != nil {
			chipOnce.skip = "no connectedhomeip checkout with data_model/" + version + " at the pin " + pin +
				" at " + root + " (set GOFABRIC_CHIP_ROOT, or run make chiptool-setup): " + err.Error()
			return
		}
		chipOnce.model, chipOnce.err = ReadChipModel(root, pin, version)
	})
	switch {
	case chipOnce.err != nil:
		t.Fatal(chipOnce.err)
	case chipOnce.skip != "" && os.Getenv("GOFABRIC_CHIP_REQUIRED") != "":
		t.Fatalf("GOFABRIC_CHIP_REQUIRED is set, but %s", chipOnce.skip)
	case chipOnce.skip != "":
		t.Skip(chipOnce.skip)
	}
	return chipOnce.model
}

// TestChipDataModelCrosscheck compares the whole snapshot with CHIP's data
// model and holds every difference to the acknowledged table: it fails on a
// difference the table does not explain and on an entry that explains
// none. It also holds docs/chip-datamodel-crosscheck.md's generated block
// to the result.
func TestChipDataModelCrosscheck(t *testing.T) {
	chip := chipModel(t)
	ours, info := loadSnapshot(t)
	res := Compare(ours, chip.Model)
	rec := Reconcile(res.Differences, Acknowledged)

	for _, d := range rec.Unexplained {
		t.Errorf("unexplained difference: %s — fix the snapshot side, or classify it in acknowledged.go "+
			"(class i, ii or iv with a reason and a source), or normalize it in compare.go if it is representation only", d)
	}
	for _, a := range rec.Stale {
		t.Errorf("stale acknowledgement: %s %s (chip %q, ours %q) explains no difference any more — remove it",
			a.Path, a.Property, a.Chip, a.Ours)
	}
	if res.Compared["cluster"] != len(ours.Clusters) || res.Compared["deviceType"] != len(ours.DeviceTypes) {
		t.Errorf("compared %d of %d clusters and %d of %d device types",
			res.Compared["cluster"], len(ours.Clusters), res.Compared["deviceType"], len(ours.DeviceTypes))
	}

	block := ReportInput{
		Snapshot:       info,
		SnapshotSHA256: schema.SchemaSnapshotSHA256,
		Chip:           chip.Provenance,
		HarnessCommit:  makeVar(t, "CHIP_TEST_IMAGE_COMMIT"),
		Result:         res,
		Reconciliation: rec,
		Acknowledged:   Acknowledged,
	}.Render()
	file := filepath.Join(repoRoot, docPath)
	doc, err := os.ReadFile(file) //nolint:gosec // a fixed repository path
	if err != nil {
		t.Fatal(err)
	}
	text := string(doc)
	b, e := strings.Index(text, docBegin), strings.Index(text, docEnd)
	if b < 0 || e < b {
		t.Fatalf("%s lacks the generated-block markers", docPath)
	}
	updated := text[:b] + docBegin + "\n\n" + block + "\n" + text[e:]
	if updated == text {
		return
	}
	if *updateDoc {
		if err := os.WriteFile(file, []byte(updated), 0o644); err != nil { //nolint:gosec // a committed document
			t.Fatal(err)
		}
		return
	}
	t.Errorf("%s's generated block is out of date; regenerate: "+
		"go test ./internal/chipdm/ -run TestChipDataModelCrosscheck -args -update-chipdm-doc", docPath)
}

// TestAcknowledgedEntries holds the table's own shape, with or without a
// checkout: every entry cites a reason and a source, and class (ii)
// entries, and only they, state their impact.
func TestAcknowledgedEntries(t *testing.T) {
	t.Parallel()
	for _, a := range Acknowledged {
		if a.Reason == "" || a.Source == "" {
			t.Errorf("acknowledgement %s %s lacks a reason or a source", a.Path, a.Property)
		}
		if (a.Class == ClassCHIP) != (a.Impact != "") {
			t.Errorf("acknowledgement %s %s: class (ii) entries, and only they, state their impact", a.Path, a.Property)
		}
	}
}

// TestChipDataModelPins holds the Makefile's data model directory to the
// snapshot's Matter revision, and the data read to the pins.
func TestChipDataModelPins(t *testing.T) {
	_, info := loadSnapshot(t)
	want := DataModelVersion(info.Revision)
	if v := makeVar(t, "CHIP_DATA_MODEL_VERSION"); v != want {
		t.Errorf("the Makefile's CHIP_DATA_MODEL_VERSION is %s, the snapshot is Matter %s (data_model/%s)", v, info.Revision, want)
	}
	chip := chipModel(t)
	p := chip.Provenance
	if p.Commit != makeVar(t, "CHIP_TEST_IMAGE_COMMIT") || p.DataModel != want || p.Tree == "" || p.SpecTag == "" {
		t.Errorf("incomplete or mismatched provenance: %+v", p)
	}
}
