// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package pumpconfigurationandcontrol is the generated definition of the Matter PumpConfigurationAndControl cluster
// (0x0200, revision 5), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package pumpconfigurationandcontrol

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0200
	Name             = "PumpConfigurationAndControl"
	Revision  uint16 = 5
)

// Attribute ids.
const (
	AttrMaxPressure            uint32 = 0x0000 // int16, M, R V, X F
	AttrMaxSpeed               uint32 = 0x0001 // uint16, M, R V, X F
	AttrMaxFlow                uint32 = 0x0002 // uint16, M, R V, X F
	AttrMinConstPressure       uint32 = 0x0003 // int16, PRSCONST, [AUTO], R V, X F
	AttrMaxConstPressure       uint32 = 0x0004 // int16, PRSCONST, [AUTO], R V, X F
	AttrMinCompPressure        uint32 = 0x0005 // int16, PRSCOMP, [AUTO], R V, X F
	AttrMaxCompPressure        uint32 = 0x0006 // int16, PRSCOMP, [AUTO], R V, X F
	AttrMinConstSpeed          uint32 = 0x0007 // uint16, SPD, [AUTO], R V, X F
	AttrMaxConstSpeed          uint32 = 0x0008 // uint16, SPD, [AUTO], R V, X F
	AttrMinConstFlow           uint32 = 0x0009 // uint16, FLW, [AUTO], R V, X F
	AttrMaxConstFlow           uint32 = 0x000A // uint16, FLW, [AUTO], R V, X F
	AttrMinConstTemp           uint32 = 0x000B // int16, TEMP, [AUTO], R V, X F
	AttrMaxConstTemp           uint32 = 0x000C // int16, TEMP, [AUTO], R V, X F
	AttrPumpStatus             uint32 = 0x0010 // PumpStatusBitmap, O, R V
	AttrEffectiveOperationMode uint32 = 0x0011 // OperationModeEnum, M, R V, N
	AttrEffectiveControlMode   uint32 = 0x0012 // ControlModeEnum, M, R V, N
	AttrCapacity               uint32 = 0x0013 // int16, M, R V, X
	AttrSpeed                  uint32 = 0x0014 // uint16, O, R V, X
	AttrLifetimeRunningHours   uint32 = 0x0015 // uint24, O, RW VM, X N
	AttrPower                  uint32 = 0x0016 // uint24, O, R V, X
	AttrLifetimeEnergyConsumed uint32 = 0x0017 // uint32, O, RW VM, X N
	AttrOperationMode          uint32 = 0x0020 // OperationModeEnum, M, RW VM, N
	AttrControlMode            uint32 = 0x0021 // ControlModeEnum, O, RW VM, N
	AttrAlarmMask              uint32 = 0x0022 // uint16, D, RW VO
)

// Event ids.
const (
	EventSupplyVoltageLow          uint32 = 0x00 // info, O
	EventSupplyVoltageHigh         uint32 = 0x01 // info, O
	EventPowerMissingPhase         uint32 = 0x02 // info, O
	EventSystemPressureLow         uint32 = 0x03 // info, O
	EventSystemPressureHigh        uint32 = 0x04 // info, O
	EventDryRunning                uint32 = 0x05 // critical, O
	EventMotorTemperatureHigh      uint32 = 0x06 // info, O
	EventPumpMotorFatalFailure     uint32 = 0x07 // critical, O
	EventElectronicTemperatureHigh uint32 = 0x08 // info, O
	EventPumpBlocked               uint32 = 0x09 // critical, O
	EventSensorFailure             uint32 = 0x0A // info, O
	EventElectronicNonFatalFailure uint32 = 0x0B // info, O
	EventElectronicFatalFailure    uint32 = 0x0C // critical, O
	EventGeneralFault              uint32 = 0x0D // info, O
	EventLeakage                   uint32 = 0x0E // info, O
	EventAirDetection              uint32 = 0x0F // info, O
	EventTurbineOperation          uint32 = 0x10 // info, O
)

// Feature is a PumpConfigurationAndControl FeatureMap bit.
type Feature uint32

// FeatureMap bits.
const (
	FeatureConstantPressure    Feature = 1 << 0 // PRSCONST, O.a+
	FeatureCompensatedPressure Feature = 1 << 1 // PRSCOMP, O.a+
	FeatureConstantFlow        Feature = 1 << 2 // FLW, O.a+
	FeatureConstantSpeed       Feature = 1 << 3 // SPD, O.a+
	FeatureConstantTemperature Feature = 1 << 4 // TEMP, O.a+
	FeatureAutomatic           Feature = 1 << 5 // AUTO, O
	FeatureLocalOperation      Feature = 1 << 6 // LOCAL, O
)

// ControlModeEnum is the ControlModeEnum enum8.
type ControlModeEnum uint8

// ControlModeEnum values.
const (
	ControlModeConstantSpeed        ControlModeEnum = 0 // SPD
	ControlModeConstantPressure     ControlModeEnum = 1 // PRSCONST
	ControlModeProportionalPressure ControlModeEnum = 2 // PRSCOMP
	ControlModeConstantFlow         ControlModeEnum = 3 // FLW
	ControlModeConstantTemperature  ControlModeEnum = 5 // TEMP
	ControlModeAutomatic            ControlModeEnum = 7 // AUTO
)

// ControlModeEnumDef describes ControlModeEnum.
var ControlModeEnumDef = &spec.Enum{Name: "ControlModeEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "ConstantSpeed", Conformance: spec.Conformance{Text: "SPD", Op: spec.ConfName, Name: "SPD"}},
	{Value: 1, Name: "ConstantPressure", Conformance: spec.Conformance{Text: "PRSCONST", Op: spec.ConfName, Name: "PRSCONST"}},
	{Value: 2, Name: "ProportionalPressure", Conformance: spec.Conformance{Text: "PRSCOMP", Op: spec.ConfName, Name: "PRSCOMP"}},
	{Value: 3, Name: "ConstantFlow", Conformance: spec.Conformance{Text: "FLW", Op: spec.ConfName, Name: "FLW"}},
	{Value: 5, Name: "ConstantTemperature", Conformance: spec.Conformance{Text: "TEMP", Op: spec.ConfName, Name: "TEMP"}},
	{Value: 7, Name: "Automatic", Conformance: spec.Conformance{Text: "AUTO", Op: spec.ConfName, Name: "AUTO"}},
}}

// OperationModeEnum is the OperationModeEnum enum8.
type OperationModeEnum uint8

// OperationModeEnum values.
const (
	OperationModeNormal  OperationModeEnum = 0 // M
	OperationModeMinimum OperationModeEnum = 1 // SPD
	OperationModeMaximum OperationModeEnum = 2 // SPD
	OperationModeLocal   OperationModeEnum = 3 // LOCAL
)

// OperationModeEnumDef describes OperationModeEnum.
var OperationModeEnumDef = &spec.Enum{Name: "OperationModeEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Normal", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Minimum", Conformance: spec.Conformance{Text: "SPD", Op: spec.ConfName, Name: "SPD"}},
	{Value: 2, Name: "Maximum", Conformance: spec.Conformance{Text: "SPD", Op: spec.ConfName, Name: "SPD"}},
	{Value: 3, Name: "Local", Conformance: spec.Conformance{Text: "LOCAL", Op: spec.ConfName, Name: "LOCAL"}},
}}

// PumpStatusBitmap is the PumpStatusBitmap map16.
type PumpStatusBitmap uint16

// PumpStatusBitmap bits; a member wider than one bit is its mask.
const (
	PumpStatusDeviceFault       PumpStatusBitmap = 1 << 0 // M
	PumpStatusSupplyFault       PumpStatusBitmap = 1 << 1 // M
	PumpStatusSpeedLow          PumpStatusBitmap = 1 << 2 // M
	PumpStatusSpeedHigh         PumpStatusBitmap = 1 << 3 // M
	PumpStatusLocalOverride     PumpStatusBitmap = 1 << 4 // M
	PumpStatusRunning           PumpStatusBitmap = 1 << 5 // M
	PumpStatusRemotePressure    PumpStatusBitmap = 1 << 6 // M
	PumpStatusRemoteFlow        PumpStatusBitmap = 1 << 7 // M
	PumpStatusRemoteTemperature PumpStatusBitmap = 1 << 8 // M
)

// PumpStatusBitmapDef describes PumpStatusBitmap.
var PumpStatusBitmapDef = &spec.Bitmap{Name: "PumpStatusBitmap", Bits: 16, Members: []spec.BitmapMember{
	{Name: "DeviceFault", Bit: 0, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "SupplyFault", Bit: 1, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "SpeedLow", Bit: 2, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "SpeedHigh", Bit: 3, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "LocalOverride", Bit: 4, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "Running", Bit: 5, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "RemotePressure", Bit: 6, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "RemoteFlow", Bit: 7, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "RemoteTemperature", Bit: 8, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// SupplyVoltageLowEvent is the SupplyVoltageLow event payload.
type SupplyVoltageLowEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v SupplyVoltageLowEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *SupplyVoltageLowEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "SupplyVoltageLow")
}

// SupplyVoltageHighEvent is the SupplyVoltageHigh event payload.
type SupplyVoltageHighEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v SupplyVoltageHighEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *SupplyVoltageHighEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "SupplyVoltageHigh")
}

// PowerMissingPhaseEvent is the PowerMissingPhase event payload.
type PowerMissingPhaseEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v PowerMissingPhaseEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *PowerMissingPhaseEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "PowerMissingPhase")
}

// SystemPressureLowEvent is the SystemPressureLow event payload.
type SystemPressureLowEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v SystemPressureLowEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *SystemPressureLowEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "SystemPressureLow")
}

// SystemPressureHighEvent is the SystemPressureHigh event payload.
type SystemPressureHighEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v SystemPressureHighEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *SystemPressureHighEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "SystemPressureHigh")
}

// DryRunningEvent is the DryRunning event payload.
type DryRunningEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v DryRunningEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *DryRunningEvent) DecodeTLV(n spec.Node) error { return spec.DecodeFields(n, "DryRunning") }

// MotorTemperatureHighEvent is the MotorTemperatureHigh event payload.
type MotorTemperatureHighEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v MotorTemperatureHighEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *MotorTemperatureHighEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "MotorTemperatureHigh")
}

// PumpMotorFatalFailureEvent is the PumpMotorFatalFailure event payload.
type PumpMotorFatalFailureEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v PumpMotorFatalFailureEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *PumpMotorFatalFailureEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "PumpMotorFatalFailure")
}

// ElectronicTemperatureHighEvent is the ElectronicTemperatureHigh event payload.
type ElectronicTemperatureHighEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v ElectronicTemperatureHighEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ElectronicTemperatureHighEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ElectronicTemperatureHigh")
}

// PumpBlockedEvent is the PumpBlocked event payload.
type PumpBlockedEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v PumpBlockedEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *PumpBlockedEvent) DecodeTLV(n spec.Node) error { return spec.DecodeFields(n, "PumpBlocked") }

// SensorFailureEvent is the SensorFailure event payload.
type SensorFailureEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v SensorFailureEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *SensorFailureEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "SensorFailure")
}

// ElectronicNonFatalFailureEvent is the ElectronicNonFatalFailure event payload.
type ElectronicNonFatalFailureEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v ElectronicNonFatalFailureEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ElectronicNonFatalFailureEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ElectronicNonFatalFailure")
}

// ElectronicFatalFailureEvent is the ElectronicFatalFailure event payload.
type ElectronicFatalFailureEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v ElectronicFatalFailureEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ElectronicFatalFailureEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ElectronicFatalFailure")
}

// GeneralFaultEvent is the GeneralFault event payload.
type GeneralFaultEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v GeneralFaultEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *GeneralFaultEvent) DecodeTLV(n spec.Node) error { return spec.DecodeFields(n, "GeneralFault") }

// LeakageEvent is the Leakage event payload.
type LeakageEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v LeakageEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *LeakageEvent) DecodeTLV(n spec.Node) error { return spec.DecodeFields(n, "Leakage") }

// AirDetectionEvent is the AirDetection event payload.
type AirDetectionEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v AirDetectionEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *AirDetectionEvent) DecodeTLV(n spec.Node) error { return spec.DecodeFields(n, "AirDetection") }

// TurbineOperationEvent is the TurbineOperation event payload.
type TurbineOperationEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v TurbineOperationEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *TurbineOperationEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "TurbineOperation")
}

func decodeSupplyVoltageLowEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[SupplyVoltageLowEvent](n)
}

func decodeSupplyVoltageHighEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[SupplyVoltageHighEvent](n)
}

func decodePowerMissingPhaseEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[PowerMissingPhaseEvent](n)
}

func decodeSystemPressureLowEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[SystemPressureLowEvent](n)
}

func decodeSystemPressureHighEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[SystemPressureHighEvent](n)
}

func decodeDryRunningEvent(n spec.Node) (any, error) { return spec.DecodeStruct[DryRunningEvent](n) }

func decodeMotorTemperatureHighEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[MotorTemperatureHighEvent](n)
}

func decodePumpMotorFatalFailureEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[PumpMotorFatalFailureEvent](n)
}

func decodeElectronicTemperatureHighEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[ElectronicTemperatureHighEvent](n)
}

func decodePumpBlockedEvent(n spec.Node) (any, error) { return spec.DecodeStruct[PumpBlockedEvent](n) }

func decodeSensorFailureEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[SensorFailureEvent](n)
}

func decodeElectronicNonFatalFailureEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[ElectronicNonFatalFailureEvent](n)
}

func decodeElectronicFatalFailureEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[ElectronicFatalFailureEvent](n)
}

func decodeGeneralFaultEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[GeneralFaultEvent](n)
}

func decodeLeakageEvent(n spec.Node) (any, error) { return spec.DecodeStruct[LeakageEvent](n) }

func decodeAirDetectionEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[AirDetectionEvent](n)
}

func decodeTurbineOperationEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[TurbineOperationEvent](n)
}

// Definition is the PumpConfigurationAndControl cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Features: []spec.Feature{
		{Name: "PRSCONST", Title: "ConstantPressure", Bit: 0, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "PRSCOMP", Title: "CompensatedPressure", Bit: 1, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "FLW", Title: "ConstantFlow", Bit: 2, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "SPD", Title: "ConstantSpeed", Bit: 3, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "TEMP", Title: "ConstantTemperature", Bit: 4, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "AUTO", Title: "Automatic", Bit: 5, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
		{Name: "LOCAL", Title: "LocalOperation", Bit: 6, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrMaxPressure, Name: "MaxPressure",
			Type:        spec.Type{Name: "int16", Kind: spec.KindInt, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrMaxSpeed, Name: "MaxSpeed",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrMaxFlow, Name: "MaxFlow",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrMinConstPressure, Name: "MinConstPressure",
			Type:        spec.Type{Name: "int16", Kind: spec.KindInt, Bits: 16},
			Conformance: spec.Conformance{Text: "PRSCONST, [AUTO]", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PRSCONST"}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "AUTO"}}}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrMaxConstPressure, Name: "MaxConstPressure",
			Type:        spec.Type{Name: "int16", Kind: spec.KindInt, Bits: 16},
			Conformance: spec.Conformance{Text: "PRSCONST, [AUTO]", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PRSCONST"}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "AUTO"}}}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrMinCompPressure, Name: "MinCompPressure",
			Type:        spec.Type{Name: "int16", Kind: spec.KindInt, Bits: 16},
			Conformance: spec.Conformance{Text: "PRSCOMP, [AUTO]", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PRSCOMP"}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "AUTO"}}}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrMaxCompPressure, Name: "MaxCompPressure",
			Type:        spec.Type{Name: "int16", Kind: spec.KindInt, Bits: 16},
			Conformance: spec.Conformance{Text: "PRSCOMP, [AUTO]", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PRSCOMP"}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "AUTO"}}}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrMinConstSpeed, Name: "MinConstSpeed",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "SPD, [AUTO]", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfName, Name: "SPD"}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "AUTO"}}}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrMaxConstSpeed, Name: "MaxConstSpeed",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "SPD, [AUTO]", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfName, Name: "SPD"}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "AUTO"}}}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrMinConstFlow, Name: "MinConstFlow",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "FLW, [AUTO]", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfName, Name: "FLW"}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "AUTO"}}}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrMaxConstFlow, Name: "MaxConstFlow",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "FLW, [AUTO]", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfName, Name: "FLW"}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "AUTO"}}}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrMinConstTemp, Name: "MinConstTemp",
			Type:        spec.Type{Name: "int16", Kind: spec.KindInt, Bits: 16},
			Conformance: spec.Conformance{Text: "TEMP, [AUTO]", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfName, Name: "TEMP"}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "AUTO"}}}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Constraint:  spec.Constraint{Text: "min -27315", Min: &spec.Bound{Int: -27315}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrMaxConstTemp, Name: "MaxConstTemp",
			Type:        spec.Type{Name: "int16", Kind: spec.KindInt, Bits: 16},
			Conformance: spec.Conformance{Text: "TEMP, [AUTO]", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfName, Name: "TEMP"}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "AUTO"}}}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Constraint:  spec.Constraint{Text: "min -27315", Min: &spec.Bound{Int: -27315}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrPumpStatus, Name: "PumpStatus",
			Type:        spec.Type{Name: "PumpStatusBitmap", Kind: spec.KindBitmap, Bits: 16, Bitmap: PumpStatusBitmapDef},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
			Default:     float64(0),
		},
		{
			ID: AttrEffectiveOperationMode, Name: "EffectiveOperationMode",
			Type:        spec.Type{Name: "OperationModeEnum", Kind: spec.KindEnum, Bits: 8, Enum: OperationModeEnumDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
		},
		{
			ID: AttrEffectiveControlMode, Name: "EffectiveControlMode",
			Type:        spec.Type{Name: "ControlModeEnum", Kind: spec.KindEnum, Bits: 8, Enum: ControlModeEnumDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
		},
		{
			ID: AttrCapacity, Name: "Capacity",
			Type:        spec.Type{Name: "int16", Kind: spec.KindInt, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrSpeed, Name: "Speed",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrLifetimeRunningHours, Name: "LifetimeRunningHours",
			Type:        spec.Type{Name: "uint24", Kind: spec.KindUint, Bits: 24},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{Nullable: true, NonVolatile: true},
			Default:     float64(0),
		},
		{
			ID: AttrPower, Name: "Power",
			Type:        spec.Type{Name: "uint24", Kind: spec.KindUint, Bits: 24},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrLifetimeEnergyConsumed, Name: "LifetimeEnergyConsumed",
			Type:        spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{Nullable: true, NonVolatile: true},
			Default:     float64(0),
		},
		{
			ID: AttrOperationMode, Name: "OperationMode",
			Type:        spec.Type{Name: "OperationModeEnum", Kind: spec.KindEnum, Bits: 8, Enum: OperationModeEnumDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
			Default:     float64(0),
		},
		{
			ID: AttrControlMode, Name: "ControlMode",
			Type:        spec.Type{Name: "ControlModeEnum", Kind: spec.KindEnum, Bits: 8, Enum: ControlModeEnumDef},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
			Default:     float64(0),
		},
		{
			ID: AttrAlarmMask, Name: "AlarmMask",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "D", Op: spec.ConfDeprecated},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
		},
	},
	Events: []spec.Event{
		{
			ID: EventSupplyVoltageLow, Name: "SupplyVoltageLow", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeSupplyVoltageLowEvent,
		},
		{
			ID: EventSupplyVoltageHigh, Name: "SupplyVoltageHigh", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeSupplyVoltageHighEvent,
		},
		{
			ID: EventPowerMissingPhase, Name: "PowerMissingPhase", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodePowerMissingPhaseEvent,
		},
		{
			ID: EventSystemPressureLow, Name: "SystemPressureLow", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeSystemPressureLowEvent,
		},
		{
			ID: EventSystemPressureHigh, Name: "SystemPressureHigh", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeSystemPressureHighEvent,
		},
		{
			ID: EventDryRunning, Name: "DryRunning", Priority: spec.PriorityCritical,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeDryRunningEvent,
		},
		{
			ID: EventMotorTemperatureHigh, Name: "MotorTemperatureHigh", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeMotorTemperatureHighEvent,
		},
		{
			ID: EventPumpMotorFatalFailure, Name: "PumpMotorFatalFailure", Priority: spec.PriorityCritical,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodePumpMotorFatalFailureEvent,
		},
		{
			ID: EventElectronicTemperatureHigh, Name: "ElectronicTemperatureHigh", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeElectronicTemperatureHighEvent,
		},
		{
			ID: EventPumpBlocked, Name: "PumpBlocked", Priority: spec.PriorityCritical,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodePumpBlockedEvent,
		},
		{
			ID: EventSensorFailure, Name: "SensorFailure", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeSensorFailureEvent,
		},
		{
			ID: EventElectronicNonFatalFailure, Name: "ElectronicNonFatalFailure", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeElectronicNonFatalFailureEvent,
		},
		{
			ID: EventElectronicFatalFailure, Name: "ElectronicFatalFailure", Priority: spec.PriorityCritical,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeElectronicFatalFailureEvent,
		},
		{
			ID: EventGeneralFault, Name: "GeneralFault", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeGeneralFaultEvent,
		},
		{
			ID: EventLeakage, Name: "Leakage", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeLeakageEvent,
		},
		{
			ID: EventAirDetection, Name: "AirDetection", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeAirDetectionEvent,
		},
		{
			ID: EventTurbineOperation, Name: "TurbineOperation", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeTurbineOperationEvent,
		},
	},
}

func init() { spec.Register(Definition) }
