// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package groups is the generated definition of the Matter Groups cluster
// (0x0004, revision 4), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package groups

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0004
	Name             = "Groups"
	Revision  uint16 = 4
)

// Attribute ids.
const (
	AttrNameSupport uint32 = 0x0000 // NameSupportBitmap, M, R V, F
)

// Command ids.
const (
	CmdAddGroup                   uint32 = 0x00 // request → AddGroupResponse, M
	CmdAddGroupResponse           uint32 = 0x00 // response, M
	CmdViewGroup                  uint32 = 0x01 // request → ViewGroupResponse, M
	CmdViewGroupResponse          uint32 = 0x01 // response, M
	CmdGetGroupMembership         uint32 = 0x02 // request → GetGroupMembershipResponse, M
	CmdGetGroupMembershipResponse uint32 = 0x02 // response, M
	CmdRemoveGroup                uint32 = 0x03 // request → RemoveGroupResponse, M
	CmdRemoveGroupResponse        uint32 = 0x03 // response, M
	CmdRemoveAllGroups            uint32 = 0x04 // request → status, M
	CmdAddGroupIfIdentifying      uint32 = 0x05 // request → status, M
)

// Feature is a Groups FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// FeatureMap bits.
const (
	FeatureGroupNames Feature = 1 << 0 // GN, O
)

// NameSupportBitmap is the NameSupportBitmap map8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type NameSupportBitmap uint8

// NameSupportBitmap bits; a member wider than one bit is its mask.
const (
	NameSupportGroupNames NameSupportBitmap = 1 << 7 // M
)

// NameSupportBitmapDef describes NameSupportBitmap.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var NameSupportBitmapDef = &spec.Bitmap{Name: "NameSupportBitmap", Bits: 8, Members: []spec.BitmapMember{
	{Name: "GroupNames", Bit: 7, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// Status is the status enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Status uint8

// Status values.
const (
	StatusSuccess                   Status = 0
	StatusFailure                   Status = 1
	StatusInvalidSubscription       Status = 125
	StatusUnsupportedAccess         Status = 126
	StatusUnsupportedEndpoint       Status = 127
	StatusInvalidAction             Status = 128
	StatusUnsupportedCommand        Status = 129
	StatusInvalidCommand            Status = 133
	StatusUnsupportedAttribute      Status = 134
	StatusConstraintError           Status = 135
	StatusUnsupportedWrite          Status = 136
	StatusResourceExhausted         Status = 137
	StatusNotFound                  Status = 139
	StatusInvalidDataType           Status = 141
	StatusUnsupportedRead           Status = 143
	StatusDataVersionMismatch       Status = 146
	StatusTimeout                   Status = 148
	StatusUnsupportedNode           Status = 155
	StatusBusy                      Status = 156
	StatusAccessRestricted          Status = 157
	StatusUnsupportedCluster        Status = 195
	StatusNeedsTimedInteraction     Status = 198
	StatusUnsupportedEvent          Status = 199
	StatusPathsExhausted            Status = 200
	StatusTimedRequestMismatch      Status = 201
	StatusFailsafeRequired          Status = 202
	StatusInvalidInState            Status = 203
	StatusNoCommandResponse         Status = 204
	StatusTermsAndConditionsChanged Status = 205
	StatusMaintenanceRequired       Status = 206
	StatusDynamicConstraintError    Status = 207
	StatusAlreadyExists             Status = 208
	StatusInvalidTransportType      Status = 209
)

// StatusDef describes status.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var StatusDef = &spec.Enum{Name: "status", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Success"},
	{Value: 1, Name: "Failure"},
	{Value: 125, Name: "InvalidSubscription"},
	{Value: 126, Name: "UnsupportedAccess"},
	{Value: 127, Name: "UnsupportedEndpoint"},
	{Value: 128, Name: "InvalidAction"},
	{Value: 129, Name: "UnsupportedCommand"},
	{Value: 133, Name: "InvalidCommand"},
	{Value: 134, Name: "UnsupportedAttribute"},
	{Value: 135, Name: "ConstraintError"},
	{Value: 136, Name: "UnsupportedWrite"},
	{Value: 137, Name: "ResourceExhausted"},
	{Value: 139, Name: "NotFound"},
	{Value: 141, Name: "InvalidDataType"},
	{Value: 143, Name: "UnsupportedRead"},
	{Value: 146, Name: "DataVersionMismatch"},
	{Value: 148, Name: "Timeout"},
	{Value: 155, Name: "UnsupportedNode"},
	{Value: 156, Name: "Busy"},
	{Value: 157, Name: "AccessRestricted"},
	{Value: 195, Name: "UnsupportedCluster"},
	{Value: 198, Name: "NeedsTimedInteraction"},
	{Value: 199, Name: "UnsupportedEvent"},
	{Value: 200, Name: "PathsExhausted"},
	{Value: 201, Name: "TimedRequestMismatch"},
	{Value: 202, Name: "FailsafeRequired"},
	{Value: 203, Name: "InvalidInState"},
	{Value: 204, Name: "NoCommandResponse"},
	{Value: 205, Name: "TermsAndConditionsChanged"},
	{Value: 206, Name: "MaintenanceRequired"},
	{Value: 207, Name: "DynamicConstraintError"},
	{Value: 208, Name: "AlreadyExists"},
	{Value: 209, Name: "InvalidTransportType"},
}}

// AddGroupRequest is the AddGroup command payload.
type AddGroupRequest struct {
	GroupId   uint16 // 0: group-id, M, min 1
	GroupName string // 1: string, M, max 16
}

// EncodeTLV implements spec.Encodable.
func (v AddGroupRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.GroupId)
	spec.PutString(enc, tlv.ContextTag(1), v.GroupName)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *AddGroupRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "AddGroup",
		spec.Bind(0, "GroupId", true, &v.GroupId, spec.DecodeUintIn[uint16](16, 1, 65535)),
		spec.Bind(1, "GroupName", true, &v.GroupName, spec.DecodeStringIn(0, 16)),
	)
}

// AddGroupResponse is the AddGroupResponse command payload.
type AddGroupResponse struct {
	Status  Status // 0: status, M, desc
	GroupId uint16 // 1: group-id, M, min 1
}

// EncodeTLV implements spec.Encodable.
func (v AddGroupResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[Status](enc, tlv.ContextTag(0), v.Status)
	spec.PutUint[uint16](enc, tlv.ContextTag(1), v.GroupId)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *AddGroupResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "AddGroupResponse",
		spec.Bind(0, "Status", true, &v.Status, spec.DecodeUint[Status](8)),
		spec.Bind(1, "GroupId", true, &v.GroupId, spec.DecodeUintIn[uint16](16, 1, 65535)),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (AddGroupResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdAddGroupResponse
}

// ViewGroupRequest is the ViewGroup command payload.
type ViewGroupRequest struct {
	GroupId uint16 // 0: group-id, M, min 1
}

// EncodeTLV implements spec.Encodable.
func (v ViewGroupRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.GroupId)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ViewGroupRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ViewGroup",
		spec.Bind(0, "GroupId", true, &v.GroupId, spec.DecodeUintIn[uint16](16, 1, 65535)),
	)
}

// ViewGroupResponse is the ViewGroupResponse command payload.
type ViewGroupResponse struct {
	Status    Status // 0: status, M, desc
	GroupId   uint16 // 1: group-id, M, min 1
	GroupName string // 2: string, M, max 16
}

// EncodeTLV implements spec.Encodable.
func (v ViewGroupResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[Status](enc, tlv.ContextTag(0), v.Status)
	spec.PutUint[uint16](enc, tlv.ContextTag(1), v.GroupId)
	spec.PutString(enc, tlv.ContextTag(2), v.GroupName)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ViewGroupResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ViewGroupResponse",
		spec.Bind(0, "Status", true, &v.Status, spec.DecodeUint[Status](8)),
		spec.Bind(1, "GroupId", true, &v.GroupId, spec.DecodeUintIn[uint16](16, 1, 65535)),
		spec.Bind(2, "GroupName", true, &v.GroupName, spec.DecodeStringIn(0, 16)),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (ViewGroupResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdViewGroupResponse
}

// GetGroupMembershipRequest is the GetGroupMembership command payload.
type GetGroupMembershipRequest struct {
	GroupList []uint16 // 0: list[group-id], M, all[min 1]
}

// EncodeTLV implements spec.Encodable.
func (v GetGroupMembershipRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutList(spec.PutUint[uint16])(enc, tlv.ContextTag(0), v.GroupList)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *GetGroupMembershipRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "GetGroupMembership",
		spec.Bind(0, "GroupList", true, &v.GroupList, spec.DecodeList(spec.DecodeUint[uint16](16))),
	)
}

// GetGroupMembershipResponse is the GetGroupMembershipResponse command payload.
type GetGroupMembershipResponse struct {
	Capacity  spec.Nullable[uint8] // 0: uint8, M, X
	GroupList []uint16             // 1: list[group-id], M, all[min 1]
}

// EncodeTLV implements spec.Encodable.
func (v GetGroupMembershipResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutNullable(spec.PutUint[uint8])(enc, tlv.ContextTag(0), v.Capacity)
	spec.PutList(spec.PutUint[uint16])(enc, tlv.ContextTag(1), v.GroupList)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *GetGroupMembershipResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "GetGroupMembershipResponse",
		spec.Bind(0, "Capacity", true, &v.Capacity, spec.DecodeNullable(spec.DecodeUint[uint8](8))),
		spec.Bind(1, "GroupList", true, &v.GroupList, spec.DecodeList(spec.DecodeUint[uint16](16))),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (GetGroupMembershipResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdGetGroupMembershipResponse
}

// RemoveGroupRequest is the RemoveGroup command payload.
type RemoveGroupRequest struct {
	GroupId uint16 // 0: group-id, M, min 1
}

// EncodeTLV implements spec.Encodable.
func (v RemoveGroupRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.GroupId)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *RemoveGroupRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "RemoveGroup",
		spec.Bind(0, "GroupId", true, &v.GroupId, spec.DecodeUintIn[uint16](16, 1, 65535)),
	)
}

// RemoveGroupResponse is the RemoveGroupResponse command payload.
type RemoveGroupResponse struct {
	Status  Status // 0: status, M, desc
	GroupId uint16 // 1: group-id, M, min 1
}

// EncodeTLV implements spec.Encodable.
func (v RemoveGroupResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[Status](enc, tlv.ContextTag(0), v.Status)
	spec.PutUint[uint16](enc, tlv.ContextTag(1), v.GroupId)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *RemoveGroupResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "RemoveGroupResponse",
		spec.Bind(0, "Status", true, &v.Status, spec.DecodeUint[Status](8)),
		spec.Bind(1, "GroupId", true, &v.GroupId, spec.DecodeUintIn[uint16](16, 1, 65535)),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (RemoveGroupResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdRemoveGroupResponse
}

// RemoveAllGroupsRequest is the RemoveAllGroups command payload.
type RemoveAllGroupsRequest struct{}

// EncodeTLV implements spec.Encodable.
func (v RemoveAllGroupsRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *RemoveAllGroupsRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "RemoveAllGroups")
}

// AddGroupIfIdentifyingRequest is the AddGroupIfIdentifying command payload.
type AddGroupIfIdentifyingRequest struct {
	GroupId   uint16 // 0: group-id, M, min 1
	GroupName string // 1: string, M, max 16
}

// EncodeTLV implements spec.Encodable.
func (v AddGroupIfIdentifyingRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.GroupId)
	spec.PutString(enc, tlv.ContextTag(1), v.GroupName)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *AddGroupIfIdentifyingRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "AddGroupIfIdentifying",
		spec.Bind(0, "GroupId", true, &v.GroupId, spec.DecodeUintIn[uint16](16, 1, 65535)),
		spec.Bind(1, "GroupName", true, &v.GroupName, spec.DecodeStringIn(0, 16)),
	)
}

func decodeAddGroupRequest(n spec.Node) (any, error) { return spec.DecodeStruct[AddGroupRequest](n) }

func decodeAddGroupResponse(n spec.Node) (any, error) { return spec.DecodeStruct[AddGroupResponse](n) }

func decodeViewGroupRequest(n spec.Node) (any, error) { return spec.DecodeStruct[ViewGroupRequest](n) }

func decodeViewGroupResponse(n spec.Node) (any, error) {
	return spec.DecodeStruct[ViewGroupResponse](n)
}

func decodeGetGroupMembershipRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[GetGroupMembershipRequest](n)
}

func decodeGetGroupMembershipResponse(n spec.Node) (any, error) {
	return spec.DecodeStruct[GetGroupMembershipResponse](n)
}

func decodeRemoveGroupRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[RemoveGroupRequest](n)
}

func decodeRemoveGroupResponse(n spec.Node) (any, error) {
	return spec.DecodeStruct[RemoveGroupResponse](n)
}

func decodeRemoveAllGroupsRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[RemoveAllGroupsRequest](n)
}

func decodeAddGroupIfIdentifyingRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[AddGroupIfIdentifyingRequest](n)
}

// Definition is the Groups cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Features: []spec.Feature{
		{Name: "GN", Title: "GroupNames", Bit: 0, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrNameSupport, Name: "NameSupport",
			Type:        spec.Type{Name: "NameSupportBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: NameSupportBitmapDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
		},
	},
	Commands: []spec.Command{
		{
			ID: CmdAddGroup, Name: "AddGroup", Direction: spec.Request,
			Response:    "AddGroupResponse",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage, Fabric: "F"},
			Fields: []spec.Field{
				{ID: 0, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}}},
				{ID: 1, Name: "GroupName", Type: spec.Type{Name: "string", Kind: spec.KindString}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 16", Max: &spec.Bound{Int: 16}}},
			},
			Decode: decodeAddGroupRequest,
		},
		{
			ID: CmdAddGroupResponse, Name: "AddGroupResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "Status", Type: spec.Type{Name: "status", Kind: spec.KindEnum, Bits: 8, Enum: StatusDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}}},
			},
			Decode: decodeAddGroupResponse,
		},
		{
			ID: CmdViewGroup, Name: "ViewGroup", Direction: spec.Request,
			Response:    "ViewGroupResponse",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate, Fabric: "F"},
			Fields: []spec.Field{
				{ID: 0, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}}},
			},
			Decode: decodeViewGroupRequest,
		},
		{
			ID: CmdViewGroupResponse, Name: "ViewGroupResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "Status", Type: spec.Type{Name: "status", Kind: spec.KindEnum, Bits: 8, Enum: StatusDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}}},
				{ID: 2, Name: "GroupName", Type: spec.Type{Name: "string", Kind: spec.KindString}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 16", Max: &spec.Bound{Int: 16}}},
			},
			Decode: decodeViewGroupResponse,
		},
		{
			ID: CmdGetGroupMembership, Name: "GetGroupMembership", Direction: spec.Request,
			Response:    "GetGroupMembershipResponse",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate, Fabric: "F"},
			Fields: []spec.Field{
				{ID: 0, Name: "GroupList", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "all[min 1]", Entry: &spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}}}},
			},
			Decode: decodeGetGroupMembershipRequest,
		},
		{
			ID: CmdGetGroupMembershipResponse, Name: "GetGroupMembershipResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "Capacity", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Quality: spec.Quality{Nullable: true}},
				{ID: 1, Name: "GroupList", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "all[min 1]", Entry: &spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}}}},
			},
			Decode: decodeGetGroupMembershipResponse,
		},
		{
			ID: CmdRemoveGroup, Name: "RemoveGroup", Direction: spec.Request,
			Response:    "RemoveGroupResponse",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage, Fabric: "F"},
			Fields: []spec.Field{
				{ID: 0, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}}},
			},
			Decode: decodeRemoveGroupRequest,
		},
		{
			ID: CmdRemoveGroupResponse, Name: "RemoveGroupResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "Status", Type: spec.Type{Name: "status", Kind: spec.KindEnum, Bits: 8, Enum: StatusDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}}},
			},
			Decode: decodeRemoveGroupResponse,
		},
		{
			ID: CmdRemoveAllGroups, Name: "RemoveAllGroups", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage, Fabric: "F"},
			Decode:      decodeRemoveAllGroupsRequest,
		},
		{
			ID: CmdAddGroupIfIdentifying, Name: "AddGroupIfIdentifying", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage, Fabric: "F"},
			Fields: []spec.Field{
				{ID: 0, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}}},
				{ID: 1, Name: "GroupName", Type: spec.Type{Name: "string", Kind: spec.KindString}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 16", Max: &spec.Bound{Int: 16}}},
			},
			Decode: decodeAddGroupIfIdentifyingRequest,
		},
	},
}

func init() { spec.Register(Definition) }
