// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package airquality is the generated definition of the Matter AirQuality cluster
// (0x005B, revision 1), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package airquality

import "github.com/SukramJ/go-fabric/cluster/spec"

// Cluster identity.
const (
	ClusterID uint32 = 0x005B
	Name             = "AirQuality"
	Revision  uint16 = 1
)

// Attribute ids.
const (
	AttrAirQuality uint32 = 0x0000 // AirQualityEnum, M, R V
)

// Feature is a AirQuality FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// FeatureMap bits.
const (
	FeatureFair          Feature = 1 << 0 // FAIR, O
	FeatureModerate      Feature = 1 << 1 // MOD, O
	FeatureVeryPoor      Feature = 1 << 2 // VPOOR, O
	FeatureExtremelyPoor Feature = 1 << 3 // XPOOR, O
)

// AirQualityEnum is the AirQualityEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type AirQualityEnum uint8

// AirQualityEnum values.
const (
	AirQualityUnknown       AirQualityEnum = 0 // M
	AirQualityGood          AirQualityEnum = 1 // M
	AirQualityFair          AirQualityEnum = 2 // FAIR
	AirQualityModerate      AirQualityEnum = 3 // MOD
	AirQualityPoor          AirQualityEnum = 4 // M
	AirQualityVeryPoor      AirQualityEnum = 5 // VPOOR
	AirQualityExtremelyPoor AirQualityEnum = 6 // XPOOR
)

// AirQualityEnumDef describes AirQualityEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var AirQualityEnumDef = &spec.Enum{Name: "AirQualityEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Unknown", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Good", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "Fair", Conformance: spec.Conformance{Text: "FAIR", Op: spec.ConfName, Name: "FAIR"}},
	{Value: 3, Name: "Moderate", Conformance: spec.Conformance{Text: "MOD", Op: spec.ConfName, Name: "MOD"}},
	{Value: 4, Name: "Poor", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 5, Name: "VeryPoor", Conformance: spec.Conformance{Text: "VPOOR", Op: spec.ConfName, Name: "VPOOR"}},
	{Value: 6, Name: "ExtremelyPoor", Conformance: spec.Conformance{Text: "XPOOR", Op: spec.ConfName, Name: "XPOOR"}},
}}

// Definition is the AirQuality cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Features: []spec.Feature{
		{Name: "FAIR", Title: "Fair", Bit: 0, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
		{Name: "MOD", Title: "Moderate", Bit: 1, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
		{Name: "VPOOR", Title: "VeryPoor", Bit: 2, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
		{Name: "XPOOR", Title: "ExtremelyPoor", Bit: 3, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrAirQuality, Name: "AirQuality",
			Type:        spec.Type{Name: "AirQualityEnum", Kind: spec.KindEnum, Bits: 8, Enum: AirQualityEnumDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
		},
	},
}

func init() { spec.Register(Definition) }
