// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package valveconfigurationandcontrol

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTripCommand(t, Definition, CmdOpen, spec.Request, OpenRequest{OpenDuration: spectest.Ptr(spec.ValueOf(uint32(1))), TargetLevel: spectest.Ptr(uint8(1))})
	spectest.RoundTripCommand(t, Definition, CmdClose, spec.Request, CloseRequest{})
	spectest.RoundTripEvent(t, Definition, EventValveStateChanged, ValveStateChangedEvent{ValveState: ValveStateEnum(0), ValveLevel: spectest.Ptr(uint8(1))})
	spectest.RoundTripEvent(t, Definition, EventValveFault, ValveFaultEvent{ValveFault: ValveFaultBitmap(1 << 0)})
}
