// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package valveconfigurationandcontrol is the generated definition of the Matter ValveConfigurationAndControl cluster
// (0x0081, revision 1), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package valveconfigurationandcontrol

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0081
	Name             = "ValveConfigurationAndControl"
	Revision  uint16 = 1
)

// Attribute ids.
const (
	AttrOpenDuration        uint32 = 0x0000 // elapsed-s, M, R V, X
	AttrDefaultOpenDuration uint32 = 0x0001 // elapsed-s, M, RW VO, X N
	AttrAutoCloseTime       uint32 = 0x0002 // epoch-us, TS, R V, X
	AttrRemainingDuration   uint32 = 0x0003 // elapsed-s, M, R V, X Q
	AttrCurrentState        uint32 = 0x0004 // ValveStateEnum, M, R V, X
	AttrTargetState         uint32 = 0x0005 // ValveStateEnum, M, R V, X
	AttrCurrentLevel        uint32 = 0x0006 // percent, LVL, R V, X
	AttrTargetLevel         uint32 = 0x0007 // percent, LVL, R V, X
	AttrDefaultOpenLevel    uint32 = 0x0008 // percent, [LVL], RW VO, N
	AttrValveFault          uint32 = 0x0009 // ValveFaultBitmap, O, R V
	AttrLevelStep           uint32 = 0x000A // uint8, [LVL], R V, F
)

// Command ids.
const (
	CmdOpen  uint32 = 0x00 // request → status, M
	CmdClose uint32 = 0x01 // request → status, M
)

// Event ids.
const (
	EventValveStateChanged uint32 = 0x00 // info, O
	EventValveFault        uint32 = 0x01 // info, O
)

// Feature is a ValveConfigurationAndControl FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// FeatureMap bits.
const (
	FeatureTimeSync Feature = 1 << 0 // TS, desc
	FeatureLevel    Feature = 1 << 1 // LVL, O
)

// StatusCodeEnum is the StatusCodeEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type StatusCodeEnum uint8

// StatusCodeEnum values.
const (
	StatusCodeFailureDueToFault StatusCodeEnum = 2 // M
)

// StatusCodeEnumDef describes StatusCodeEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var StatusCodeEnumDef = &spec.Enum{Name: "StatusCodeEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 2, Name: "FailureDueToFault", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// ValveFaultBitmap is the ValveFaultBitmap map16.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type ValveFaultBitmap uint16

// ValveFaultBitmap bits; a member wider than one bit is its mask.
const (
	ValveFaultGeneralFault    ValveFaultBitmap = 1 << 0 // M
	ValveFaultBlocked         ValveFaultBitmap = 1 << 1 // M
	ValveFaultLeaking         ValveFaultBitmap = 1 << 2 // M
	ValveFaultNotConnected    ValveFaultBitmap = 1 << 3 // M
	ValveFaultShortCircuit    ValveFaultBitmap = 1 << 4 // M
	ValveFaultCurrentExceeded ValveFaultBitmap = 1 << 5 // M
)

// ValveFaultBitmapDef describes ValveFaultBitmap.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var ValveFaultBitmapDef = &spec.Bitmap{Name: "ValveFaultBitmap", Bits: 16, Members: []spec.BitmapMember{
	{Name: "GeneralFault", Bit: 0, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "Blocked", Bit: 1, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "Leaking", Bit: 2, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "NotConnected", Bit: 3, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "ShortCircuit", Bit: 4, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "CurrentExceeded", Bit: 5, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// ValveStateEnum is the ValveStateEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type ValveStateEnum uint8

// ValveStateEnum values.
const (
	ValveStateClosed        ValveStateEnum = 0 // M
	ValveStateOpen          ValveStateEnum = 1 // M
	ValveStateTransitioning ValveStateEnum = 2 // M
)

// ValveStateEnumDef describes ValveStateEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var ValveStateEnumDef = &spec.Enum{Name: "ValveStateEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Closed", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Open", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "Transitioning", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// OpenRequest is the Open command payload.
type OpenRequest struct {
	OpenDuration *spec.Nullable[uint32] // 0: elapsed-s, O, min 1, X
	TargetLevel  *uint8                 // 1: percent, [LVL], 1 to 100
}

// EncodeTLV implements spec.Encodable.
func (v OpenRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutOptional(enc, tlv.ContextTag(0), v.OpenDuration, spec.PutNullable(spec.PutUint[uint32]))
	spec.PutOptional(enc, tlv.ContextTag(1), v.TargetLevel, spec.PutUint[uint8])
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *OpenRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "Open",
		spec.Bind(0, "OpenDuration", false, &v.OpenDuration, spec.DecodeOptional(spec.DecodeNullable(spec.DecodeUintIn[uint32](32, 1, 4294967295)))),
		spec.Bind(1, "TargetLevel", false, &v.TargetLevel, spec.DecodeOptional(spec.DecodeUintIn[uint8](8, 1, 100))),
	)
}

// CloseRequest is the Close command payload.
type CloseRequest struct{}

// EncodeTLV implements spec.Encodable.
func (v CloseRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *CloseRequest) DecodeTLV(n spec.Node) error { return spec.DecodeFields(n, "Close") }

// ValveStateChangedEvent is the ValveStateChanged event payload.
type ValveStateChangedEvent struct {
	ValveState ValveStateEnum // 0: ValveStateEnum, M
	ValveLevel *uint8         // 1: percent, LVL, max 100
}

// EncodeTLV implements spec.Encodable.
func (v ValveStateChangedEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[ValveStateEnum](enc, tlv.ContextTag(0), v.ValveState)
	spec.PutOptional(enc, tlv.ContextTag(1), v.ValveLevel, spec.PutUint[uint8])
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ValveStateChangedEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ValveStateChanged",
		spec.Bind(0, "ValveState", true, &v.ValveState, spec.DecodeUint[ValveStateEnum](8)),
		spec.Bind(1, "ValveLevel", false, &v.ValveLevel, spec.DecodeOptional(spec.DecodeUintIn[uint8](8, 0, 100))),
	)
}

// ValveFaultEvent is the ValveFault event payload.
type ValveFaultEvent struct {
	ValveFault ValveFaultBitmap // 0: ValveFaultBitmap, M
}

// EncodeTLV implements spec.Encodable.
func (v ValveFaultEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[ValveFaultBitmap](enc, tlv.ContextTag(0), v.ValveFault)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ValveFaultEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ValveFault",
		spec.Bind(0, "ValveFault", true, &v.ValveFault, spec.DecodeUint[ValveFaultBitmap](16)),
	)
}

func decodeOpenRequest(n spec.Node) (any, error) { return spec.DecodeStruct[OpenRequest](n) }

func decodeCloseRequest(n spec.Node) (any, error) { return spec.DecodeStruct[CloseRequest](n) }

func decodeValveStateChangedEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[ValveStateChangedEvent](n)
}

func decodeValveFaultEvent(n spec.Node) (any, error) { return spec.DecodeStruct[ValveFaultEvent](n) }

// Definition is the ValveConfigurationAndControl cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Features: []spec.Feature{
		{Name: "TS", Title: "TimeSync", Bit: 0, Conformance: spec.Conformance{Text: "desc", Op: spec.ConfDesc}},
		{Name: "LVL", Title: "Level", Bit: 1, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrOpenDuration, Name: "OpenDuration",
			Type:        spec.Type{Name: "elapsed-s", Kind: spec.KindUint, Bits: 32},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
			Constraint:  spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}},
		},
		{
			ID: AttrDefaultOpenDuration, Name: "DefaultOpenDuration",
			Type:        spec.Type{Name: "elapsed-s", Kind: spec.KindUint, Bits: 32},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Quality:     spec.Quality{Nullable: true, NonVolatile: true},
			Constraint:  spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}},
		},
		{
			ID: AttrAutoCloseTime, Name: "AutoCloseTime",
			Type:        spec.Type{Name: "epoch-us", Kind: spec.KindUint, Bits: 64},
			Conformance: spec.Conformance{Text: "TS", Op: spec.ConfName, Name: "TS"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
		},
		{
			ID: AttrRemainingDuration, Name: "RemainingDuration",
			Type:        spec.Type{Name: "elapsed-s", Kind: spec.KindUint, Bits: 32},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
		},
		{
			ID: AttrCurrentState, Name: "CurrentState",
			Type:        spec.Type{Name: "ValveStateEnum", Kind: spec.KindEnum, Bits: 8, Enum: ValveStateEnumDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
		},
		{
			ID: AttrTargetState, Name: "TargetState",
			Type:        spec.Type{Name: "ValveStateEnum", Kind: spec.KindEnum, Bits: 8, Enum: ValveStateEnumDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
		},
		{
			ID: AttrCurrentLevel, Name: "CurrentLevel",
			Type:        spec.Type{Name: "percent", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "LVL", Op: spec.ConfName, Name: "LVL"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
			Constraint:  spec.Constraint{Text: "max 100", Max: &spec.Bound{Int: 100}},
		},
		{
			ID: AttrTargetLevel, Name: "TargetLevel",
			Type:        spec.Type{Name: "percent", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "LVL", Op: spec.ConfName, Name: "LVL"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
			Constraint:  spec.Constraint{Text: "max 100", Max: &spec.Bound{Int: 100}},
		},
		{
			ID: AttrDefaultOpenLevel, Name: "DefaultOpenLevel",
			Type:        spec.Type{Name: "percent", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "[LVL]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "LVL"}}},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "1 to 100", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 100}},
			Default:     float64(100),
		},
		{
			ID: AttrValveFault, Name: "ValveFault",
			Type:        spec.Type{Name: "ValveFaultBitmap", Kind: spec.KindBitmap, Bits: 16, Bitmap: ValveFaultBitmapDef},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Default:     float64(0),
		},
		{
			ID: AttrLevelStep, Name: "LevelStep",
			Type:        spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "[LVL]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "LVL"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "1 to 50", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 50}},
			Default:     float64(1),
		},
	},
	Commands: []spec.Command{
		{
			ID: CmdOpen, Name: "Open", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "OpenDuration", Type: spec.Type{Name: "elapsed-s", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}, Quality: spec.Quality{Nullable: true}, Constraint: spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}}},
				{ID: 1, Name: "TargetLevel", Type: spec.Type{Name: "percent", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "[LVL]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "LVL"}}}, Constraint: spec.Constraint{Text: "1 to 100", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 100}}},
			},
			Decode: decodeOpenRequest,
		},
		{
			ID: CmdClose, Name: "Close", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate},
			Decode:      decodeCloseRequest,
		},
	},
	Events: []spec.Event{
		{
			ID: EventValveStateChanged, Name: "ValveStateChanged", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "ValveState", Type: spec.Type{Name: "ValveStateEnum", Kind: spec.KindEnum, Bits: 8, Enum: ValveStateEnumDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 1, Name: "ValveLevel", Type: spec.Type{Name: "percent", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "LVL", Op: spec.ConfName, Name: "LVL"}, Constraint: spec.Constraint{Text: "max 100", Max: &spec.Bound{Int: 100}}},
			},
			Decode: decodeValveStateChangedEvent,
		},
		{
			ID: EventValveFault, Name: "ValveFault", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "ValveFault", Type: spec.Type{Name: "ValveFaultBitmap", Kind: spec.KindBitmap, Bits: 16, Bitmap: ValveFaultBitmapDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeValveFaultEvent,
		},
	},
}

func init() { spec.Register(Definition) }
