// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package identify is the generated definition of the Matter Identify cluster
// (0x0003, revision 6), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package identify

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0003
	Name             = "Identify"
	Revision  uint16 = 6
)

// Attribute ids.
const (
	AttrIdentifyTime uint32 = 0x0000 // uint16, M, RW VO, Q
	AttrIdentifyType uint32 = 0x0001 // IdentifyTypeEnum, M, R V
)

// Command ids.
const (
	CmdIdentify      uint32 = 0x00 // request → status, M
	CmdTriggerEffect uint32 = 0x40 // request → status, O
)

// Feature is a Identify FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// EffectIdentifierEnum is the EffectIdentifierEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type EffectIdentifierEnum uint8

// EffectIdentifierEnum values.
const (
	EffectIdentifierBlink         EffectIdentifierEnum = 0   // M
	EffectIdentifierBreathe       EffectIdentifierEnum = 1   // M
	EffectIdentifierOkay          EffectIdentifierEnum = 2   // M
	EffectIdentifierChannelChange EffectIdentifierEnum = 11  // M
	EffectIdentifierFinishEffect  EffectIdentifierEnum = 254 // M
	EffectIdentifierStopEffect    EffectIdentifierEnum = 255 // M
)

// EffectIdentifierEnumDef describes EffectIdentifierEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var EffectIdentifierEnumDef = &spec.Enum{Name: "EffectIdentifierEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Blink", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Breathe", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "Okay", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 11, Name: "ChannelChange", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 254, Name: "FinishEffect", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 255, Name: "StopEffect", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// EffectVariantEnum is the EffectVariantEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type EffectVariantEnum uint8

// EffectVariantEnum values.
const (
	EffectVariantDefault EffectVariantEnum = 0 // M
)

// EffectVariantEnumDef describes EffectVariantEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var EffectVariantEnumDef = &spec.Enum{Name: "EffectVariantEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Default", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// IdentifyTypeEnum is the IdentifyTypeEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type IdentifyTypeEnum uint8

// IdentifyTypeEnum values.
const (
	IdentifyTypeNone             IdentifyTypeEnum = 0 // M
	IdentifyTypeLightOutput      IdentifyTypeEnum = 1 // M
	IdentifyTypeVisibleIndicator IdentifyTypeEnum = 2 // M
	IdentifyTypeAudibleBeep      IdentifyTypeEnum = 3 // M
	IdentifyTypeDisplay          IdentifyTypeEnum = 4 // M
	IdentifyTypeActuator         IdentifyTypeEnum = 5 // M
)

// IdentifyTypeEnumDef describes IdentifyTypeEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var IdentifyTypeEnumDef = &spec.Enum{Name: "IdentifyTypeEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "None", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "LightOutput", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "VisibleIndicator", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 3, Name: "AudibleBeep", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 4, Name: "Display", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 5, Name: "Actuator", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// IdentifyRequest is the Identify command payload.
type IdentifyRequest struct {
	IdentifyTime uint16 // 0: uint16, M
}

// EncodeTLV implements spec.Encodable.
func (v IdentifyRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.IdentifyTime)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *IdentifyRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "Identify",
		spec.Bind(0, "IdentifyTime", true, &v.IdentifyTime, spec.DecodeUint[uint16](16)),
	)
}

// TriggerEffectRequest is the TriggerEffect command payload.
type TriggerEffectRequest struct {
	EffectIdentifier EffectIdentifierEnum // 0: EffectIdentifierEnum, M, desc
	EffectVariant    EffectVariantEnum    // 1: EffectVariantEnum, M, desc
}

// EncodeTLV implements spec.Encodable.
func (v TriggerEffectRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[EffectIdentifierEnum](enc, tlv.ContextTag(0), v.EffectIdentifier)
	spec.PutUint[EffectVariantEnum](enc, tlv.ContextTag(1), v.EffectVariant)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *TriggerEffectRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "TriggerEffect",
		spec.Bind(0, "EffectIdentifier", true, &v.EffectIdentifier, spec.DecodeUint[EffectIdentifierEnum](8)),
		spec.Bind(1, "EffectVariant", true, &v.EffectVariant, spec.DecodeUint[EffectVariantEnum](8)),
	)
}

func decodeIdentifyRequest(n spec.Node) (any, error) { return spec.DecodeStruct[IdentifyRequest](n) }

func decodeTriggerEffectRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[TriggerEffectRequest](n)
}

// Definition is the Identify cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Attributes: []spec.Attribute{
		{
			ID: AttrIdentifyTime, Name: "IdentifyTime",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Quality:     spec.Quality{Quieter: true},
		},
		{
			ID: AttrIdentifyType, Name: "IdentifyType",
			Type:        spec.Type{Name: "IdentifyTypeEnum", Kind: spec.KindEnum, Bits: 8, Enum: IdentifyTypeEnumDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
		},
	},
	Commands: []spec.Command{
		{
			ID: CmdIdentify, Name: "Identify", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage},
			Fields: []spec.Field{
				{ID: 0, Name: "IdentifyTime", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeIdentifyRequest,
		},
		{
			ID: CmdTriggerEffect, Name: "TriggerEffect", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage},
			Fields: []spec.Field{
				{ID: 0, Name: "EffectIdentifier", Type: spec.Type{Name: "EffectIdentifierEnum", Kind: spec.KindEnum, Bits: 8, Enum: EffectIdentifierEnumDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "EffectVariant", Type: spec.Type{Name: "EffectVariantEnum", Kind: spec.KindEnum, Bits: 8, Enum: EffectVariantEnumDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
			},
			Decode: decodeTriggerEffectRequest,
		},
	},
}

func init() { spec.Register(Definition) }
