// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package levelcontrol

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTripCommand(t, Definition, CmdMoveToLevel, spec.Request, MoveToLevelRequest{Level: uint8(1), TransitionTime: spec.ValueOf(uint16(1)), OptionsMask: OptionsBitmap(1 << 0), OptionsOverride: OptionsBitmap(1 << 0)})
	spectest.RoundTripCommand(t, Definition, CmdMove, spec.Request, MoveRequest{MoveMode: MoveModeEnum(0), Rate: spec.ValueOf(uint8(1)), OptionsMask: OptionsBitmap(1 << 0), OptionsOverride: OptionsBitmap(1 << 0)})
	spectest.RoundTripCommand(t, Definition, CmdStep, spec.Request, StepRequest{StepMode: StepModeEnum(0), StepSize: uint8(1), TransitionTime: spec.ValueOf(uint16(1)), OptionsMask: OptionsBitmap(1 << 0), OptionsOverride: OptionsBitmap(1 << 0)})
	spectest.RoundTripCommand(t, Definition, CmdStop, spec.Request, StopRequest{OptionsMask: OptionsBitmap(1 << 0), OptionsOverride: OptionsBitmap(1 << 0)})
	spectest.RoundTripCommand(t, Definition, CmdMoveToLevelWithOnOff, spec.Request, MoveToLevelWithOnOffRequest{Level: uint8(1), TransitionTime: spec.ValueOf(uint16(1)), OptionsMask: OptionsBitmap(1 << 0), OptionsOverride: OptionsBitmap(1 << 0)})
	spectest.RoundTripCommand(t, Definition, CmdMoveWithOnOff, spec.Request, MoveWithOnOffRequest{MoveMode: MoveModeEnum(0), Rate: spec.ValueOf(uint8(1)), OptionsMask: OptionsBitmap(1 << 0), OptionsOverride: OptionsBitmap(1 << 0)})
	spectest.RoundTripCommand(t, Definition, CmdStepWithOnOff, spec.Request, StepWithOnOffRequest{StepMode: StepModeEnum(0), StepSize: uint8(1), TransitionTime: spec.ValueOf(uint16(1)), OptionsMask: OptionsBitmap(1 << 0), OptionsOverride: OptionsBitmap(1 << 0)})
	spectest.RoundTripCommand(t, Definition, CmdStopWithOnOff, spec.Request, StopWithOnOffRequest{OptionsMask: OptionsBitmap(1 << 0), OptionsOverride: OptionsBitmap(1 << 0)})
	spectest.RoundTripCommand(t, Definition, CmdMoveToClosestFrequency, spec.Request, MoveToClosestFrequencyRequest{Frequency: uint16(1)})
}
