// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package binding

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, TargetStruct{Node: spectest.Ptr(uint64(1)), Group: spectest.Ptr(uint16(1)), Endpoint: spectest.Ptr(uint16(1)), Cluster: spectest.Ptr(uint32(1)), FabricIndex: uint8(1)}, spec.DecodeStruct[TargetStruct])
	spectest.RoundTripAttribute(t, Definition, AttrBinding, spec.List[TargetStruct]([]TargetStruct{TargetStruct{Node: spectest.Ptr(uint64(1)), Group: spectest.Ptr(uint16(1)), Endpoint: spectest.Ptr(uint16(1)), Cluster: spectest.Ptr(uint32(1)), FabricIndex: uint8(1)}}))
}
