// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package icdmanagement

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, MonitoringRegistrationStruct{CheckInNodeId: uint64(1), MonitoredSubject: uint64(1), Key: spectest.Ptr([]byte{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}), ClientType: ClientTypeEnum(0), FabricIndex: uint8(1)}, spec.DecodeStruct[MonitoringRegistrationStruct])
	spectest.RoundTripCommand(t, Definition, CmdRegisterClient, spec.Request, RegisterClientRequest{CheckInNodeId: uint64(1), MonitoredSubject: uint64(1), Key: []byte{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}, VerificationKey: spectest.Ptr([]byte{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}), ClientType: ClientTypeEnum(0)})
	spectest.RoundTripCommand(t, Definition, CmdRegisterClientResponse, spec.Response, RegisterClientResponse{IcdCounter: uint32(1)})
	spectest.RoundTripCommand(t, Definition, CmdUnregisterClient, spec.Request, UnregisterClientRequest{CheckInNodeId: uint64(1), VerificationKey: spectest.Ptr([]byte{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1})})
	spectest.RoundTripCommand(t, Definition, CmdStayActiveRequest, spec.Request, StayActiveRequestRequest{StayActiveDuration: uint32(1)})
	spectest.RoundTripCommand(t, Definition, CmdStayActiveResponse, spec.Response, StayActiveResponse{PromisedActiveDuration: uint32(1)})
	spectest.RoundTripAttribute(t, Definition, AttrRegisteredClients, spec.List[MonitoringRegistrationStruct]([]MonitoringRegistrationStruct{MonitoringRegistrationStruct{CheckInNodeId: uint64(1), MonitoredSubject: uint64(1), Key: spectest.Ptr([]byte{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}), ClientType: ClientTypeEnum(0), FabricIndex: uint8(1)}}))
}
