// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

package bridge

import (
	"context"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"errors"
	"testing"

	"github.com/SukramJ/go-fabric/cluster/light"
	"github.com/SukramJ/go-fabric/cluster/spec"
	ccdef "github.com/SukramJ/go-fabric/cluster/spec/colorcontrol"
	"github.com/SukramJ/go-fabric/cluster/wire"
	"github.com/SukramJ/go-fabric/im"
	"github.com/SukramJ/go-fabric/tlv"
)

// colorcontrol-wire-fixtures.json holds matter.js's own encodings of every
// ColorControl request and of the colour attributes cluster/light reads
// (TlvOfModel(element)), generated by
// notes/parity/matter/generate-colorcontrol-fixtures.ts.
//
//go:embed testdata/colorcontrol-wire-fixtures.json
var colorControlWireFixturesJSON []byte

type colorControlFixture struct {
	Label    string          `json:"label"`
	Kind     string          `json:"kind"`
	Element  string          `json:"element"`
	ID       uint32          `json:"id"`
	Fixture  json.RawMessage `json:"fixture"`
	BytesHex string          `json:"bytesHex"`
}

// canonicalColorRequest turns what commandFieldsReader hands the server
// into the generated request type: the four commands with hand-written
// decoders arrive as cluster/wire structs, the rest as generated structs.
func canonicalColorRequest(t *testing.T, got any) spec.Encodable {
	t.Helper()
	switch v := got.(type) {
	case wire.MoveToHueRequest:
		return ccdef.MoveToHueRequest{
			Hue: v.Hue, Direction: ccdef.DirectionEnum(v.Direction), TransitionTime: v.TransitionTime,
			OptionsMask: ccdef.OptionsBitmap(v.OptionsMask), OptionsOverride: ccdef.OptionsBitmap(v.OptionsOverride),
		}
	case wire.MoveToSaturationRequest:
		return ccdef.MoveToSaturationRequest{
			Saturation: v.Saturation, TransitionTime: v.TransitionTime,
			OptionsMask: ccdef.OptionsBitmap(v.OptionsMask), OptionsOverride: ccdef.OptionsBitmap(v.OptionsOverride),
		}
	case wire.MoveToHueAndSaturationRequest:
		return ccdef.MoveToHueAndSaturationRequest{
			Hue: v.Hue, Saturation: v.Saturation, TransitionTime: v.TransitionTime,
			OptionsMask: ccdef.OptionsBitmap(v.OptionsMask), OptionsOverride: ccdef.OptionsBitmap(v.OptionsOverride),
		}
	case wire.MoveToColorTemperatureRequest:
		return ccdef.MoveToColorTemperatureRequest{
			ColorTemperatureMireds: v.ColorTemperatureMireds, TransitionTime: v.TransitionTime,
			OptionsMask: ccdef.OptionsBitmap(v.OptionsMask), OptionsOverride: ccdef.OptionsBitmap(v.OptionsOverride),
		}
	case spec.Encodable:
		return v
	}
	t.Fatalf("commandFieldsReader handed %T", got)
	return nil
}

// TestColorControlPayloadsMatchMatterJS runs every ColorControl request of
// matter.js through the bridge's decode path and into a ColorControl
// server with every feature: the decoded fields re-encode to matter.js's
// bytes (nothing dropped — the Options fields of the hue and saturation
// commands included), and the server accepts them. The colour attributes
// the server reads encode through the value writer into matter.js's bytes.
func TestColorControlPayloadsMatchMatterJS(t *testing.T) {
	t.Parallel()
	var fixtures []colorControlFixture
	if err := json.Unmarshal(colorControlWireFixturesJSON, &fixtures); err != nil || len(fixtures) == 0 {
		t.Fatalf("colorcontrol-wire-fixtures.json: %v (%d entries)", err, len(fixtures))
	}
	commands := 0
	for _, f := range fixtures {
		t.Run(f.Label, func(t *testing.T) {
			t.Parallel()
			srv := newFullColorServer(t)
			switch f.Kind {
			case "commands":
				got := decodeCommandFields(t, ccdef.ClusterID, f.ID, f.BytesHex)
				enc := tlv.NewEncoder()
				canonicalColorRequest(t, got).EncodeTLV(enc, tlv.AnonymousTag())
				b, err := enc.Bytes()
				if err != nil {
					t.Fatal(err)
				}
				if hex.EncodeToString(b) != f.BytesHex {
					t.Fatalf("%s: decoded %+v re-encodes to %x, matter.js %s", f.Element, got, b, f.BytesHex)
				}
				if _, err := srv.MatterInvoke(context.Background(), f.ID, got); err != nil {
					t.Fatalf("%s: MatterInvoke(%+v): %v", f.Element, got, err)
				}
			case "attributes":
				id := map[string]uint32{
					"CurrentX": ccdef.AttrCurrentX, "CurrentHue": ccdef.AttrCurrentHue,
					"EnhancedCurrentHue": ccdef.AttrEnhancedCurrentHue, "EnhancedColorMode": ccdef.AttrEnhancedColorMode,
					"ColorLoopActive": ccdef.AttrColorLoopActive, "ColorCapabilities": ccdef.AttrColorCapabilities,
				}[f.Element]
				if f.Element == "ColorLoopActive" {
					if _, err := srv.MatterInvoke(context.Background(), ccdef.CmdColorLoopSet, ccdef.ColorLoopSetRequest{
						UpdateFlags: ccdef.UpdateFlagsUpdateAction, Action: ccdef.ColorLoopActionActivateFromEnhancedCurrentHue,
						Direction: ccdef.ColorLoopDirectionIncrement,
					}); err != nil {
						t.Fatal(err)
					}
				}
				v, ok := srv.MatterRead(id)
				if !ok {
					t.Fatalf("%s not served", f.Element)
				}
				// The value writer encodes an attribute at its Go type's width
				// (tlv.Encoder.PutUint16); matter.js at the smallest width
				// that holds the value. Both are the same unsigned integer.
				if got, want := decodeUintHex(t, encodeValue(t, v)), decodeUintHex(t, f.BytesHex); got != want {
					t.Fatalf("%s: encoded %d, matter.js %d", f.Element, got, want)
				}
			default:
				t.Fatalf("unhandled fixture kind %s", f.Kind)
			}
		})
		if f.Kind == "commands" {
			commands++
		}
	}
	if want := 19; commands != want {
		t.Errorf("%d command fixtures, want one per ColorControl request (%d)", commands, want)
	}
}

func decodeUintHex(t *testing.T, s string) uint64 {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	el, err := tlv.NewDecoder(b).Next()
	if err != nil || el.Type < tlv.TypeUnsignedInt1 || el.Type > tlv.TypeUnsignedInt8 {
		t.Fatalf("%s is no unsigned integer: %v", s, err)
	}
	return el.Uint
}

func newFullColorServer(t *testing.T) *light.ColorControlServer {
	t.Helper()
	mode := light.ColorModeEnhancedHueSaturation
	srv, err := light.NewColorControl(light.ColorControlServerConfig{
		Features: light.ColorFeatureHueSaturation | light.ColorFeatureEnhancedHue | light.ColorFeatureColorLoop |
			light.ColorFeatureXY | light.ColorFeatureColorTemperature,
		MinMireds: 153, MaxMireds: 500, InitialMireds: 250, InitialColorMode: &mode,
		InitialHue: 254, InitialEnhancedHue: 65535,
	})
	if err != nil {
		t.Fatal(err)
	}
	return srv
}

// TestColorControlRequestsRefusedAsMatterJS: a request the generated
// schema rejects is answered with matter.js's status before the server
// runs — a value outside its type or constraint CONSTRAINT_ERROR, a
// missing mandatory field INVALID_COMMAND (CommandInvokeResponse.ts maps
// ValidationMandatoryFieldMissingError's InvalidAction to it).
func TestColorControlRequestsRefusedAsMatterJS(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name   string
		cmd    uint32
		fields func(enc *tlv.Encoder)
		want   im.StatusCode
	}{
		{"MoveToColor.ColorX above 65279", ccdef.CmdMoveToColor, func(enc *tlv.Encoder) {
			enc.PutUint(tlv.ContextTag(0), 65280)
		}, im.StatusConstraintError},
		{"MoveColor.RateX wider than int16", ccdef.CmdMoveColor, func(enc *tlv.Encoder) {
			enc.PutInt(tlv.ContextTag(0), 40000)
		}, im.StatusConstraintError},
		{"StepHue.TransitionTime wider than uint8", ccdef.CmdStepHue, func(enc *tlv.Encoder) {
			enc.PutUint(tlv.ContextTag(2), 256)
		}, im.StatusConstraintError},
		{"EnhancedMoveToHueAndSaturation.Saturation above 254", ccdef.CmdEnhancedMoveToHueAndSaturation, func(enc *tlv.Encoder) {
			enc.PutUint(tlv.ContextTag(1), 255)
		}, im.StatusConstraintError},
		{"ColorLoopSet without fields", ccdef.CmdColorLoopSet, func(*tlv.Encoder) {}, im.StatusInvalidCommand},
		{"StopMoveStep without OptionsOverride", ccdef.CmdStopMoveStep, func(enc *tlv.Encoder) {
			enc.PutUint(tlv.ContextTag(0), 0)
		}, im.StatusInvalidCommand},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			enc := tlv.NewEncoder()
			enc.StartStruct(tlv.AnonymousTag())
			tc.fields(enc)
			_ = enc.EndContainer()
			b, err := enc.Bytes()
			if err != nil {
				t.Fatal(err)
			}
			dec := tlv.NewDecoder(b)
			open, err := dec.Next()
			if err != nil {
				t.Fatal(err)
			}
			_, err = commandFieldsReader(im.ConcreteCommandPath{Cluster: ccdef.ClusterID, Command: tc.cmd}, dec, open)
			var sce im.StatusCodeError
			if err == nil || !errors.As(err, &sce) || sce.MatterStatusCode() != tc.want {
				t.Fatalf("err = %v, want status %v", err, tc.want)
			}
		})
	}
}
