// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

package bridge

import (
	_ "embed"
	"encoding/json"
	"testing"

	"github.com/SukramJ/go-fabric/cluster/filter"
	carbon "github.com/SukramJ/go-fabric/cluster/spec/activatedcarbonfiltermonitoring"
	hepa "github.com/SukramJ/go-fabric/cluster/spec/hepafiltermonitoring"
)

// filter-wire-fixtures.json holds matter.js's own encodings of the
// ResourceMonitoring payloads cluster/filter sends and receives
// (TlvOfModel(element)), generated by
// notes/parity/matter/generate-filter-fixtures.ts.
//
//go:embed testdata/filter-wire-fixtures.json
var filterWireFixturesJSON []byte

// TestFilterPayloadsMatchMatterJS runs the generated-definition wire path
// end to end against matter.js: a ResetCondition request decodes through
// commandFieldsReader into the generated request type of its cluster (the
// spec registry), and the ReplacementProductList a server reads encodes
// through the value writer into matter.js's bytes.
func TestFilterPayloadsMatchMatterJS(t *testing.T) {
	t.Parallel()
	var fixtures []struct {
		Label    string          `json:"label"`
		Kind     string          `json:"kind"`
		Cluster  uint32          `json:"cluster"`
		Fixture  json.RawMessage `json:"fixture"`
		BytesHex string          `json:"bytesHex"`
	}
	if err := json.Unmarshal(filterWireFixturesJSON, &fixtures); err != nil || len(fixtures) == 0 {
		t.Fatalf("filter-wire-fixtures.json: %v (%d entries)", err, len(fixtures))
	}
	for _, f := range fixtures {
		t.Run(f.Label, func(t *testing.T) {
			t.Parallel()
			switch f.Kind {
			case "commands":
				got := decodeCommandFields(t, f.Cluster, hepa.CmdResetCondition, f.BytesHex)
				var ok bool
				switch f.Cluster {
				case hepa.ClusterID:
					_, ok = got.(hepa.ResetConditionRequest)
				case carbon.ClusterID:
					_, ok = got.(carbon.ResetConditionRequest)
				}
				if !ok {
					t.Fatalf("decoded %T", got)
				}
			case "attributes":
				var products []struct {
					Type  uint8  `json:"productIdentifierType"`
					Value string `json:"productIdentifierValue"`
				}
				if err := json.Unmarshal(f.Fixture, &products); err != nil {
					t.Fatal(err)
				}
				cfg := filter.Config{Features: filter.FeatureReplacementProductList}
				for _, p := range products {
					cfg.ReplacementProducts = append(cfg.ReplacementProducts, filter.ReplacementProduct{
						ProductIdentifierType: hepa.ProductIdentifierTypeEnum(p.Type), ProductIdentifierValue: p.Value,
					})
				}
				newServer := filter.NewHepaFilterMonitoring
				if f.Cluster == carbon.ClusterID {
					newServer = filter.NewActivatedCarbonFilterMonitoring
				}
				srv, err := newServer(cfg)
				if err != nil {
					t.Fatal(err)
				}
				v, _ := srv.MatterRead(hepa.AttrReplacementProductList)
				if got := encodeValue(t, v); got != f.BytesHex {
					t.Fatalf("encoded %s, matter.js %s", got, f.BytesHex)
				}
			default:
				t.Fatalf("unhandled fixture kind %s", f.Kind)
			}
		})
	}
}
