// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/generate_matter_schema.go from
// parity/schema.json — DO NOT EDIT.
// Run `go generate ./schema/...` to regenerate.

package schema

// SchemaSnapshotSHA256 is the SHA-256 hex digest of
// parity/schema.json at generation time.
// The TestMatterSchemaSnapshotHashMatchesEmbedded test recomputes the
// hash at test time and fails when they diverge — catching hand-edits
// to generated constants that did not go through the generator.
const SchemaSnapshotSHA256 = "db3eea6bc4f8d11734a2eb318d4146aec188e900061196cd72b00f8bd1743866"
