// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/generate_matter_schema.go from
// parity/schema.json — DO NOT EDIT.
// Run `go generate ./schema/...` to regenerate.

package schema

// SchemaSnapshotSHA256 is the SHA-256 hex digest of
// parity/schema.json at generation time.
// The TestMatterSchemaSnapshotHashMatchesEmbedded test recomputes the
// hash at test time and fails when they diverge — catching hand-edits
// to generated constants that did not go through the generator.
const SchemaSnapshotSHA256 = "09d67269d2bed61dd89394100adc871c1790514c1b2315f94fa4317cfd1c5850"
