// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/generate_matter_schema.go from
// parity/schema.json — DO NOT EDIT.
// Run `go generate ./schema/...` to regenerate.

package schema

// SchemaSnapshotSHA256 is the SHA-256 hex digest of
// parity/schema.json at generation time.
// The TestMatterSchemaSnapshotHashMatchesEmbedded test recomputes the
// hash at test time and fails when they diverge — catching hand-edits
// to generated constants that did not go through the generator.
const SchemaSnapshotSHA256 = "cc4310bdcdaebf56d97c571aa9936d4155296988ef88ec11d9cbf741a16f5828"
