// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package generaldiagnostics is the generated definition of the Matter GeneralDiagnostics cluster
// (0x0033, revision 3), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package generaldiagnostics

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0033
	Name             = "GeneralDiagnostics"
	Revision  uint16 = 3
)

// Attribute ids.
const (
	AttrNetworkInterfaces        uint32 = 0x0000 // list[NetworkInterface], M, R V
	AttrRebootCount              uint32 = 0x0001 // uint16, M, R V, N
	AttrUpTime                   uint32 = 0x0002 // uint64, M, R V, C
	AttrTotalOperationalHours    uint32 = 0x0003 // uint32, O, R V, N C
	AttrBootReason               uint32 = 0x0004 // BootReasonEnum, O, R V
	AttrActiveHardwareFaults     uint32 = 0x0005 // list[HardwareFaultEnum], O, R V
	AttrActiveRadioFaults        uint32 = 0x0006 // list[RadioFaultEnum], O, R V
	AttrActiveNetworkFaults      uint32 = 0x0007 // list[NetworkFaultEnum], O, R V
	AttrTestEventTriggersEnabled uint32 = 0x0008 // bool, M, R V
	AttrDoNotUse                 uint32 = 0x0009 // untyped, X, RW VO
	AttrDeviceLoadStatus         uint32 = 0x000A // DeviceLoadStruct, Rev >= v3, R V, C
)

// Command ids.
const (
	CmdTestEventTrigger     uint32 = 0x00 // request → status, M
	CmdTimeSnapshot         uint32 = 0x01 // request → TimeSnapshotResponse, M
	CmdTimeSnapshotResponse uint32 = 0x02 // response, M
	CmdPayloadTestRequest   uint32 = 0x03 // request → PayloadTestResponse, DMTEST
	CmdPayloadTestResponse  uint32 = 0x04 // response, DMTEST
)

// Event ids.
const (
	EventHardwareFaultChange uint32 = 0x00 // critical, O
	EventRadioFaultChange    uint32 = 0x01 // critical, O
	EventNetworkFaultChange  uint32 = 0x02 // critical, O
	EventBootReason          uint32 = 0x03 // critical, M
)

// Feature is a GeneralDiagnostics FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// FeatureMap bits.
const (
	FeatureDataModelTest Feature = 1 << 0 // DMTEST, desc
)

// BootReasonEnum is the BootReasonEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type BootReasonEnum uint8

// BootReasonEnum values.
const (
	BootReasonUnspecified             BootReasonEnum = 0 // M
	BootReasonPowerOnReboot           BootReasonEnum = 1 // M
	BootReasonBrownOutReset           BootReasonEnum = 2 // M
	BootReasonSoftwareWatchdogReset   BootReasonEnum = 3 // M
	BootReasonHardwareWatchdogReset   BootReasonEnum = 4 // M
	BootReasonSoftwareUpdateCompleted BootReasonEnum = 5 // M
	BootReasonSoftwareReset           BootReasonEnum = 6 // M
)

// BootReasonEnumDef describes BootReasonEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var BootReasonEnumDef = &spec.Enum{Name: "BootReasonEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Unspecified", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "PowerOnReboot", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "BrownOutReset", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 3, Name: "SoftwareWatchdogReset", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 4, Name: "HardwareWatchdogReset", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 5, Name: "SoftwareUpdateCompleted", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 6, Name: "SoftwareReset", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// DeviceLoadStruct is the DeviceLoadStruct struct.
type DeviceLoadStruct struct {
	CurrentSubscriptions                  uint16 // 0: uint16, M
	CurrentSubscriptionsForFabric         uint16 // 1: uint16, M
	TotalSubscriptionsEstablished         uint32 // 2: uint32, M
	TotalInteractionModelMessagesSent     uint32 // 3: uint32, M
	TotalInteractionModelMessagesReceived uint32 // 4: uint32, M
}

// EncodeTLV implements spec.Encodable.
func (v DeviceLoadStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.CurrentSubscriptions)
	spec.PutUint[uint16](enc, tlv.ContextTag(1), v.CurrentSubscriptionsForFabric)
	spec.PutUint[uint32](enc, tlv.ContextTag(2), v.TotalSubscriptionsEstablished)
	spec.PutUint[uint32](enc, tlv.ContextTag(3), v.TotalInteractionModelMessagesSent)
	spec.PutUint[uint32](enc, tlv.ContextTag(4), v.TotalInteractionModelMessagesReceived)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *DeviceLoadStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "DeviceLoadStruct",
		spec.Bind(0, "CurrentSubscriptions", true, &v.CurrentSubscriptions, spec.DecodeUint[uint16](16)),
		spec.Bind(1, "CurrentSubscriptionsForFabric", true, &v.CurrentSubscriptionsForFabric, spec.DecodeUint[uint16](16)),
		spec.Bind(2, "TotalSubscriptionsEstablished", true, &v.TotalSubscriptionsEstablished, spec.DecodeUint[uint32](32)),
		spec.Bind(3, "TotalInteractionModelMessagesSent", true, &v.TotalInteractionModelMessagesSent, spec.DecodeUint[uint32](32)),
		spec.Bind(4, "TotalInteractionModelMessagesReceived", true, &v.TotalInteractionModelMessagesReceived, spec.DecodeUint[uint32](32)),
	)
}

// DeviceLoadStructDef describes DeviceLoadStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var DeviceLoadStructDef = &spec.Struct{Name: "DeviceLoadStruct", Fields: []spec.Field{
	{ID: 0, Name: "CurrentSubscriptions", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{ID: 1, Name: "CurrentSubscriptionsForFabric", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{ID: 2, Name: "TotalSubscriptionsEstablished", Type: spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{ID: 3, Name: "TotalInteractionModelMessagesSent", Type: spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{ID: 4, Name: "TotalInteractionModelMessagesReceived", Type: spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// HardwareFaultEnum is the HardwareFaultEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type HardwareFaultEnum uint8

// HardwareFaultEnum values.
const (
	HardwareFaultUnspecified            HardwareFaultEnum = 0  // M
	HardwareFaultRadio                  HardwareFaultEnum = 1  // O
	HardwareFaultSensor                 HardwareFaultEnum = 2  // O
	HardwareFaultResettableOverTemp     HardwareFaultEnum = 3  // O
	HardwareFaultNonResettableOverTemp  HardwareFaultEnum = 4  // O
	HardwareFaultPowerSource            HardwareFaultEnum = 5  // O
	HardwareFaultVisualDisplayFault     HardwareFaultEnum = 6  // O
	HardwareFaultAudioOutputFault       HardwareFaultEnum = 7  // O
	HardwareFaultUserInterfaceFault     HardwareFaultEnum = 8  // O
	HardwareFaultNonVolatileMemoryError HardwareFaultEnum = 9  // O
	HardwareFaultTamperDetected         HardwareFaultEnum = 10 // O
)

// HardwareFaultEnumDef describes HardwareFaultEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var HardwareFaultEnumDef = &spec.Enum{Name: "HardwareFaultEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Unspecified", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Radio", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 2, Name: "Sensor", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 3, Name: "ResettableOverTemp", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 4, Name: "NonResettableOverTemp", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 5, Name: "PowerSource", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 6, Name: "VisualDisplayFault", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 7, Name: "AudioOutputFault", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 8, Name: "UserInterfaceFault", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 9, Name: "NonVolatileMemoryError", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 10, Name: "TamperDetected", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
}}

// InterfaceTypeEnum is the InterfaceTypeEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type InterfaceTypeEnum uint8

// InterfaceTypeEnum values.
const (
	InterfaceTypeUnspecified InterfaceTypeEnum = 0 // M
	InterfaceTypeWiFi        InterfaceTypeEnum = 1 // O
	InterfaceTypeEthernet    InterfaceTypeEnum = 2 // O
	InterfaceTypeCellular    InterfaceTypeEnum = 3 // O
	InterfaceTypeThread      InterfaceTypeEnum = 4 // O
)

// InterfaceTypeEnumDef describes InterfaceTypeEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var InterfaceTypeEnumDef = &spec.Enum{Name: "InterfaceTypeEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Unspecified", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "WiFi", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 2, Name: "Ethernet", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 3, Name: "Cellular", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 4, Name: "Thread", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
}}

// NetworkFaultEnum is the NetworkFaultEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type NetworkFaultEnum uint8

// NetworkFaultEnum values.
const (
	NetworkFaultUnspecified      NetworkFaultEnum = 0 // M
	NetworkFaultHardwareFailure  NetworkFaultEnum = 1 // O
	NetworkFaultNetworkJammed    NetworkFaultEnum = 2 // O
	NetworkFaultConnectionFailed NetworkFaultEnum = 3 // O
)

// NetworkFaultEnumDef describes NetworkFaultEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var NetworkFaultEnumDef = &spec.Enum{Name: "NetworkFaultEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Unspecified", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "HardwareFailure", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 2, Name: "NetworkJammed", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 3, Name: "ConnectionFailed", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
}}

// NetworkInterface is the NetworkInterface struct.
type NetworkInterface struct {
	Name                            string              // 0: string, M, max 32
	IsOperational                   bool                // 1: bool, M
	OffPremiseServicesReachableIPv4 spec.Nullable[bool] // 2: bool, M, X
	OffPremiseServicesReachableIPv6 spec.Nullable[bool] // 3: bool, M, X
	HardwareAddress                 []byte              // 4: hwadr, M, 6, 8
	IPv4Addresses                   [][]byte            // 5: list[ipv4adr], M, max 4
	IPv6Addresses                   [][]byte            // 6: list[ipv6adr], M, max 8
	Type                            InterfaceTypeEnum   // 7: InterfaceTypeEnum, M
}

// EncodeTLV implements spec.Encodable.
func (v NetworkInterface) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutString(enc, tlv.ContextTag(0), v.Name)
	spec.PutBool(enc, tlv.ContextTag(1), v.IsOperational)
	spec.PutNullable(spec.PutBool)(enc, tlv.ContextTag(2), v.OffPremiseServicesReachableIPv4)
	spec.PutNullable(spec.PutBool)(enc, tlv.ContextTag(3), v.OffPremiseServicesReachableIPv6)
	spec.PutBytes(enc, tlv.ContextTag(4), v.HardwareAddress)
	spec.PutList(spec.PutBytes)(enc, tlv.ContextTag(5), v.IPv4Addresses)
	spec.PutList(spec.PutBytes)(enc, tlv.ContextTag(6), v.IPv6Addresses)
	spec.PutUint[InterfaceTypeEnum](enc, tlv.ContextTag(7), v.Type)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *NetworkInterface) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "NetworkInterface",
		spec.Bind(0, "Name", true, &v.Name, spec.DecodeStringIn(0, 32)),
		spec.Bind(1, "IsOperational", true, &v.IsOperational, spec.DecodeBool),
		spec.Bind(2, "OffPremiseServicesReachableIPv4", true, &v.OffPremiseServicesReachableIPv4, spec.DecodeNullable(spec.DecodeBool)),
		spec.Bind(3, "OffPremiseServicesReachableIPv6", true, &v.OffPremiseServicesReachableIPv6, spec.DecodeNullable(spec.DecodeBool)),
		spec.Bind(4, "HardwareAddress", true, &v.HardwareAddress, spec.DecodeBytes),
		spec.Bind(5, "IPv4Addresses", true, &v.IPv4Addresses, spec.DecodeListIn(spec.DecodeBytesIn(4, 4), 0, 4)),
		spec.Bind(6, "IPv6Addresses", true, &v.IPv6Addresses, spec.DecodeListIn(spec.DecodeBytesIn(16, 16), 0, 8)),
		spec.Bind(7, "Type", true, &v.Type, spec.DecodeUint[InterfaceTypeEnum](8)),
	)
}

// NetworkInterfaceDef describes NetworkInterface.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var NetworkInterfaceDef = &spec.Struct{Name: "NetworkInterface", Fields: []spec.Field{
	{ID: 0, Name: "Name", Type: spec.Type{Name: "string", Kind: spec.KindString}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 32", Max: &spec.Bound{Int: 32}}},
	{ID: 1, Name: "IsOperational", Type: spec.Type{Name: "bool", Kind: spec.KindBool}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{ID: 2, Name: "OffPremiseServicesReachableIPv4", Type: spec.Type{Name: "bool", Kind: spec.KindBool}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Quality: spec.Quality{Nullable: true}, Default: spec.NullDefault{}},
	{ID: 3, Name: "OffPremiseServicesReachableIPv6", Type: spec.Type{Name: "bool", Kind: spec.KindBool}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Quality: spec.Quality{Nullable: true}, Default: spec.NullDefault{}},
	{ID: 4, Name: "HardwareAddress", Type: spec.Type{Name: "hwadr", Kind: spec.KindBytes}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "6, 8", Parts: []spec.Constraint{{Text: "6", Value: &spec.Bound{Int: 6}}, {Text: "8", Value: &spec.Bound{Int: 8}}}}},
	{ID: 5, Name: "IPv4Addresses", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "ipv4adr", Kind: spec.KindBytes}, Constraint: spec.Constraint{Text: "4", Value: &spec.Bound{Int: 4}}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 4", Max: &spec.Bound{Int: 4}}},
	{ID: 6, Name: "IPv6Addresses", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "ipv6adr", Kind: spec.KindBytes}, Constraint: spec.Constraint{Text: "16", Value: &spec.Bound{Int: 16}}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 8", Max: &spec.Bound{Int: 8}}},
	{ID: 7, Name: "Type", Type: spec.Type{Name: "InterfaceTypeEnum", Kind: spec.KindEnum, Bits: 8, Enum: InterfaceTypeEnumDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// RadioFaultEnum is the RadioFaultEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type RadioFaultEnum uint8

// RadioFaultEnum values.
const (
	RadioFaultUnspecified   RadioFaultEnum = 0 // M
	RadioFaultWiFiFault     RadioFaultEnum = 1 // O
	RadioFaultCellularFault RadioFaultEnum = 2 // O
	RadioFaultThreadFault   RadioFaultEnum = 3 // O
	RadioFaultNfcFault      RadioFaultEnum = 4 // O
	RadioFaultBleFault      RadioFaultEnum = 5 // O
	RadioFaultEthernetFault RadioFaultEnum = 6 // O
)

// RadioFaultEnumDef describes RadioFaultEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var RadioFaultEnumDef = &spec.Enum{Name: "RadioFaultEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Unspecified", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "WiFiFault", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 2, Name: "CellularFault", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 3, Name: "ThreadFault", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 4, Name: "NfcFault", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 5, Name: "BleFault", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	{Value: 6, Name: "EthernetFault", Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
}}

// TestEventTriggerRequest is the TestEventTrigger command payload.
type TestEventTriggerRequest struct {
	EnableKey    []byte // 0: octstr, M, 16
	EventTrigger uint64 // 1: uint64, M
}

// EncodeTLV implements spec.Encodable.
func (v TestEventTriggerRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutBytes(enc, tlv.ContextTag(0), v.EnableKey)
	spec.PutUint[uint64](enc, tlv.ContextTag(1), v.EventTrigger)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *TestEventTriggerRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "TestEventTrigger",
		spec.Bind(0, "EnableKey", true, &v.EnableKey, spec.DecodeBytesIn(16, 16)),
		spec.Bind(1, "EventTrigger", true, &v.EventTrigger, spec.DecodeUint[uint64](64)),
	)
}

// TimeSnapshotRequest is the TimeSnapshot command payload.
type TimeSnapshotRequest struct{}

// EncodeTLV implements spec.Encodable.
func (v TimeSnapshotRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *TimeSnapshotRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "TimeSnapshot")
}

// TimeSnapshotResponse is the TimeSnapshotResponse command payload.
type TimeSnapshotResponse struct {
	SystemTimeMs uint64                // 0: systime-ms, M
	PosixTimeMs  spec.Nullable[uint64] // 1: posix-ms, M, X
}

// EncodeTLV implements spec.Encodable.
func (v TimeSnapshotResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint64](enc, tlv.ContextTag(0), v.SystemTimeMs)
	spec.PutNullable(spec.PutUint[uint64])(enc, tlv.ContextTag(1), v.PosixTimeMs)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *TimeSnapshotResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "TimeSnapshotResponse",
		spec.Bind(0, "SystemTimeMs", true, &v.SystemTimeMs, spec.DecodeUint[uint64](64)),
		spec.Bind(1, "PosixTimeMs", true, &v.PosixTimeMs, spec.DecodeNullable(spec.DecodeUint[uint64](64))),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (TimeSnapshotResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdTimeSnapshotResponse
}

// PayloadTestRequestRequest is the PayloadTestRequest command payload.
type PayloadTestRequestRequest struct {
	EnableKey []byte // 0: octstr, M, 16
	Value     uint8  // 1: uint8, M
	Count     uint16 // 2: uint16, M, max 2048
}

// EncodeTLV implements spec.Encodable.
func (v PayloadTestRequestRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutBytes(enc, tlv.ContextTag(0), v.EnableKey)
	spec.PutUint[uint8](enc, tlv.ContextTag(1), v.Value)
	spec.PutUint[uint16](enc, tlv.ContextTag(2), v.Count)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *PayloadTestRequestRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "PayloadTestRequest",
		spec.Bind(0, "EnableKey", true, &v.EnableKey, spec.DecodeBytesIn(16, 16)),
		spec.Bind(1, "Value", true, &v.Value, spec.DecodeUint[uint8](8)),
		spec.Bind(2, "Count", true, &v.Count, spec.DecodeUintIn[uint16](16, 0, 2048)),
	)
}

// PayloadTestResponse is the PayloadTestResponse command payload.
type PayloadTestResponse struct {
	Payload []byte // 0: octstr, M, max 2048
}

// EncodeTLV implements spec.Encodable.
func (v PayloadTestResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutBytes(enc, tlv.ContextTag(0), v.Payload)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *PayloadTestResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "PayloadTestResponse",
		spec.Bind(0, "Payload", true, &v.Payload, spec.DecodeBytesIn(0, 2048)),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (PayloadTestResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdPayloadTestResponse
}

// HardwareFaultChangeEvent is the HardwareFaultChange event payload.
type HardwareFaultChangeEvent struct {
	Current  []HardwareFaultEnum // 0: list[HardwareFaultEnum], M, max 11
	Previous []HardwareFaultEnum // 1: list[HardwareFaultEnum], M, max 11
}

// EncodeTLV implements spec.Encodable.
func (v HardwareFaultChangeEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutList(spec.PutUint[HardwareFaultEnum])(enc, tlv.ContextTag(0), v.Current)
	spec.PutList(spec.PutUint[HardwareFaultEnum])(enc, tlv.ContextTag(1), v.Previous)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *HardwareFaultChangeEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "HardwareFaultChange",
		spec.Bind(0, "Current", true, &v.Current, spec.DecodeListIn(spec.DecodeUint[HardwareFaultEnum](8), 0, 11)),
		spec.Bind(1, "Previous", true, &v.Previous, spec.DecodeListIn(spec.DecodeUint[HardwareFaultEnum](8), 0, 11)),
	)
}

// RadioFaultChangeEvent is the RadioFaultChange event payload.
type RadioFaultChangeEvent struct {
	Current  []RadioFaultEnum // 0: list[RadioFaultEnum], M, max 7
	Previous []RadioFaultEnum // 1: list[RadioFaultEnum], M, max 7
}

// EncodeTLV implements spec.Encodable.
func (v RadioFaultChangeEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutList(spec.PutUint[RadioFaultEnum])(enc, tlv.ContextTag(0), v.Current)
	spec.PutList(spec.PutUint[RadioFaultEnum])(enc, tlv.ContextTag(1), v.Previous)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *RadioFaultChangeEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "RadioFaultChange",
		spec.Bind(0, "Current", true, &v.Current, spec.DecodeListIn(spec.DecodeUint[RadioFaultEnum](8), 0, 7)),
		spec.Bind(1, "Previous", true, &v.Previous, spec.DecodeListIn(spec.DecodeUint[RadioFaultEnum](8), 0, 7)),
	)
}

// NetworkFaultChangeEvent is the NetworkFaultChange event payload.
type NetworkFaultChangeEvent struct {
	Current  []NetworkFaultEnum // 0: list[NetworkFaultEnum], M, max 4
	Previous []NetworkFaultEnum // 1: list[NetworkFaultEnum], M, max 4
}

// EncodeTLV implements spec.Encodable.
func (v NetworkFaultChangeEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutList(spec.PutUint[NetworkFaultEnum])(enc, tlv.ContextTag(0), v.Current)
	spec.PutList(spec.PutUint[NetworkFaultEnum])(enc, tlv.ContextTag(1), v.Previous)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *NetworkFaultChangeEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "NetworkFaultChange",
		spec.Bind(0, "Current", true, &v.Current, spec.DecodeListIn(spec.DecodeUint[NetworkFaultEnum](8), 0, 4)),
		spec.Bind(1, "Previous", true, &v.Previous, spec.DecodeListIn(spec.DecodeUint[NetworkFaultEnum](8), 0, 4)),
	)
}

// BootReasonEvent is the BootReason event payload.
type BootReasonEvent struct {
	BootReason BootReasonEnum // 0: BootReasonEnum, M
}

// EncodeTLV implements spec.Encodable.
func (v BootReasonEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[BootReasonEnum](enc, tlv.ContextTag(0), v.BootReason)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *BootReasonEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "BootReason",
		spec.Bind(0, "BootReason", true, &v.BootReason, spec.DecodeUint[BootReasonEnum](8)),
	)
}

func decodeTestEventTriggerRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[TestEventTriggerRequest](n)
}

func decodeTimeSnapshotRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[TimeSnapshotRequest](n)
}

func decodeTimeSnapshotResponse(n spec.Node) (any, error) {
	return spec.DecodeStruct[TimeSnapshotResponse](n)
}

func decodePayloadTestRequestRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[PayloadTestRequestRequest](n)
}

func decodePayloadTestResponse(n spec.Node) (any, error) {
	return spec.DecodeStruct[PayloadTestResponse](n)
}

func decodeHardwareFaultChangeEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[HardwareFaultChangeEvent](n)
}

func decodeRadioFaultChangeEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[RadioFaultChangeEvent](n)
}

func decodeNetworkFaultChangeEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[NetworkFaultChangeEvent](n)
}

func decodeBootReasonEvent(n spec.Node) (any, error) { return spec.DecodeStruct[BootReasonEvent](n) }

func decodeAttrNetworkInterfaces(n spec.Node) (any, error) {
	v, err := spec.DecodeListIn(spec.DecodeStruct[NetworkInterface], 0, 8)(n)
	return spec.List[NetworkInterface](v), err
}

func decodeAttrDeviceLoadStatus(n spec.Node) (any, error) {
	return spec.DecodeStruct[DeviceLoadStruct](n)
}

// Definition is the GeneralDiagnostics cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Features: []spec.Feature{
		{Name: "DMTEST", Title: "DataModelTest", Bit: 0, Conformance: spec.Conformance{Text: "desc", Op: spec.ConfDesc}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrNetworkInterfaces, Name: "NetworkInterfaces",
			Type:        spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "NetworkInterface", Kind: spec.KindStruct, Struct: NetworkInterfaceDef}}},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "max 8", Max: &spec.Bound{Int: 8}},
			Decode:      decodeAttrNetworkInterfaces,
		},
		{
			ID: AttrRebootCount, Name: "RebootCount",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{NonVolatile: true},
		},
		{
			ID: AttrUpTime, Name: "UpTime",
			Type:        spec.Type{Name: "uint64", Kind: spec.KindUint, Bits: 64},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{ChangesOmitted: true},
		},
		{
			ID: AttrTotalOperationalHours, Name: "TotalOperationalHours",
			Type:        spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{NonVolatile: true, ChangesOmitted: true},
		},
		{
			ID: AttrBootReason, Name: "BootReason",
			Type:        spec.Type{Name: "BootReasonEnum", Kind: spec.KindEnum, Bits: 8, Enum: BootReasonEnumDef},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
		},
		{
			ID: AttrActiveHardwareFaults, Name: "ActiveHardwareFaults",
			Type:        spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "HardwareFaultEnum", Kind: spec.KindEnum, Bits: 8, Enum: HardwareFaultEnumDef}}},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "max 11", Max: &spec.Bound{Int: 11}},
		},
		{
			ID: AttrActiveRadioFaults, Name: "ActiveRadioFaults",
			Type:        spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "RadioFaultEnum", Kind: spec.KindEnum, Bits: 8, Enum: RadioFaultEnumDef}}},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "max 7", Max: &spec.Bound{Int: 7}},
		},
		{
			ID: AttrActiveNetworkFaults, Name: "ActiveNetworkFaults",
			Type:        spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "NetworkFaultEnum", Kind: spec.KindEnum, Bits: 8, Enum: NetworkFaultEnumDef}}},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "max 4", Max: &spec.Bound{Int: 4}},
		},
		{
			ID: AttrTestEventTriggersEnabled, Name: "TestEventTriggersEnabled",
			Type:        spec.Type{Name: "bool", Kind: spec.KindBool},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
		},
		{
			ID: AttrDoNotUse, Name: "DoNotUse",
			Type:        spec.Type{Name: "", Kind: spec.KindAny},
			Conformance: spec.Conformance{Text: "X", Op: spec.ConfDisallowed},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
		},
		{
			ID: AttrDeviceLoadStatus, Name: "DeviceLoadStatus",
			Type:        spec.Type{Name: "DeviceLoadStruct", Kind: spec.KindStruct, Struct: DeviceLoadStructDef},
			Conformance: spec.Conformance{Text: "Rev >= v3", Op: spec.ConfRevision, Rev: 3},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{ChangesOmitted: true},
			Decode:      decodeAttrDeviceLoadStatus,
		},
	},
	Commands: []spec.Command{
		{
			ID: CmdTestEventTrigger, Name: "TestEventTrigger", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage},
			Fields: []spec.Field{
				{ID: 0, Name: "EnableKey", Type: spec.Type{Name: "octstr", Kind: spec.KindBytes}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "16", Value: &spec.Bound{Int: 16}}},
				{ID: 1, Name: "EventTrigger", Type: spec.Type{Name: "uint64", Kind: spec.KindUint, Bits: 64}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeTestEventTriggerRequest,
		},
		{
			ID: CmdTimeSnapshot, Name: "TimeSnapshot", Direction: spec.Request,
			Response:    "TimeSnapshotResponse",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate},
			Decode:      decodeTimeSnapshotRequest,
		},
		{
			ID: CmdTimeSnapshotResponse, Name: "TimeSnapshotResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "SystemTimeMs", Type: spec.Type{Name: "systime-ms", Kind: spec.KindUint, Bits: 64}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 1, Name: "PosixTimeMs", Type: spec.Type{Name: "posix-ms", Kind: spec.KindUint, Bits: 64}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Quality: spec.Quality{Nullable: true}, Default: spec.NullDefault{}},
			},
			Decode: decodeTimeSnapshotResponse,
		},
		{
			ID: CmdPayloadTestRequest, Name: "PayloadTestRequest", Direction: spec.Request,
			Response:    "PayloadTestResponse",
			Conformance: spec.Conformance{Text: "DMTEST", Op: spec.ConfName, Name: "DMTEST"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage},
			Fields: []spec.Field{
				{ID: 0, Name: "EnableKey", Type: spec.Type{Name: "octstr", Kind: spec.KindBytes}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "16", Value: &spec.Bound{Int: 16}}},
				{ID: 1, Name: "Value", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 2, Name: "Count", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 2048", Max: &spec.Bound{Int: 2048}}},
			},
			Decode: decodePayloadTestRequestRequest,
		},
		{
			ID: CmdPayloadTestResponse, Name: "PayloadTestResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "DMTEST", Op: spec.ConfName, Name: "DMTEST"},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "Payload", Type: spec.Type{Name: "octstr", Kind: spec.KindBytes}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 2048", Max: &spec.Bound{Int: 2048}}},
			},
			Decode: decodePayloadTestResponse,
		},
	},
	Events: []spec.Event{
		{
			ID: EventHardwareFaultChange, Name: "HardwareFaultChange", Priority: spec.PriorityCritical,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "Current", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "HardwareFaultEnum", Kind: spec.KindEnum, Bits: 8, Enum: HardwareFaultEnumDef}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 11", Max: &spec.Bound{Int: 11}}},
				{ID: 1, Name: "Previous", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "HardwareFaultEnum", Kind: spec.KindEnum, Bits: 8, Enum: HardwareFaultEnumDef}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 11", Max: &spec.Bound{Int: 11}}},
			},
			Decode: decodeHardwareFaultChangeEvent,
		},
		{
			ID: EventRadioFaultChange, Name: "RadioFaultChange", Priority: spec.PriorityCritical,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "Current", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "RadioFaultEnum", Kind: spec.KindEnum, Bits: 8, Enum: RadioFaultEnumDef}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 7", Max: &spec.Bound{Int: 7}}},
				{ID: 1, Name: "Previous", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "RadioFaultEnum", Kind: spec.KindEnum, Bits: 8, Enum: RadioFaultEnumDef}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 7", Max: &spec.Bound{Int: 7}}},
			},
			Decode: decodeRadioFaultChangeEvent,
		},
		{
			ID: EventNetworkFaultChange, Name: "NetworkFaultChange", Priority: spec.PriorityCritical,
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "Current", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "NetworkFaultEnum", Kind: spec.KindEnum, Bits: 8, Enum: NetworkFaultEnumDef}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 4", Max: &spec.Bound{Int: 4}}},
				{ID: 1, Name: "Previous", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "NetworkFaultEnum", Kind: spec.KindEnum, Bits: 8, Enum: NetworkFaultEnumDef}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 4", Max: &spec.Bound{Int: 4}}},
			},
			Decode: decodeNetworkFaultChangeEvent,
		},
		{
			ID: EventBootReason, Name: "BootReason", Priority: spec.PriorityCritical,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "BootReason", Type: spec.Type{Name: "BootReasonEnum", Kind: spec.KindEnum, Bits: 8, Enum: BootReasonEnumDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeBootReasonEvent,
		},
	},
}

func init() { spec.Register(Definition) }
