// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package occupancysensing is the generated definition of the Matter OccupancySensing cluster
// (0x0406, revision 7), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package occupancysensing

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0406
	Name             = "OccupancySensing"
	Revision  uint16 = 7
)

// Attribute ids.
const (
	AttrOccupancy                                    uint32 = 0x0000 // OccupancyBitmap, M, R V
	AttrOccupancySensorType                          uint32 = 0x0001 // OccupancySensorTypeEnum, M, D, R V, F
	AttrOccupancySensorTypeBitmap                    uint32 = 0x0002 // OccupancySensorTypeBitmap, M, D, R V, F
	AttrHoldTime                                     uint32 = 0x0003 // uint16, O, RW VM, N
	AttrHoldTimeLimits                               uint32 = 0x0004 // HoldTimeLimitsStruct, HoldTime, R V, F
	AttrPirOccupiedToUnoccupiedDelay                 uint32 = 0x0010 // uint16, [HoldTime & (PIR | !PIR & !US & !PHY)], D, RW VM, N
	AttrPirUnoccupiedToOccupiedDelay                 uint32 = 0x0011 // uint16, HoldTime & (PIR | !PIR & !US & !PHY) & PirUnoccupiedToOccupiedThreshold, [HoldTime & (PIR | !PIR & !US & !PHY)], D, RW VM, N
	AttrPirUnoccupiedToOccupiedThreshold             uint32 = 0x0012 // uint8, HoldTime & (PIR | !PIR & !US & !PHY) & PirUnoccupiedToOccupiedDelay, [HoldTime & (PIR | !PIR & !US & !PHY)], D, RW VM, N
	AttrUltrasonicOccupiedToUnoccupiedDelay          uint32 = 0x0020 // uint16, [HoldTime & US], D, RW VM, N
	AttrUltrasonicUnoccupiedToOccupiedDelay          uint32 = 0x0021 // uint16, HoldTime & US & UltrasonicUnoccupiedToOccupiedThreshold, [HoldTime & US], D, RW VM, N
	AttrUltrasonicUnoccupiedToOccupiedThreshold      uint32 = 0x0022 // uint8, HoldTime & US & UltrasonicUnoccupiedToOccupiedDelay, [HoldTime & US], D, RW VM, N
	AttrPhysicalContactOccupiedToUnoccupiedDelay     uint32 = 0x0030 // uint16, [HoldTime & PHY], D, RW VM, N
	AttrPhysicalContactUnoccupiedToOccupiedDelay     uint32 = 0x0031 // uint16, HoldTime & PHY & PhysicalContactUnoccupiedToOccupiedThreshold, [HoldTime & PHY], D, RW VM, N
	AttrPhysicalContactUnoccupiedToOccupiedThreshold uint32 = 0x0032 // uint8, HoldTime & PHY & PhysicalContactUnoccupiedToOccupiedDelay, [HoldTime & PHY], D, RW VM, N
)

// Event ids.
const (
	EventOccupancyChanged uint32 = 0x00 // info, OCCEVENT, O
)

// Feature is a OccupancySensing FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// FeatureMap bits.
const (
	FeatureOther           Feature = 1 << 0 // OTHER, O.a+
	FeaturePassiveInfrared Feature = 1 << 1 // PIR, O.a+
	FeatureUltrasonic      Feature = 1 << 2 // US, O.a+
	FeaturePhysicalContact Feature = 1 << 3 // PHY, O.a+
	FeatureActiveInfrared  Feature = 1 << 4 // AIR, O.a+
	FeatureRadar           Feature = 1 << 5 // RAD, O.a+
	FeatureRfSensing       Feature = 1 << 6 // RFS, O.a+
	FeatureVision          Feature = 1 << 7 // VIS, O.a+
	FeatureOccupancyEvent  Feature = 1 << 9 // OCCEVENT, [Rev >= v7]
)

// HoldTimeLimitsStruct is the HoldTimeLimitsStruct struct.
type HoldTimeLimitsStruct struct {
	HoldTimeMin     uint16 // 0: uint16, M, min 1
	HoldTimeMax     uint16 // 1: uint16, M, min maxOf(holdTimeMin, 10)
	HoldTimeDefault uint16 // 2: uint16, M, holdTimeMin to holdTimeMax
}

// EncodeTLV implements spec.Encodable.
func (v HoldTimeLimitsStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.HoldTimeMin)
	spec.PutUint[uint16](enc, tlv.ContextTag(1), v.HoldTimeMax)
	spec.PutUint[uint16](enc, tlv.ContextTag(2), v.HoldTimeDefault)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *HoldTimeLimitsStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "HoldTimeLimitsStruct",
		spec.Bind(0, "HoldTimeMin", true, &v.HoldTimeMin, spec.DecodeUintIn[uint16](16, 1, 65535)),
		spec.Bind(1, "HoldTimeMax", true, &v.HoldTimeMax, spec.DecodeUint[uint16](16)),
		spec.Bind(2, "HoldTimeDefault", true, &v.HoldTimeDefault, spec.DecodeUint[uint16](16)),
	)
}

// HoldTimeLimitsStructDef describes HoldTimeLimitsStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var HoldTimeLimitsStructDef = &spec.Struct{Name: "HoldTimeLimitsStruct", Fields: []spec.Field{
	{ID: 0, Name: "HoldTimeMin", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}}},
	{ID: 1, Name: "HoldTimeMax", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "min maxOf(holdTimeMin, 10)", Min: &spec.Bound{Expr: "{\"type\":\"maxOf\",\"args\":[{\"type\":\"reference\",\"name\":\"holdTimeMin\"},10]}"}}},
	{ID: 2, Name: "HoldTimeDefault", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "holdTimeMin to holdTimeMax", Min: &spec.Bound{Ref: "holdTimeMin"}, Max: &spec.Bound{Ref: "holdTimeMax"}}},
}}

// OccupancyBitmap is the OccupancyBitmap map8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type OccupancyBitmap uint8

// OccupancyBitmap bits; a member wider than one bit is its mask.
const (
	OccupancyOccupied OccupancyBitmap = 1 << 0 // M
)

// OccupancyBitmapDef describes OccupancyBitmap.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var OccupancyBitmapDef = &spec.Bitmap{Name: "OccupancyBitmap", Bits: 8, Members: []spec.BitmapMember{
	{Name: "Occupied", Bit: 0, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// OccupancySensorTypeBitmap is the OccupancySensorTypeBitmap map8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type OccupancySensorTypeBitmap uint8

// OccupancySensorTypeBitmap bits; a member wider than one bit is its mask.
const (
	OccupancySensorTypeBitmapPir             OccupancySensorTypeBitmap = 1 << 0 // M
	OccupancySensorTypeBitmapUltrasonic      OccupancySensorTypeBitmap = 1 << 1 // M
	OccupancySensorTypeBitmapPhysicalContact OccupancySensorTypeBitmap = 1 << 2 // M
)

// OccupancySensorTypeBitmapDef describes OccupancySensorTypeBitmap.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var OccupancySensorTypeBitmapDef = &spec.Bitmap{Name: "OccupancySensorTypeBitmap", Bits: 8, Members: []spec.BitmapMember{
	{Name: "Pir", Bit: 0, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "Ultrasonic", Bit: 1, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Name: "PhysicalContact", Bit: 2, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// OccupancySensorTypeEnum is the OccupancySensorTypeEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type OccupancySensorTypeEnum uint8

// OccupancySensorTypeEnum values.
const (
	OccupancySensorTypeEnumPir              OccupancySensorTypeEnum = 0 // M
	OccupancySensorTypeEnumUltrasonic       OccupancySensorTypeEnum = 1 // M
	OccupancySensorTypeEnumPirAndUltrasonic OccupancySensorTypeEnum = 2 // M
	OccupancySensorTypeEnumPhysicalContact  OccupancySensorTypeEnum = 3 // M
)

// OccupancySensorTypeEnumDef describes OccupancySensorTypeEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var OccupancySensorTypeEnumDef = &spec.Enum{Name: "OccupancySensorTypeEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Pir", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Ultrasonic", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "PirAndUltrasonic", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 3, Name: "PhysicalContact", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// OccupancyChangedEvent is the OccupancyChanged event payload.
type OccupancyChangedEvent struct {
	Occupancy OccupancyBitmap // 0: OccupancyBitmap, M
}

// EncodeTLV implements spec.Encodable.
func (v OccupancyChangedEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[OccupancyBitmap](enc, tlv.ContextTag(0), v.Occupancy)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *OccupancyChangedEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "OccupancyChanged",
		spec.Bind(0, "Occupancy", true, &v.Occupancy, spec.DecodeUint[OccupancyBitmap](8)),
	)
}

func decodeOccupancyChangedEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[OccupancyChangedEvent](n)
}

func decodeAttrHoldTimeLimits(n spec.Node) (any, error) {
	return spec.DecodeStruct[HoldTimeLimitsStruct](n)
}

// Definition is the OccupancySensing cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Features: []spec.Feature{
		{Name: "OTHER", Title: "Other", Bit: 0, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "PIR", Title: "PassiveInfrared", Bit: 1, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "US", Title: "Ultrasonic", Bit: 2, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "PHY", Title: "PhysicalContact", Bit: 3, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "AIR", Title: "ActiveInfrared", Bit: 4, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "RAD", Title: "Radar", Bit: 5, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "RFS", Title: "RfSensing", Bit: 6, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "VIS", Title: "Vision", Bit: 7, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "OCCEVENT", Title: "OccupancyEvent", Bit: 9, Conformance: spec.Conformance{Text: "[Rev >= v7]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfRevision, Rev: 7}}}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrOccupancy, Name: "Occupancy",
			Type:        spec.Type{Name: "OccupancyBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: OccupancyBitmapDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "0 to 1", Min: &spec.Bound{Int: 0}, Max: &spec.Bound{Int: 1}},
		},
		{
			ID: AttrOccupancySensorType, Name: "OccupancySensorType",
			Type:        spec.Type{Name: "OccupancySensorTypeEnum", Kind: spec.KindEnum, Bits: 8, Enum: OccupancySensorTypeEnumDef},
			Conformance: spec.Conformance{Text: "M, D", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfMandatory}, {Op: spec.ConfDeprecated}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
		},
		{
			ID: AttrOccupancySensorTypeBitmap, Name: "OccupancySensorTypeBitmap",
			Type:        spec.Type{Name: "OccupancySensorTypeBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: OccupancySensorTypeBitmapDef},
			Conformance: spec.Conformance{Text: "M, D", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfMandatory}, {Op: spec.ConfDeprecated}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "0 to 7", Min: &spec.Bound{Int: 0}, Max: &spec.Bound{Int: 7}},
		},
		{
			ID: AttrHoldTime, Name: "HoldTime",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "holdTimeLimits.holdTimeMin to holdTimeLimits.holdTimeMax", Min: &spec.Bound{Expr: "{\"type\":\".\",\"lhs\":{\"type\":\"reference\",\"name\":\"holdTimeLimits\"},\"rhs\":{\"type\":\"reference\",\"name\":\"holdTimeMin\"}}"}, Max: &spec.Bound{Expr: "{\"type\":\".\",\"lhs\":{\"type\":\"reference\",\"name\":\"holdTimeLimits\"},\"rhs\":{\"type\":\"reference\",\"name\":\"holdTimeMax\"}}"}},
		},
		{
			ID: AttrHoldTimeLimits, Name: "HoldTimeLimits",
			Type:        spec.Type{Name: "HoldTimeLimitsStruct", Kind: spec.KindStruct, Struct: HoldTimeLimitsStructDef},
			Conformance: spec.Conformance{Text: "HoldTime", Op: spec.ConfName, Name: "HoldTime"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Decode:      decodeAttrHoldTimeLimits,
		},
		{
			ID: AttrPirOccupiedToUnoccupiedDelay, Name: "PirOccupiedToUnoccupiedDelay",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "[HoldTime & (PIR | !PIR & !US & !PHY)], D", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfOr, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PIR"}, {Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PIR"}}}, {Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "US"}}}}}, {Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PHY"}}}}}}}}}}}, {Op: spec.ConfDeprecated}}},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Default:     float64(0),
		},
		{
			ID: AttrPirUnoccupiedToOccupiedDelay, Name: "PirUnoccupiedToOccupiedDelay",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "HoldTime & (PIR | !PIR & !US & !PHY) & PirUnoccupiedToOccupiedThreshold, [HoldTime & (PIR | !PIR & !US & !PHY)], D", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfOr, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PIR"}, {Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PIR"}}}, {Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "US"}}}}}, {Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PHY"}}}}}}}}}, {Op: spec.ConfName, Name: "PirUnoccupiedToOccupiedThreshold"}}}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfOr, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PIR"}, {Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PIR"}}}, {Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "US"}}}}}, {Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PHY"}}}}}}}}}}}, {Op: spec.ConfDeprecated}}},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Default:     float64(0),
		},
		{
			ID: AttrPirUnoccupiedToOccupiedThreshold, Name: "PirUnoccupiedToOccupiedThreshold",
			Type:        spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "HoldTime & (PIR | !PIR & !US & !PHY) & PirUnoccupiedToOccupiedDelay, [HoldTime & (PIR | !PIR & !US & !PHY)], D", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfOr, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PIR"}, {Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PIR"}}}, {Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "US"}}}}}, {Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PHY"}}}}}}}}}, {Op: spec.ConfName, Name: "PirUnoccupiedToOccupiedDelay"}}}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfOr, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PIR"}, {Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PIR"}}}, {Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "US"}}}}}, {Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PHY"}}}}}}}}}}}, {Op: spec.ConfDeprecated}}},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "1 to 254", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 254}},
			Default:     float64(1),
		},
		{
			ID: AttrUltrasonicOccupiedToUnoccupiedDelay, Name: "UltrasonicOccupiedToUnoccupiedDelay",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "[HoldTime & US], D", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfName, Name: "US"}}}}}, {Op: spec.ConfDeprecated}}},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Default:     float64(0),
		},
		{
			ID: AttrUltrasonicUnoccupiedToOccupiedDelay, Name: "UltrasonicUnoccupiedToOccupiedDelay",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "HoldTime & US & UltrasonicUnoccupiedToOccupiedThreshold, [HoldTime & US], D", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfName, Name: "US"}}}, {Op: spec.ConfName, Name: "UltrasonicUnoccupiedToOccupiedThreshold"}}}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfName, Name: "US"}}}}}, {Op: spec.ConfDeprecated}}},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Default:     float64(0),
		},
		{
			ID: AttrUltrasonicUnoccupiedToOccupiedThreshold, Name: "UltrasonicUnoccupiedToOccupiedThreshold",
			Type:        spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "HoldTime & US & UltrasonicUnoccupiedToOccupiedDelay, [HoldTime & US], D", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfName, Name: "US"}}}, {Op: spec.ConfName, Name: "UltrasonicUnoccupiedToOccupiedDelay"}}}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfName, Name: "US"}}}}}, {Op: spec.ConfDeprecated}}},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "1 to 254", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 254}},
			Default:     float64(1),
		},
		{
			ID: AttrPhysicalContactOccupiedToUnoccupiedDelay, Name: "PhysicalContactOccupiedToUnoccupiedDelay",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "[HoldTime & PHY], D", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfName, Name: "PHY"}}}}}, {Op: spec.ConfDeprecated}}},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Default:     float64(0),
		},
		{
			ID: AttrPhysicalContactUnoccupiedToOccupiedDelay, Name: "PhysicalContactUnoccupiedToOccupiedDelay",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "HoldTime & PHY & PhysicalContactUnoccupiedToOccupiedThreshold, [HoldTime & PHY], D", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfName, Name: "PHY"}}}, {Op: spec.ConfName, Name: "PhysicalContactUnoccupiedToOccupiedThreshold"}}}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfName, Name: "PHY"}}}}}, {Op: spec.ConfDeprecated}}},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Default:     float64(0),
		},
		{
			ID: AttrPhysicalContactUnoccupiedToOccupiedThreshold, Name: "PhysicalContactUnoccupiedToOccupiedThreshold",
			Type:        spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "HoldTime & PHY & PhysicalContactUnoccupiedToOccupiedDelay, [HoldTime & PHY], D", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfName, Name: "PHY"}}}, {Op: spec.ConfName, Name: "PhysicalContactUnoccupiedToOccupiedDelay"}}}, {Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "HoldTime"}, {Op: spec.ConfName, Name: "PHY"}}}}}, {Op: spec.ConfDeprecated}}},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeManage},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "1 to 254", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 254}},
			Default:     float64(1),
		},
	},
	Events: []spec.Event{
		{
			ID: EventOccupancyChanged, Name: "OccupancyChanged", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "OCCEVENT, O", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfName, Name: "OCCEVENT"}, {Op: spec.ConfOptional}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "Occupancy", Type: spec.Type{Name: "OccupancyBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: OccupancyBitmapDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeOccupancyChangedEvent,
		},
	},
}

func init() { spec.Register(Definition) }
