// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package booleanstateconfiguration is the generated definition of the Matter BooleanStateConfiguration cluster
// (0x0080, revision 2), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package booleanstateconfiguration

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0080
	Name             = "BooleanStateConfiguration"
	Revision  uint16 = 2
)

// Attribute ids.
const (
	AttrCurrentSensitivityLevel    uint32 = 0x0000 // uint8, SENSLVL, RW VO, N
	AttrSupportedSensitivityLevels uint32 = 0x0001 // uint8, SENSLVL, R V, F
	AttrDefaultSensitivityLevel    uint32 = 0x0002 // uint8, [SENSLVL], R V, F
	AttrAlarmsActive               uint32 = 0x0003 // AlarmModeBitmap, VIS | AUD, R V
	AttrAlarmsSuppressed           uint32 = 0x0004 // AlarmModeBitmap, SPRS, R V
	AttrAlarmsEnabled              uint32 = 0x0005 // AlarmModeBitmap, [VIS | AUD], R V, N
	AttrAlarmsSupported            uint32 = 0x0006 // AlarmModeBitmap, VIS | AUD, R V, F
	AttrSensorFault                uint32 = 0x0007 // SensorFaultBitmap, O, R V
)

// Command ids.
const (
	CmdSuppressAlarm      uint32 = 0x00 // request → status, SPRS
	CmdEnableDisableAlarm uint32 = 0x01 // request → status, VIS | AUD
)

// Event ids.
const (
	EventAlarmsStateChanged uint32 = 0x00 // info, VIS | AUD
	EventSensorFault        uint32 = 0x01 // info, FAULTEV, O
)

// Feature is a BooleanStateConfiguration FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// FeatureMap bits.
const (
	FeatureVisual           Feature = 1 << 0 // VIS, O
	FeatureAudible          Feature = 1 << 1 // AUD, O
	FeatureAlarmSuppress    Feature = 1 << 2 // SPRS, [VIS | AUD]
	FeatureSensitivityLevel Feature = 1 << 3 // SENSLVL, O
	FeatureFaultEvents      Feature = 1 << 4 // FAULTEV, [Rev >= v2]
)

// AlarmModeBitmap is the AlarmModeBitmap map8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type AlarmModeBitmap uint8

// AlarmModeBitmap bits; a member wider than one bit is its mask.
const (
	AlarmModeVisual  AlarmModeBitmap = 1 << 0 // VIS
	AlarmModeAudible AlarmModeBitmap = 1 << 1 // AUD
)

// AlarmModeBitmapDef describes AlarmModeBitmap.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var AlarmModeBitmapDef = &spec.Bitmap{Name: "AlarmModeBitmap", Bits: 8, Members: []spec.BitmapMember{
	{Name: "Visual", Bit: 0, Width: 1, Conformance: spec.Conformance{Text: "VIS", Op: spec.ConfName, Name: "VIS"}},
	{Name: "Audible", Bit: 1, Width: 1, Conformance: spec.Conformance{Text: "AUD", Op: spec.ConfName, Name: "AUD"}},
}}

// SensorFaultBitmap is the SensorFaultBitmap map16.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type SensorFaultBitmap uint16

// SensorFaultBitmap bits; a member wider than one bit is its mask.
const (
	SensorFaultGeneralFault SensorFaultBitmap = 1 << 0 // M
)

// SensorFaultBitmapDef describes SensorFaultBitmap.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var SensorFaultBitmapDef = &spec.Bitmap{Name: "SensorFaultBitmap", Bits: 16, Members: []spec.BitmapMember{
	{Name: "GeneralFault", Bit: 0, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// SuppressAlarmRequest is the SuppressAlarm command payload.
type SuppressAlarmRequest struct {
	AlarmsToSuppress AlarmModeBitmap // 0: AlarmModeBitmap, M
}

// EncodeTLV implements spec.Encodable.
func (v SuppressAlarmRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[AlarmModeBitmap](enc, tlv.ContextTag(0), v.AlarmsToSuppress)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *SuppressAlarmRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "SuppressAlarm",
		spec.Bind(0, "AlarmsToSuppress", true, &v.AlarmsToSuppress, spec.DecodeUint[AlarmModeBitmap](8)),
	)
}

// EnableDisableAlarmRequest is the EnableDisableAlarm command payload.
type EnableDisableAlarmRequest struct {
	AlarmsToEnableDisable AlarmModeBitmap // 0: AlarmModeBitmap, M
}

// EncodeTLV implements spec.Encodable.
func (v EnableDisableAlarmRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[AlarmModeBitmap](enc, tlv.ContextTag(0), v.AlarmsToEnableDisable)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *EnableDisableAlarmRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "EnableDisableAlarm",
		spec.Bind(0, "AlarmsToEnableDisable", true, &v.AlarmsToEnableDisable, spec.DecodeUint[AlarmModeBitmap](8)),
	)
}

// AlarmsStateChangedEvent is the AlarmsStateChanged event payload.
type AlarmsStateChangedEvent struct {
	AlarmsActive     AlarmModeBitmap  // 0: AlarmModeBitmap, M
	AlarmsSuppressed *AlarmModeBitmap // 1: AlarmModeBitmap, SPRS
}

// EncodeTLV implements spec.Encodable.
func (v AlarmsStateChangedEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[AlarmModeBitmap](enc, tlv.ContextTag(0), v.AlarmsActive)
	spec.PutOptional(enc, tlv.ContextTag(1), v.AlarmsSuppressed, spec.PutUint[AlarmModeBitmap])
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *AlarmsStateChangedEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "AlarmsStateChanged",
		spec.Bind(0, "AlarmsActive", true, &v.AlarmsActive, spec.DecodeUint[AlarmModeBitmap](8)),
		spec.Bind(1, "AlarmsSuppressed", false, &v.AlarmsSuppressed, spec.DecodeOptional(spec.DecodeUint[AlarmModeBitmap](8))),
	)
}

// SensorFaultEvent is the SensorFault event payload.
type SensorFaultEvent struct {
	SensorFault SensorFaultBitmap // 0: SensorFaultBitmap, M
}

// EncodeTLV implements spec.Encodable.
func (v SensorFaultEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[SensorFaultBitmap](enc, tlv.ContextTag(0), v.SensorFault)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *SensorFaultEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "SensorFault",
		spec.Bind(0, "SensorFault", true, &v.SensorFault, spec.DecodeUint[SensorFaultBitmap](16)),
	)
}

func decodeSuppressAlarmRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[SuppressAlarmRequest](n)
}

func decodeEnableDisableAlarmRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[EnableDisableAlarmRequest](n)
}

func decodeAlarmsStateChangedEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[AlarmsStateChangedEvent](n)
}

func decodeSensorFaultEvent(n spec.Node) (any, error) { return spec.DecodeStruct[SensorFaultEvent](n) }

// Definition is the BooleanStateConfiguration cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Features: []spec.Feature{
		{Name: "VIS", Title: "Visual", Bit: 0, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
		{Name: "AUD", Title: "Audible", Bit: 1, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
		{Name: "SPRS", Title: "AlarmSuppress", Bit: 2, Conformance: spec.Conformance{Text: "[VIS | AUD]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfOr, Args: []spec.Conformance{{Op: spec.ConfName, Name: "VIS"}, {Op: spec.ConfName, Name: "AUD"}}}}}},
		{Name: "SENSLVL", Title: "SensitivityLevel", Bit: 3, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
		{Name: "FAULTEV", Title: "FaultEvents", Bit: 4, Conformance: spec.Conformance{Text: "[Rev >= v2]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfRevision, Rev: 2}}}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrCurrentSensitivityLevel, Name: "CurrentSensitivityLevel",
			Type:        spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "SENSLVL", Op: spec.ConfName, Name: "SENSLVL"},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Quality:     spec.Quality{NonVolatile: true},
			Constraint:  spec.Constraint{Text: "max supportedSensitivityLevels - 1", Max: &spec.Bound{Expr: "{\"type\":\"-\",\"lhs\":{\"type\":\"reference\",\"name\":\"supportedSensitivityLevels\"},\"rhs\":1}"}},
		},
		{
			ID: AttrSupportedSensitivityLevels, Name: "SupportedSensitivityLevels",
			Type:        spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "SENSLVL", Op: spec.ConfName, Name: "SENSLVL"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "2 to 10", Min: &spec.Bound{Int: 2}, Max: &spec.Bound{Int: 10}},
		},
		{
			ID: AttrDefaultSensitivityLevel, Name: "DefaultSensitivityLevel",
			Type:        spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "[SENSLVL]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "SENSLVL"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "max supportedSensitivityLevels - 1", Max: &spec.Bound{Expr: "{\"type\":\"-\",\"lhs\":{\"type\":\"reference\",\"name\":\"supportedSensitivityLevels\"},\"rhs\":1}"}},
		},
		{
			ID: AttrAlarmsActive, Name: "AlarmsActive",
			Type:        spec.Type{Name: "AlarmModeBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: AlarmModeBitmapDef},
			Conformance: spec.Conformance{Text: "VIS | AUD", Op: spec.ConfOr, Args: []spec.Conformance{{Op: spec.ConfName, Name: "VIS"}, {Op: spec.ConfName, Name: "AUD"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
		},
		{
			ID: AttrAlarmsSuppressed, Name: "AlarmsSuppressed",
			Type:        spec.Type{Name: "AlarmModeBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: AlarmModeBitmapDef},
			Conformance: spec.Conformance{Text: "SPRS", Op: spec.ConfName, Name: "SPRS"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
		},
		{
			ID: AttrAlarmsEnabled, Name: "AlarmsEnabled",
			Type:        spec.Type{Name: "AlarmModeBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: AlarmModeBitmapDef},
			Conformance: spec.Conformance{Text: "[VIS | AUD]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfOr, Args: []spec.Conformance{{Op: spec.ConfName, Name: "VIS"}, {Op: spec.ConfName, Name: "AUD"}}}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{NonVolatile: true},
		},
		{
			ID: AttrAlarmsSupported, Name: "AlarmsSupported",
			Type:        spec.Type{Name: "AlarmModeBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: AlarmModeBitmapDef},
			Conformance: spec.Conformance{Text: "VIS | AUD", Op: spec.ConfOr, Args: []spec.Conformance{{Op: spec.ConfName, Name: "VIS"}, {Op: spec.ConfName, Name: "AUD"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
		},
		{
			ID: AttrSensorFault, Name: "SensorFault",
			Type:        spec.Type{Name: "SensorFaultBitmap", Kind: spec.KindBitmap, Bits: 16, Bitmap: SensorFaultBitmapDef},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Default:     float64(0),
		},
	},
	Commands: []spec.Command{
		{
			ID: CmdSuppressAlarm, Name: "SuppressAlarm", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "SPRS", Op: spec.ConfName, Name: "SPRS"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "AlarmsToSuppress", Type: spec.Type{Name: "AlarmModeBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: AlarmModeBitmapDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeSuppressAlarmRequest,
		},
		{
			ID: CmdEnableDisableAlarm, Name: "EnableDisableAlarm", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "VIS | AUD", Op: spec.ConfOr, Args: []spec.Conformance{{Op: spec.ConfName, Name: "VIS"}, {Op: spec.ConfName, Name: "AUD"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "AlarmsToEnableDisable", Type: spec.Type{Name: "AlarmModeBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: AlarmModeBitmapDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeEnableDisableAlarmRequest,
		},
	},
	Events: []spec.Event{
		{
			ID: EventAlarmsStateChanged, Name: "AlarmsStateChanged", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "VIS | AUD", Op: spec.ConfOr, Args: []spec.Conformance{{Op: spec.ConfName, Name: "VIS"}, {Op: spec.ConfName, Name: "AUD"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "AlarmsActive", Type: spec.Type{Name: "AlarmModeBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: AlarmModeBitmapDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 1, Name: "AlarmsSuppressed", Type: spec.Type{Name: "AlarmModeBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: AlarmModeBitmapDef}, Conformance: spec.Conformance{Text: "SPRS", Op: spec.ConfName, Name: "SPRS"}},
			},
			Decode: decodeAlarmsStateChangedEvent,
		},
		{
			ID: EventSensorFault, Name: "SensorFault", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "FAULTEV, O", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfName, Name: "FAULTEV"}, {Op: spec.ConfOptional}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "SensorFault", Type: spec.Type{Name: "SensorFaultBitmap", Kind: spec.KindBitmap, Bits: 16, Bitmap: SensorFaultBitmapDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeSensorFaultEvent,
		},
	},
}

func init() { spec.Register(Definition) }
