// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package relativehumiditymeasurement is the generated definition of the Matter RelativeHumidityMeasurement cluster
// (0x0405, revision 5), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package relativehumiditymeasurement

import "github.com/SukramJ/go-fabric/cluster/spec"

// Cluster identity.
const (
	ClusterID uint32 = 0x0405
	Name             = "RelativeHumidityMeasurement"
	Revision  uint16 = 5
)

// Attribute ids.
const (
	AttrMeasuredValue    uint32 = 0x0000 // uint16, M, R V, X
	AttrMinMeasuredValue uint32 = 0x0001 // uint16, M, R V, X F
	AttrMaxMeasuredValue uint32 = 0x0002 // uint16, M, R V, X F
	AttrTolerance        uint32 = 0x0003 // uint16, O, R V, F
)

// Feature is a RelativeHumidityMeasurement FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// Definition is the RelativeHumidityMeasurement cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Attributes: []spec.Attribute{
		{
			ID: AttrMeasuredValue, Name: "MeasuredValue",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
			Constraint:  spec.Constraint{Text: "minMeasuredValue to maxMeasuredValue", Min: &spec.Bound{Ref: "minMeasuredValue"}, Max: &spec.Bound{Ref: "maxMeasuredValue"}},
		},
		{
			ID: AttrMinMeasuredValue, Name: "MinMeasuredValue",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Constraint:  spec.Constraint{Text: "max 9999", Max: &spec.Bound{Int: 9999}},
		},
		{
			ID: AttrMaxMeasuredValue, Name: "MaxMeasuredValue",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Fixed: true},
			Constraint:  spec.Constraint{Text: "minMeasuredValue + 1 to 10000", Min: &spec.Bound{Expr: "{\"type\":\"+\",\"lhs\":{\"type\":\"reference\",\"name\":\"minMeasuredValue\"},\"rhs\":1}"}, Max: &spec.Bound{Int: 10000}},
		},
		{
			ID: AttrTolerance, Name: "Tolerance",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "max 2048", Max: &spec.Bound{Int: 2048}},
		},
	},
}

func init() { spec.Register(Definition) }
