// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package electricalpowermeasurement is the generated definition of the Matter ElectricalPowerMeasurement cluster
// (0x0090, revision 3), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package electricalpowermeasurement

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0090
	Name             = "ElectricalPowerMeasurement"
	Revision  uint16 = 3
)

// Attribute ids.
const (
	AttrPowerMode                uint32 = 0x0000 // PowerModeEnum, M, R V
	AttrNumberOfMeasurementTypes uint32 = 0x0001 // uint8, M, R V, F
	AttrAccuracy                 uint32 = 0x0002 // list[MeasurementAccuracyStruct], M, R V, F
	AttrRanges                   uint32 = 0x0003 // list[MeasurementRangeStruct], O, R V, Q
	AttrVoltage                  uint32 = 0x0004 // voltage-mV, O, R V, X Q
	AttrActiveCurrent            uint32 = 0x0005 // amperage-mA, O, R V, X Q
	AttrReactiveCurrent          uint32 = 0x0006 // amperage-mA, [ALTC], R V, X Q
	AttrApparentCurrent          uint32 = 0x0007 // amperage-mA, [ALTC], R V, X Q
	AttrActivePower              uint32 = 0x0008 // power-mW, M, R V, X Q
	AttrReactivePower            uint32 = 0x0009 // power-mVAR, [ALTC], R V, X Q
	AttrApparentPower            uint32 = 0x000A // power-mVA, [ALTC], R V, X Q
	AttrRmsVoltage               uint32 = 0x000B // voltage-mV, [ALTC], R V, X Q
	AttrRmsCurrent               uint32 = 0x000C // amperage-mA, [ALTC], R V, X Q
	AttrRmsPower                 uint32 = 0x000D // power-mW, [ALTC], R V, X Q
	AttrFrequency                uint32 = 0x000E // int64, [ALTC], R V, X Q
	AttrHarmonicCurrents         uint32 = 0x000F // list[HarmonicMeasurementStruct], HARM, R V, X Q
	AttrHarmonicPhases           uint32 = 0x0010 // list[HarmonicMeasurementStruct], PWRQ, R V, X Q
	AttrPowerFactor              uint32 = 0x0011 // int64, [ALTC], R V, X Q
	AttrNeutralCurrent           uint32 = 0x0012 // amperage-mA, [POLY], R V, X Q
)

// Event ids.
const (
	EventMeasurementPeriodRanges uint32 = 0x00 // info, Ranges
)

// Feature is a ElectricalPowerMeasurement FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// FeatureMap bits.
const (
	FeatureDirectCurrent      Feature = 1 << 0 // DIRC, O.a+
	FeatureAlternatingCurrent Feature = 1 << 1 // ALTC, O.a+
	FeaturePolyphasePower     Feature = 1 << 2 // POLY, [ALTC]
	FeatureHarmonics          Feature = 1 << 3 // HARM, [ALTC]
	FeaturePowerQuality       Feature = 1 << 4 // PWRQ, [ALTC]
)

// HarmonicMeasurementStruct is the HarmonicMeasurementStruct struct.
type HarmonicMeasurementStruct struct {
	Order       uint8                // 0: uint8, M, min 1
	Measurement spec.Nullable[int64] // 1: int64, M, -2^62 to 2^62, X
}

// EncodeTLV implements spec.Encodable.
func (v HarmonicMeasurementStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint8](enc, tlv.ContextTag(0), v.Order)
	spec.PutNullable(spec.PutInt[int64])(enc, tlv.ContextTag(1), v.Measurement)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *HarmonicMeasurementStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "HarmonicMeasurementStruct",
		spec.Bind(0, "Order", true, &v.Order, spec.DecodeUintIn[uint8](8, 1, 255)),
		spec.Bind(1, "Measurement", true, &v.Measurement, spec.DecodeNullable(spec.DecodeInt[int64](64))),
	)
}

// HarmonicMeasurementStructDef describes HarmonicMeasurementStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var HarmonicMeasurementStructDef = &spec.Struct{Name: "HarmonicMeasurementStruct", Fields: []spec.Field{
	{ID: 0, Name: "Order", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}}},
	{ID: 1, Name: "Measurement", Type: spec.Type{Name: "int64", Kind: spec.KindInt, Bits: 64}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Quality: spec.Quality{Nullable: true}, Constraint: spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}}},
}}

// MeasurementRangeStruct is the MeasurementRangeStruct struct.
type MeasurementRangeStruct struct {
	MeasurementType MeasurementTypeEnum // 0: MeasurementTypeEnum, M
	Min             int64               // 1: int64, M, -2^62 to 2^62
	Max             int64               // 2: int64, M, -2^62 to 2^62
	StartTimestamp  *uint32             // 3: epoch-s, EndTimestamp
	EndTimestamp    *uint32             // 4: epoch-s, desc, min startTimestamp + 1
	MinTimestamp    *uint32             // 5: epoch-s, EndTimestamp
	MaxTimestamp    *uint32             // 6: epoch-s, EndTimestamp, min minTimestamp + 1
	StartSystime    *uint64             // 7: systime-ms, EndSystime
	EndSystime      *uint64             // 8: systime-ms, desc, min startSystime + 1
	MinSystime      *uint64             // 9: systime-ms, EndSystime
	MaxSystime      *uint64             // 10: systime-ms, EndSystime, min minSystime + 1
}

// EncodeTLV implements spec.Encodable.
func (v MeasurementRangeStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[MeasurementTypeEnum](enc, tlv.ContextTag(0), v.MeasurementType)
	spec.PutInt[int64](enc, tlv.ContextTag(1), v.Min)
	spec.PutInt[int64](enc, tlv.ContextTag(2), v.Max)
	spec.PutOptional(enc, tlv.ContextTag(3), v.StartTimestamp, spec.PutUint[uint32])
	spec.PutOptional(enc, tlv.ContextTag(4), v.EndTimestamp, spec.PutUint[uint32])
	spec.PutOptional(enc, tlv.ContextTag(5), v.MinTimestamp, spec.PutUint[uint32])
	spec.PutOptional(enc, tlv.ContextTag(6), v.MaxTimestamp, spec.PutUint[uint32])
	spec.PutOptional(enc, tlv.ContextTag(7), v.StartSystime, spec.PutUint[uint64])
	spec.PutOptional(enc, tlv.ContextTag(8), v.EndSystime, spec.PutUint[uint64])
	spec.PutOptional(enc, tlv.ContextTag(9), v.MinSystime, spec.PutUint[uint64])
	spec.PutOptional(enc, tlv.ContextTag(10), v.MaxSystime, spec.PutUint[uint64])
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *MeasurementRangeStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "MeasurementRangeStruct",
		spec.Bind(0, "MeasurementType", true, &v.MeasurementType, spec.DecodeUint[MeasurementTypeEnum](16)),
		spec.Bind(1, "Min", true, &v.Min, spec.DecodeInt[int64](64)),
		spec.Bind(2, "Max", true, &v.Max, spec.DecodeInt[int64](64)),
		spec.Bind(3, "StartTimestamp", false, &v.StartTimestamp, spec.DecodeOptional(spec.DecodeUint[uint32](32))),
		spec.Bind(4, "EndTimestamp", false, &v.EndTimestamp, spec.DecodeOptional(spec.DecodeUint[uint32](32))),
		spec.Bind(5, "MinTimestamp", false, &v.MinTimestamp, spec.DecodeOptional(spec.DecodeUint[uint32](32))),
		spec.Bind(6, "MaxTimestamp", false, &v.MaxTimestamp, spec.DecodeOptional(spec.DecodeUint[uint32](32))),
		spec.Bind(7, "StartSystime", false, &v.StartSystime, spec.DecodeOptional(spec.DecodeUint[uint64](64))),
		spec.Bind(8, "EndSystime", false, &v.EndSystime, spec.DecodeOptional(spec.DecodeUint[uint64](64))),
		spec.Bind(9, "MinSystime", false, &v.MinSystime, spec.DecodeOptional(spec.DecodeUint[uint64](64))),
		spec.Bind(10, "MaxSystime", false, &v.MaxSystime, spec.DecodeOptional(spec.DecodeUint[uint64](64))),
	)
}

// MeasurementRangeStructDef describes MeasurementRangeStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var MeasurementRangeStructDef = &spec.Struct{Name: "MeasurementRangeStruct", Fields: []spec.Field{
	{ID: 0, Name: "MeasurementType", Type: spec.Type{Name: "MeasurementTypeEnum", Kind: spec.KindEnum, Bits: 16, Enum: MeasurementTypeEnumDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{ID: 1, Name: "Min", Type: spec.Type{Name: "int64", Kind: spec.KindInt, Bits: 64}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}}},
	{ID: 2, Name: "Max", Type: spec.Type{Name: "int64", Kind: spec.KindInt, Bits: 64}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}}},
	{ID: 3, Name: "StartTimestamp", Type: spec.Type{Name: "epoch-s", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "EndTimestamp", Op: spec.ConfName, Name: "EndTimestamp"}},
	{ID: 4, Name: "EndTimestamp", Type: spec.Type{Name: "epoch-s", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "desc", Op: spec.ConfDesc}, Constraint: spec.Constraint{Text: "min startTimestamp + 1", Min: &spec.Bound{Expr: "{\"type\":\"+\",\"lhs\":{\"type\":\"reference\",\"name\":\"startTimestamp\"},\"rhs\":1}"}}},
	{ID: 5, Name: "MinTimestamp", Type: spec.Type{Name: "epoch-s", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "EndTimestamp", Op: spec.ConfName, Name: "EndTimestamp"}},
	{ID: 6, Name: "MaxTimestamp", Type: spec.Type{Name: "epoch-s", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "EndTimestamp", Op: spec.ConfName, Name: "EndTimestamp"}, Constraint: spec.Constraint{Text: "min minTimestamp + 1", Min: &spec.Bound{Expr: "{\"type\":\"+\",\"lhs\":{\"type\":\"reference\",\"name\":\"minTimestamp\"},\"rhs\":1}"}}},
	{ID: 7, Name: "StartSystime", Type: spec.Type{Name: "systime-ms", Kind: spec.KindUint, Bits: 64}, Conformance: spec.Conformance{Text: "EndSystime", Op: spec.ConfName, Name: "EndSystime"}},
	{ID: 8, Name: "EndSystime", Type: spec.Type{Name: "systime-ms", Kind: spec.KindUint, Bits: 64}, Conformance: spec.Conformance{Text: "desc", Op: spec.ConfDesc}, Constraint: spec.Constraint{Text: "min startSystime + 1", Min: &spec.Bound{Expr: "{\"type\":\"+\",\"lhs\":{\"type\":\"reference\",\"name\":\"startSystime\"},\"rhs\":1}"}}},
	{ID: 9, Name: "MinSystime", Type: spec.Type{Name: "systime-ms", Kind: spec.KindUint, Bits: 64}, Conformance: spec.Conformance{Text: "EndSystime", Op: spec.ConfName, Name: "EndSystime"}},
	{ID: 10, Name: "MaxSystime", Type: spec.Type{Name: "systime-ms", Kind: spec.KindUint, Bits: 64}, Conformance: spec.Conformance{Text: "EndSystime", Op: spec.ConfName, Name: "EndSystime"}, Constraint: spec.Constraint{Text: "min minSystime + 1", Min: &spec.Bound{Expr: "{\"type\":\"+\",\"lhs\":{\"type\":\"reference\",\"name\":\"minSystime\"},\"rhs\":1}"}}},
}}

// MeasurementTypeEnum is the MeasurementTypeEnum enum16.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type MeasurementTypeEnum uint16

// MeasurementTypeEnum values.
const (
	MeasurementTypeUnspecified      MeasurementTypeEnum = 0  // M
	MeasurementTypeVoltage          MeasurementTypeEnum = 1  // M
	MeasurementTypeActiveCurrent    MeasurementTypeEnum = 2  // M
	MeasurementTypeReactiveCurrent  MeasurementTypeEnum = 3  // M
	MeasurementTypeApparentCurrent  MeasurementTypeEnum = 4  // M
	MeasurementTypeActivePower      MeasurementTypeEnum = 5  // M
	MeasurementTypeReactivePower    MeasurementTypeEnum = 6  // M
	MeasurementTypeApparentPower    MeasurementTypeEnum = 7  // M
	MeasurementTypeRmsVoltage       MeasurementTypeEnum = 8  // M
	MeasurementTypeRmsCurrent       MeasurementTypeEnum = 9  // M
	MeasurementTypeRmsPower         MeasurementTypeEnum = 10 // M
	MeasurementTypeFrequency        MeasurementTypeEnum = 11 // M
	MeasurementTypePowerFactor      MeasurementTypeEnum = 12 // M
	MeasurementTypeNeutralCurrent   MeasurementTypeEnum = 13 // M
	MeasurementTypeElectricalEnergy MeasurementTypeEnum = 14 // M
	MeasurementTypeReactiveEnergy   MeasurementTypeEnum = 15 // M
	MeasurementTypeApparentEnergy   MeasurementTypeEnum = 16 // M
)

// MeasurementTypeEnumDef describes MeasurementTypeEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var MeasurementTypeEnumDef = &spec.Enum{Name: "MeasurementTypeEnum", Bits: 16, Values: []spec.EnumValue{
	{Value: 0, Name: "Unspecified", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Voltage", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "ActiveCurrent", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 3, Name: "ReactiveCurrent", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 4, Name: "ApparentCurrent", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 5, Name: "ActivePower", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 6, Name: "ReactivePower", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 7, Name: "ApparentPower", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 8, Name: "RmsVoltage", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 9, Name: "RmsCurrent", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 10, Name: "RmsPower", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 11, Name: "Frequency", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 12, Name: "PowerFactor", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 13, Name: "NeutralCurrent", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 14, Name: "ElectricalEnergy", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 15, Name: "ReactiveEnergy", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 16, Name: "ApparentEnergy", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// PowerModeEnum is the PowerModeEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type PowerModeEnum uint8

// PowerModeEnum values.
const (
	PowerModeUnknown PowerModeEnum = 0 // M
	PowerModeDc      PowerModeEnum = 1 // M
	PowerModeAc      PowerModeEnum = 2 // M
)

// PowerModeEnumDef describes PowerModeEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var PowerModeEnumDef = &spec.Enum{Name: "PowerModeEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Unknown", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Dc", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "Ac", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// MeasurementAccuracyStruct is the MeasurementAccuracyStruct struct.
type MeasurementAccuracyStruct struct {
	MeasurementType  MeasurementTypeEnum              // 0: MeasurementTypeEnum, M
	Measured         bool                             // 1: bool, M
	MinMeasuredValue int64                            // 2: int64, M, -2^62 to 2^62
	MaxMeasuredValue int64                            // 3: int64, M, -2^62 to 2^62
	AccuracyRanges   []MeasurementAccuracyRangeStruct // 4: list[MeasurementAccuracyRangeStruct], M, min 1
}

// EncodeTLV implements spec.Encodable.
func (v MeasurementAccuracyStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[MeasurementTypeEnum](enc, tlv.ContextTag(0), v.MeasurementType)
	spec.PutBool(enc, tlv.ContextTag(1), v.Measured)
	spec.PutInt[int64](enc, tlv.ContextTag(2), v.MinMeasuredValue)
	spec.PutInt[int64](enc, tlv.ContextTag(3), v.MaxMeasuredValue)
	spec.PutList(spec.PutStruct[MeasurementAccuracyRangeStruct])(enc, tlv.ContextTag(4), v.AccuracyRanges)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *MeasurementAccuracyStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "MeasurementAccuracyStruct",
		spec.Bind(0, "MeasurementType", true, &v.MeasurementType, spec.DecodeUint[MeasurementTypeEnum](16)),
		spec.Bind(1, "Measured", true, &v.Measured, spec.DecodeBool),
		spec.Bind(2, "MinMeasuredValue", true, &v.MinMeasuredValue, spec.DecodeInt[int64](64)),
		spec.Bind(3, "MaxMeasuredValue", true, &v.MaxMeasuredValue, spec.DecodeInt[int64](64)),
		spec.Bind(4, "AccuracyRanges", true, &v.AccuracyRanges, spec.DecodeListIn(spec.DecodeStruct[MeasurementAccuracyRangeStruct], 1, 2147483647)),
	)
}

// MeasurementAccuracyStructDef describes MeasurementAccuracyStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var MeasurementAccuracyStructDef = &spec.Struct{Name: "MeasurementAccuracyStruct", Fields: []spec.Field{
	{ID: 0, Name: "MeasurementType", Type: spec.Type{Name: "MeasurementTypeEnum", Kind: spec.KindEnum, Bits: 16, Enum: MeasurementTypeEnumDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{ID: 1, Name: "Measured", Type: spec.Type{Name: "bool", Kind: spec.KindBool}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{ID: 2, Name: "MinMeasuredValue", Type: spec.Type{Name: "int64", Kind: spec.KindInt, Bits: 64}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}}},
	{ID: 3, Name: "MaxMeasuredValue", Type: spec.Type{Name: "int64", Kind: spec.KindInt, Bits: 64}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}}},
	{ID: 4, Name: "AccuracyRanges", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "MeasurementAccuracyRangeStruct", Kind: spec.KindStruct, Struct: MeasurementAccuracyRangeStructDef}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "min 1", Min: &spec.Bound{Int: 1}}},
}}

// MeasurementAccuracyRangeStruct is the MeasurementAccuracyRangeStruct struct.
type MeasurementAccuracyRangeStruct struct {
	RangeMin       int64   // 0: int64, M, -2^62 to 2^62
	RangeMax       int64   // 1: int64, M, -2^62 to 2^62
	PercentMax     *uint16 // 2: percent100ths, O.a+, max 10000
	PercentMin     *uint16 // 3: percent100ths, [PercentMax], max percentTypical
	PercentTypical *uint16 // 4: percent100ths, [PercentMin], percentMin to percentMax
	FixedMax       *uint64 // 5: uint64, O.a+, max (2^62) - 1
	FixedMin       *uint64 // 6: uint64, [FixedMax], max fixedMax
	FixedTypical   *uint64 // 7: uint64, [FixedMin], fixedMin to fixedMax
}

// EncodeTLV implements spec.Encodable.
func (v MeasurementAccuracyRangeStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutInt[int64](enc, tlv.ContextTag(0), v.RangeMin)
	spec.PutInt[int64](enc, tlv.ContextTag(1), v.RangeMax)
	spec.PutOptional(enc, tlv.ContextTag(2), v.PercentMax, spec.PutUint[uint16])
	spec.PutOptional(enc, tlv.ContextTag(3), v.PercentMin, spec.PutUint[uint16])
	spec.PutOptional(enc, tlv.ContextTag(4), v.PercentTypical, spec.PutUint[uint16])
	spec.PutOptional(enc, tlv.ContextTag(5), v.FixedMax, spec.PutUint[uint64])
	spec.PutOptional(enc, tlv.ContextTag(6), v.FixedMin, spec.PutUint[uint64])
	spec.PutOptional(enc, tlv.ContextTag(7), v.FixedTypical, spec.PutUint[uint64])
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *MeasurementAccuracyRangeStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "MeasurementAccuracyRangeStruct",
		spec.Bind(0, "RangeMin", true, &v.RangeMin, spec.DecodeInt[int64](64)),
		spec.Bind(1, "RangeMax", true, &v.RangeMax, spec.DecodeInt[int64](64)),
		spec.Bind(2, "PercentMax", false, &v.PercentMax, spec.DecodeOptional(spec.DecodeUintIn[uint16](16, 0, 10000))),
		spec.Bind(3, "PercentMin", false, &v.PercentMin, spec.DecodeOptional(spec.DecodeUintIn[uint16](16, 0, 10000))),
		spec.Bind(4, "PercentTypical", false, &v.PercentTypical, spec.DecodeOptional(spec.DecodeUintIn[uint16](16, 0, 10000))),
		spec.Bind(5, "FixedMax", false, &v.FixedMax, spec.DecodeOptional(spec.DecodeUint[uint64](64))),
		spec.Bind(6, "FixedMin", false, &v.FixedMin, spec.DecodeOptional(spec.DecodeUint[uint64](64))),
		spec.Bind(7, "FixedTypical", false, &v.FixedTypical, spec.DecodeOptional(spec.DecodeUint[uint64](64))),
	)
}

// MeasurementAccuracyRangeStructDef describes MeasurementAccuracyRangeStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var MeasurementAccuracyRangeStructDef = &spec.Struct{Name: "MeasurementAccuracyRangeStruct", Fields: []spec.Field{
	{ID: 0, Name: "RangeMin", Type: spec.Type{Name: "int64", Kind: spec.KindInt, Bits: 64}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}}},
	{ID: 1, Name: "RangeMax", Type: spec.Type{Name: "int64", Kind: spec.KindInt, Bits: 64}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}}},
	{ID: 2, Name: "PercentMax", Type: spec.Type{Name: "percent100ths", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}, Constraint: spec.Constraint{Text: "max 10000", Max: &spec.Bound{Int: 10000}}},
	{ID: 3, Name: "PercentMin", Type: spec.Type{Name: "percent100ths", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "[PercentMax]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PercentMax"}}}, Constraint: spec.Constraint{Text: "max percentTypical", Max: &spec.Bound{Ref: "percentTypical"}}},
	{ID: 4, Name: "PercentTypical", Type: spec.Type{Name: "percent100ths", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "[PercentMin]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PercentMin"}}}, Constraint: spec.Constraint{Text: "percentMin to percentMax", Min: &spec.Bound{Ref: "percentMin"}, Max: &spec.Bound{Ref: "percentMax"}}},
	{ID: 5, Name: "FixedMax", Type: spec.Type{Name: "uint64", Kind: spec.KindUint, Bits: 64}, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}, Constraint: spec.Constraint{Text: "max (2^62) - 1", Max: &spec.Bound{Expr: "{\"type\":\"-\",\"lhs\":{\"type\":\"^\",\"lhs\":2,\"rhs\":62},\"rhs\":1}"}}},
	{ID: 6, Name: "FixedMin", Type: spec.Type{Name: "uint64", Kind: spec.KindUint, Bits: 64}, Conformance: spec.Conformance{Text: "[FixedMax]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "FixedMax"}}}, Constraint: spec.Constraint{Text: "max fixedMax", Max: &spec.Bound{Ref: "fixedMax"}}},
	{ID: 7, Name: "FixedTypical", Type: spec.Type{Name: "uint64", Kind: spec.KindUint, Bits: 64}, Conformance: spec.Conformance{Text: "[FixedMin]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "FixedMin"}}}, Constraint: spec.Constraint{Text: "fixedMin to fixedMax", Min: &spec.Bound{Ref: "fixedMin"}, Max: &spec.Bound{Ref: "fixedMax"}}},
}}

// MeasurementPeriodRangesEvent is the MeasurementPeriodRanges event payload.
type MeasurementPeriodRangesEvent struct {
	Ranges []MeasurementRangeStruct // 0: list[MeasurementRangeStruct], M, 1 to numberOfMeasurementTypes
}

// EncodeTLV implements spec.Encodable.
func (v MeasurementPeriodRangesEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutList(spec.PutStruct[MeasurementRangeStruct])(enc, tlv.ContextTag(0), v.Ranges)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *MeasurementPeriodRangesEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "MeasurementPeriodRanges",
		spec.Bind(0, "Ranges", true, &v.Ranges, spec.DecodeListIn(spec.DecodeStruct[MeasurementRangeStruct], 1, 2147483647)),
	)
}

func decodeMeasurementPeriodRangesEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[MeasurementPeriodRangesEvent](n)
}

func decodeAttrAccuracy(n spec.Node) (any, error) {
	v, err := spec.DecodeListIn(spec.DecodeStruct[MeasurementAccuracyStruct], 1, 2147483647)(n)
	return spec.List[MeasurementAccuracyStruct](v), err
}

func decodeAttrRanges(n spec.Node) (any, error) {
	v, err := spec.DecodeListIn(spec.DecodeStruct[MeasurementRangeStruct], 0, 2147483647)(n)
	return spec.List[MeasurementRangeStruct](v), err
}

// Definition is the ElectricalPowerMeasurement cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Features: []spec.Feature{
		{Name: "DIRC", Title: "DirectCurrent", Bit: 0, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "ALTC", Title: "AlternatingCurrent", Bit: 1, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "POLY", Title: "PolyphasePower", Bit: 2, Conformance: spec.Conformance{Text: "[ALTC]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "ALTC"}}}},
		{Name: "HARM", Title: "Harmonics", Bit: 3, Conformance: spec.Conformance{Text: "[ALTC]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "ALTC"}}}},
		{Name: "PWRQ", Title: "PowerQuality", Bit: 4, Conformance: spec.Conformance{Text: "[ALTC]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "ALTC"}}}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrPowerMode, Name: "PowerMode",
			Type:        spec.Type{Name: "PowerModeEnum", Kind: spec.KindEnum, Bits: 8, Enum: PowerModeEnumDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
		},
		{
			ID: AttrNumberOfMeasurementTypes, Name: "NumberOfMeasurementTypes",
			Type:        spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "max 32", Max: &spec.Bound{Int: 32}},
		},
		{
			ID: AttrAccuracy, Name: "Accuracy",
			Type:        spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "MeasurementAccuracyStruct", Kind: spec.KindStruct, Struct: MeasurementAccuracyStructDef}}},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "1 to numberOfMeasurementTypes", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Ref: "numberOfMeasurementTypes"}},
			Decode:      decodeAttrAccuracy,
		},
		{
			ID: AttrRanges, Name: "Ranges",
			Type:        spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "MeasurementRangeStruct", Kind: spec.KindStruct, Struct: MeasurementRangeStructDef}}},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Quieter: true},
			Constraint:  spec.Constraint{Text: "0 to numberOfMeasurementTypes", Min: &spec.Bound{Int: 0}, Max: &spec.Bound{Ref: "numberOfMeasurementTypes"}},
			Decode:      decodeAttrRanges,
		},
		{
			ID: AttrVoltage, Name: "Voltage",
			Type:        spec.Type{Name: "voltage-mV", Kind: spec.KindInt, Bits: 64},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrActiveCurrent, Name: "ActiveCurrent",
			Type:        spec.Type{Name: "amperage-mA", Kind: spec.KindInt, Bits: 64},
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrReactiveCurrent, Name: "ReactiveCurrent",
			Type:        spec.Type{Name: "amperage-mA", Kind: spec.KindInt, Bits: 64},
			Conformance: spec.Conformance{Text: "[ALTC]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "ALTC"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrApparentCurrent, Name: "ApparentCurrent",
			Type:        spec.Type{Name: "amperage-mA", Kind: spec.KindInt, Bits: 64},
			Conformance: spec.Conformance{Text: "[ALTC]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "ALTC"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrActivePower, Name: "ActivePower",
			Type:        spec.Type{Name: "power-mW", Kind: spec.KindInt, Bits: 64},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}},
		},
		{
			ID: AttrReactivePower, Name: "ReactivePower",
			Type:        spec.Type{Name: "power-mVAR", Kind: spec.KindInt, Bits: 64},
			Conformance: spec.Conformance{Text: "[ALTC]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "ALTC"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrApparentPower, Name: "ApparentPower",
			Type:        spec.Type{Name: "power-mVA", Kind: spec.KindInt, Bits: 64},
			Conformance: spec.Conformance{Text: "[ALTC]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "ALTC"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrRmsVoltage, Name: "RmsVoltage",
			Type:        spec.Type{Name: "voltage-mV", Kind: spec.KindInt, Bits: 64},
			Conformance: spec.Conformance{Text: "[ALTC]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "ALTC"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrRmsCurrent, Name: "RmsCurrent",
			Type:        spec.Type{Name: "amperage-mA", Kind: spec.KindInt, Bits: 64},
			Conformance: spec.Conformance{Text: "[ALTC]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "ALTC"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrRmsPower, Name: "RmsPower",
			Type:        spec.Type{Name: "power-mW", Kind: spec.KindInt, Bits: 64},
			Conformance: spec.Conformance{Text: "[ALTC]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "ALTC"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrFrequency, Name: "Frequency",
			Type:        spec.Type{Name: "int64", Kind: spec.KindInt, Bits: 64},
			Conformance: spec.Conformance{Text: "[ALTC]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "ALTC"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "0 to 1000000", Min: &spec.Bound{Int: 0}, Max: &spec.Bound{Int: 1000000}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrHarmonicCurrents, Name: "HarmonicCurrents",
			Type:        spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "HarmonicMeasurementStruct", Kind: spec.KindStruct, Struct: HarmonicMeasurementStructDef}}},
			Conformance: spec.Conformance{Text: "HARM", Op: spec.ConfName, Name: "HARM"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "max 25", Max: &spec.Bound{Int: 25}},
		},
		{
			ID: AttrHarmonicPhases, Name: "HarmonicPhases",
			Type:        spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "HarmonicMeasurementStruct", Kind: spec.KindStruct, Struct: HarmonicMeasurementStructDef}}},
			Conformance: spec.Conformance{Text: "PWRQ", Op: spec.ConfName, Name: "PWRQ"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "max 25", Max: &spec.Bound{Int: 25}},
		},
		{
			ID: AttrPowerFactor, Name: "PowerFactor",
			Type:        spec.Type{Name: "int64", Kind: spec.KindInt, Bits: 64},
			Conformance: spec.Conformance{Text: "[ALTC]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "ALTC"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "-10000 to 10000", Min: &spec.Bound{Int: -10000}, Max: &spec.Bound{Int: 10000}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrNeutralCurrent, Name: "NeutralCurrent",
			Type:        spec.Type{Name: "amperage-mA", Kind: spec.KindInt, Bits: 64},
			Conformance: spec.Conformance{Text: "[POLY]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "POLY"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "-2^62 to 2^62", Min: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":-2,\"rhs\":62}"}, Max: &spec.Bound{Expr: "{\"type\":\"^\",\"lhs\":2,\"rhs\":62}"}},
			Default:     spec.NullDefault{},
		},
	},
	Events: []spec.Event{
		{
			ID: EventMeasurementPeriodRanges, Name: "MeasurementPeriodRanges", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "Ranges", Op: spec.ConfName, Name: "Ranges"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "Ranges", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "MeasurementRangeStruct", Kind: spec.KindStruct, Struct: MeasurementRangeStructDef}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "1 to numberOfMeasurementTypes", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Ref: "numberOfMeasurementTypes"}}},
			},
			Decode: decodeMeasurementPeriodRangesEvent,
		},
	},
}

func init() { spec.Register(Definition) }
