// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package electricalpowermeasurement

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, HarmonicMeasurementStruct{Order: uint8(1), Measurement: spec.ValueOf(int64(1))}, spec.DecodeStruct[HarmonicMeasurementStruct])
	spectest.RoundTrip(t, MeasurementRangeStruct{MeasurementType: MeasurementTypeEnum(0), Min: int64(1), Max: int64(1), StartTimestamp: spectest.Ptr(uint32(1)), EndTimestamp: spectest.Ptr(uint32(1)), MinTimestamp: spectest.Ptr(uint32(1)), MaxTimestamp: spectest.Ptr(uint32(1)), StartSystime: spectest.Ptr(uint64(1)), EndSystime: spectest.Ptr(uint64(1)), MinSystime: spectest.Ptr(uint64(1)), MaxSystime: spectest.Ptr(uint64(1))}, spec.DecodeStruct[MeasurementRangeStruct])
	spectest.RoundTrip(t, MeasurementAccuracyStruct{MeasurementType: MeasurementTypeEnum(0), Measured: true, MinMeasuredValue: int64(1), MaxMeasuredValue: int64(1), AccuracyRanges: []MeasurementAccuracyRangeStruct{MeasurementAccuracyRangeStruct{RangeMin: int64(1), RangeMax: int64(1), PercentMax: spectest.Ptr(uint16(1)), PercentMin: spectest.Ptr(uint16(1)), PercentTypical: spectest.Ptr(uint16(1)), FixedMax: spectest.Ptr(uint64(1)), FixedMin: spectest.Ptr(uint64(1)), FixedTypical: spectest.Ptr(uint64(1))}}}, spec.DecodeStruct[MeasurementAccuracyStruct])
	spectest.RoundTrip(t, MeasurementAccuracyRangeStruct{RangeMin: int64(1), RangeMax: int64(1), PercentMax: spectest.Ptr(uint16(1)), PercentMin: spectest.Ptr(uint16(1)), PercentTypical: spectest.Ptr(uint16(1)), FixedMax: spectest.Ptr(uint64(1)), FixedMin: spectest.Ptr(uint64(1)), FixedTypical: spectest.Ptr(uint64(1))}, spec.DecodeStruct[MeasurementAccuracyRangeStruct])
	spectest.RoundTripEvent(t, Definition, EventMeasurementPeriodRanges, MeasurementPeriodRangesEvent{Ranges: []MeasurementRangeStruct{MeasurementRangeStruct{MeasurementType: MeasurementTypeEnum(0), Min: int64(1), Max: int64(1), StartTimestamp: spectest.Ptr(uint32(1)), EndTimestamp: spectest.Ptr(uint32(1)), MinTimestamp: spectest.Ptr(uint32(1)), MaxTimestamp: spectest.Ptr(uint32(1)), StartSystime: spectest.Ptr(uint64(1)), EndSystime: spectest.Ptr(uint64(1)), MinSystime: spectest.Ptr(uint64(1)), MaxSystime: spectest.Ptr(uint64(1))}}})
	spectest.RoundTripAttribute(t, Definition, AttrAccuracy, spec.List[MeasurementAccuracyStruct]([]MeasurementAccuracyStruct{MeasurementAccuracyStruct{MeasurementType: MeasurementTypeEnum(0), Measured: true, MinMeasuredValue: int64(1), MaxMeasuredValue: int64(1), AccuracyRanges: []MeasurementAccuracyRangeStruct{MeasurementAccuracyRangeStruct{RangeMin: int64(1), RangeMax: int64(1), PercentMax: spectest.Ptr(uint16(1)), PercentMin: spectest.Ptr(uint16(1)), PercentTypical: spectest.Ptr(uint16(1)), FixedMax: spectest.Ptr(uint64(1)), FixedMin: spectest.Ptr(uint64(1)), FixedTypical: spectest.Ptr(uint64(1))}}}}))
	spectest.RoundTripAttribute(t, Definition, AttrRanges, spec.List[MeasurementRangeStruct]([]MeasurementRangeStruct{MeasurementRangeStruct{MeasurementType: MeasurementTypeEnum(0), Min: int64(1), Max: int64(1), StartTimestamp: spectest.Ptr(uint32(1)), EndTimestamp: spectest.Ptr(uint32(1)), MinTimestamp: spectest.Ptr(uint32(1)), MaxTimestamp: spectest.Ptr(uint32(1)), StartSystime: spectest.Ptr(uint64(1)), EndSystime: spectest.Ptr(uint64(1)), MinSystime: spectest.Ptr(uint64(1)), MaxSystime: spectest.Ptr(uint64(1))}}))
}
