// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package closurecontrol

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, OverallCurrentStateStruct{Position: spectest.Ptr(spec.ValueOf(CurrentPositionEnum(0))), Latch: spectest.Ptr(spec.ValueOf(true)), Speed: spectest.Ptr(ThreeLevelAutoEnum(0)), SecureState: spec.ValueOf(true)}, spec.DecodeStruct[OverallCurrentStateStruct])
	spectest.RoundTrip(t, OverallTargetStateStruct{Position: spectest.Ptr(spec.ValueOf(TargetPositionEnum(0))), Latch: spectest.Ptr(spec.ValueOf(true)), Speed: spectest.Ptr(ThreeLevelAutoEnum(0))}, spec.DecodeStruct[OverallTargetStateStruct])
	spectest.RoundTripCommand(t, Definition, CmdStop, spec.Request, StopRequest{})
	spectest.RoundTripCommand(t, Definition, CmdMoveTo, spec.Request, MoveToRequest{Position: spectest.Ptr(TargetPositionEnum(0)), Latch: spectest.Ptr(true), Speed: spectest.Ptr(ThreeLevelAutoEnum(0))})
	spectest.RoundTripCommand(t, Definition, CmdCalibrate, spec.Request, CalibrateRequest{})
	spectest.RoundTripEvent(t, Definition, EventOperationalError, OperationalErrorEvent{ErrorState: []ClosureErrorEnum{ClosureErrorEnum(0)}})
	spectest.RoundTripEvent(t, Definition, EventMovementCompleted, MovementCompletedEvent{})
	spectest.RoundTripEvent(t, Definition, EventEngageStateChanged, EngageStateChangedEvent{EngageValue: true})
	spectest.RoundTripEvent(t, Definition, EventSecureStateChanged, SecureStateChangedEvent{SecureValue: true})
}
