// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package closurecontrol is the generated definition of the Matter ClosureControl cluster
// (0x0104, revision 1), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package closurecontrol

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0104
	Name             = "ClosureControl"
	Revision  uint16 = 1
)

// Attribute ids.
const (
	AttrCountdownTime       uint32 = 0x0000 // elapsed-s, [PS & !IS], R V, X Q
	AttrMainState           uint32 = 0x0001 // MainStateEnum, M, R V
	AttrCurrentErrorList    uint32 = 0x0002 // list[ClosureErrorEnum], M, R V
	AttrOverallCurrentState uint32 = 0x0003 // OverallCurrentStateStruct, M, R V, X
	AttrOverallTargetState  uint32 = 0x0004 // OverallTargetStateStruct, M, R V, X
	AttrLatchControlModes   uint32 = 0x0005 // LatchControlModesBitmap, LT, R V, F
)

// Command ids.
const (
	CmdStop      uint32 = 0x00 // request → status, !IS
	CmdMoveTo    uint32 = 0x01 // request → status, M
	CmdCalibrate uint32 = 0x02 // request → status, CL
)

// Event ids.
const (
	EventOperationalError   uint32 = 0x00 // critical, M
	EventMovementCompleted  uint32 = 0x01 // info, !IS
	EventEngageStateChanged uint32 = 0x02 // info, MO
	EventSecureStateChanged uint32 = 0x03 // info, M
)

// Feature is a ClosureControl FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// FeatureMap bits.
const (
	FeaturePositioning      Feature = 1 << 0 // PS, O.a+
	FeatureMotionLatching   Feature = 1 << 1 // LT, O.a+
	FeatureInstantaneous    Feature = 1 << 2 // IS, O
	FeatureSpeed            Feature = 1 << 3 // SP, [PS & !IS]
	FeatureVentilation      Feature = 1 << 4 // VT, [PS]
	FeaturePedestrian       Feature = 1 << 5 // PD, [PS]
	FeatureCalibration      Feature = 1 << 6 // CL, [PS]
	FeatureProtection       Feature = 1 << 7 // PT, O
	FeatureManuallyOperable Feature = 1 << 8 // MO, O
)

// ClosureErrorEnum is the ClosureErrorEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type ClosureErrorEnum uint8

// ClosureErrorEnum values.
const (
	ClosureErrorPhysicallyBlocked    ClosureErrorEnum = 0 // M
	ClosureErrorBlockedBySensor      ClosureErrorEnum = 1 // M
	ClosureErrorTemperatureLimited   ClosureErrorEnum = 2 // M
	ClosureErrorMaintenanceRequired  ClosureErrorEnum = 3 // M
	ClosureErrorInternalInterference ClosureErrorEnum = 4 // M
)

// ClosureErrorEnumDef describes ClosureErrorEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var ClosureErrorEnumDef = &spec.Enum{Name: "ClosureErrorEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "PhysicallyBlocked", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "BlockedBySensor", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "TemperatureLimited", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 3, Name: "MaintenanceRequired", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 4, Name: "InternalInterference", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// CurrentPositionEnum is the CurrentPositionEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type CurrentPositionEnum uint8

// CurrentPositionEnum values.
const (
	CurrentPositionFullyClosed          CurrentPositionEnum = 0 // M
	CurrentPositionFullyOpened          CurrentPositionEnum = 1 // M
	CurrentPositionPartiallyOpened      CurrentPositionEnum = 2 // M
	CurrentPositionOpenedForPedestrian  CurrentPositionEnum = 3 // PD
	CurrentPositionOpenedForVentilation CurrentPositionEnum = 4 // VT
	CurrentPositionOpenedAtSignature    CurrentPositionEnum = 5 // M
)

// CurrentPositionEnumDef describes CurrentPositionEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var CurrentPositionEnumDef = &spec.Enum{Name: "CurrentPositionEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "FullyClosed", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "FullyOpened", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "PartiallyOpened", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 3, Name: "OpenedForPedestrian", Conformance: spec.Conformance{Text: "PD", Op: spec.ConfName, Name: "PD"}},
	{Value: 4, Name: "OpenedForVentilation", Conformance: spec.Conformance{Text: "VT", Op: spec.ConfName, Name: "VT"}},
	{Value: 5, Name: "OpenedAtSignature", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// LatchControlModesBitmap is the LatchControlModesBitmap map8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type LatchControlModesBitmap uint8

// LatchControlModesBitmap bits; a member wider than one bit is its mask.
const (
	LatchControlModesRemoteLatching   LatchControlModesBitmap = 1 << 0 // LT
	LatchControlModesRemoteUnlatching LatchControlModesBitmap = 1 << 1 // LT
)

// LatchControlModesBitmapDef describes LatchControlModesBitmap.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var LatchControlModesBitmapDef = &spec.Bitmap{Name: "LatchControlModesBitmap", Bits: 8, Members: []spec.BitmapMember{
	{Name: "RemoteLatching", Bit: 0, Width: 1, Conformance: spec.Conformance{Text: "LT", Op: spec.ConfName, Name: "LT"}},
	{Name: "RemoteUnlatching", Bit: 1, Width: 1, Conformance: spec.Conformance{Text: "LT", Op: spec.ConfName, Name: "LT"}},
}}

// MainStateEnum is the MainStateEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type MainStateEnum uint8

// MainStateEnum values.
const (
	MainStateStopped          MainStateEnum = 0 // M
	MainStateMoving           MainStateEnum = 1 // M
	MainStateWaitingForMotion MainStateEnum = 2 // M
	MainStateError            MainStateEnum = 3 // M
	MainStateCalibrating      MainStateEnum = 4 // CL
	MainStateProtected        MainStateEnum = 5 // PT
	MainStateDisengaged       MainStateEnum = 6 // MO
	MainStateSetupRequired    MainStateEnum = 7 // M
)

// MainStateEnumDef describes MainStateEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var MainStateEnumDef = &spec.Enum{Name: "MainStateEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Stopped", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Moving", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "WaitingForMotion", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 3, Name: "Error", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 4, Name: "Calibrating", Conformance: spec.Conformance{Text: "CL", Op: spec.ConfName, Name: "CL"}},
	{Value: 5, Name: "Protected", Conformance: spec.Conformance{Text: "PT", Op: spec.ConfName, Name: "PT"}},
	{Value: 6, Name: "Disengaged", Conformance: spec.Conformance{Text: "MO", Op: spec.ConfName, Name: "MO"}},
	{Value: 7, Name: "SetupRequired", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// OverallCurrentStateStruct is the OverallCurrentStateStruct struct.
type OverallCurrentStateStruct struct {
	Position    *spec.Nullable[CurrentPositionEnum] // 0: CurrentPositionEnum, PS, desc, X
	Latch       *spec.Nullable[bool]                // 1: bool, LT, desc, X
	Speed       *ThreeLevelAutoEnum                 // 2: ThreeLevelAutoEnum, SP, desc
	SecureState spec.Nullable[bool]                 // 3: bool, M, desc, X
}

// EncodeTLV implements spec.Encodable.
func (v OverallCurrentStateStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutOptional(enc, tlv.ContextTag(0), v.Position, spec.PutNullable(spec.PutUint[CurrentPositionEnum]))
	spec.PutOptional(enc, tlv.ContextTag(1), v.Latch, spec.PutNullable(spec.PutBool))
	spec.PutOptional(enc, tlv.ContextTag(2), v.Speed, spec.PutUint[ThreeLevelAutoEnum])
	spec.PutNullable(spec.PutBool)(enc, tlv.ContextTag(3), v.SecureState)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *OverallCurrentStateStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "OverallCurrentStateStruct",
		spec.Bind(0, "Position", false, &v.Position, spec.DecodeOptional(spec.DecodeNullable(spec.DecodeUint[CurrentPositionEnum](8)))),
		spec.Bind(1, "Latch", false, &v.Latch, spec.DecodeOptional(spec.DecodeNullable(spec.DecodeBool))),
		spec.Bind(2, "Speed", false, &v.Speed, spec.DecodeOptional(spec.DecodeUint[ThreeLevelAutoEnum](8))),
		spec.Bind(3, "SecureState", true, &v.SecureState, spec.DecodeNullable(spec.DecodeBool)),
	)
}

// OverallCurrentStateStructDef describes OverallCurrentStateStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var OverallCurrentStateStructDef = &spec.Struct{Name: "OverallCurrentStateStruct", Fields: []spec.Field{
	{ID: 0, Name: "Position", Type: spec.Type{Name: "CurrentPositionEnum", Kind: spec.KindEnum, Bits: 8, Enum: CurrentPositionEnumDef}, Conformance: spec.Conformance{Text: "PS", Op: spec.ConfName, Name: "PS"}, Quality: spec.Quality{Nullable: true}, Constraint: spec.Constraint{Text: "desc", Desc: true}, Default: spec.NullDefault{}},
	{ID: 1, Name: "Latch", Type: spec.Type{Name: "bool", Kind: spec.KindBool}, Conformance: spec.Conformance{Text: "LT", Op: spec.ConfName, Name: "LT"}, Quality: spec.Quality{Nullable: true}, Constraint: spec.Constraint{Text: "desc", Desc: true}, Default: spec.NullDefault{}},
	{ID: 2, Name: "Speed", Type: spec.Type{Name: "ThreeLevelAutoEnum", Kind: spec.KindEnum, Bits: 8, Enum: ThreeLevelAutoEnumDef}, Conformance: spec.Conformance{Text: "SP", Op: spec.ConfName, Name: "SP"}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
	{ID: 3, Name: "SecureState", Type: spec.Type{Name: "bool", Kind: spec.KindBool}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Quality: spec.Quality{Nullable: true}, Constraint: spec.Constraint{Text: "desc", Desc: true}, Default: spec.NullDefault{}},
}}

// ThreeLevelAutoEnum is the ThreeLevelAutoEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type ThreeLevelAutoEnum uint8

// ThreeLevelAutoEnum values.
const (
	ThreeLevelAutoAuto   ThreeLevelAutoEnum = 0 // M
	ThreeLevelAutoLow    ThreeLevelAutoEnum = 1 // M
	ThreeLevelAutoMedium ThreeLevelAutoEnum = 2 // M
	ThreeLevelAutoHigh   ThreeLevelAutoEnum = 3 // M
)

// ThreeLevelAutoEnumDef describes ThreeLevelAutoEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var ThreeLevelAutoEnumDef = &spec.Enum{Name: "ThreeLevelAutoEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Auto", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "Low", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "Medium", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 3, Name: "High", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// OverallTargetStateStruct is the OverallTargetStateStruct struct.
type OverallTargetStateStruct struct {
	Position *spec.Nullable[TargetPositionEnum] // 0: TargetPositionEnum, PS, X
	Latch    *spec.Nullable[bool]               // 1: bool, LT, X
	Speed    *ThreeLevelAutoEnum                // 2: ThreeLevelAutoEnum, SP
}

// EncodeTLV implements spec.Encodable.
func (v OverallTargetStateStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutOptional(enc, tlv.ContextTag(0), v.Position, spec.PutNullable(spec.PutUint[TargetPositionEnum]))
	spec.PutOptional(enc, tlv.ContextTag(1), v.Latch, spec.PutNullable(spec.PutBool))
	spec.PutOptional(enc, tlv.ContextTag(2), v.Speed, spec.PutUint[ThreeLevelAutoEnum])
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *OverallTargetStateStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "OverallTargetStateStruct",
		spec.Bind(0, "Position", false, &v.Position, spec.DecodeOptional(spec.DecodeNullable(spec.DecodeUint[TargetPositionEnum](8)))),
		spec.Bind(1, "Latch", false, &v.Latch, spec.DecodeOptional(spec.DecodeNullable(spec.DecodeBool))),
		spec.Bind(2, "Speed", false, &v.Speed, spec.DecodeOptional(spec.DecodeUint[ThreeLevelAutoEnum](8))),
	)
}

// OverallTargetStateStructDef describes OverallTargetStateStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var OverallTargetStateStructDef = &spec.Struct{Name: "OverallTargetStateStruct", Fields: []spec.Field{
	{ID: 0, Name: "Position", Type: spec.Type{Name: "TargetPositionEnum", Kind: spec.KindEnum, Bits: 8, Enum: TargetPositionEnumDef}, Conformance: spec.Conformance{Text: "PS", Op: spec.ConfName, Name: "PS"}, Quality: spec.Quality{Nullable: true}, Default: spec.NullDefault{}},
	{ID: 1, Name: "Latch", Type: spec.Type{Name: "bool", Kind: spec.KindBool}, Conformance: spec.Conformance{Text: "LT", Op: spec.ConfName, Name: "LT"}, Quality: spec.Quality{Nullable: true}, Default: spec.NullDefault{}},
	{ID: 2, Name: "Speed", Type: spec.Type{Name: "ThreeLevelAutoEnum", Kind: spec.KindEnum, Bits: 8, Enum: ThreeLevelAutoEnumDef}, Conformance: spec.Conformance{Text: "SP", Op: spec.ConfName, Name: "SP"}},
}}

// TargetPositionEnum is the TargetPositionEnum enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type TargetPositionEnum uint8

// TargetPositionEnum values.
const (
	TargetPositionMoveToFullyClosed         TargetPositionEnum = 0 // M
	TargetPositionMoveToFullyOpen           TargetPositionEnum = 1 // M
	TargetPositionMoveToPedestrianPosition  TargetPositionEnum = 2 // PD
	TargetPositionMoveToVentilationPosition TargetPositionEnum = 3 // VT
	TargetPositionMoveToSignaturePosition   TargetPositionEnum = 4 // M
)

// TargetPositionEnumDef describes TargetPositionEnum.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var TargetPositionEnumDef = &spec.Enum{Name: "TargetPositionEnum", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "MoveToFullyClosed", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 1, Name: "MoveToFullyOpen", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{Value: 2, Name: "MoveToPedestrianPosition", Conformance: spec.Conformance{Text: "PD", Op: spec.ConfName, Name: "PD"}},
	{Value: 3, Name: "MoveToVentilationPosition", Conformance: spec.Conformance{Text: "VT", Op: spec.ConfName, Name: "VT"}},
	{Value: 4, Name: "MoveToSignaturePosition", Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// StopRequest is the Stop command payload.
type StopRequest struct{}

// EncodeTLV implements spec.Encodable.
func (v StopRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *StopRequest) DecodeTLV(n spec.Node) error { return spec.DecodeFields(n, "Stop") }

// MoveToRequest is the MoveTo command payload.
type MoveToRequest struct {
	Position *TargetPositionEnum // 0: TargetPositionEnum, O.a+
	Latch    *bool               // 1: bool, O.a+
	Speed    *ThreeLevelAutoEnum // 2: ThreeLevelAutoEnum, O.a+
}

// EncodeTLV implements spec.Encodable.
func (v MoveToRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutOptional(enc, tlv.ContextTag(0), v.Position, spec.PutUint[TargetPositionEnum])
	spec.PutOptional(enc, tlv.ContextTag(1), v.Latch, spec.PutBool)
	spec.PutOptional(enc, tlv.ContextTag(2), v.Speed, spec.PutUint[ThreeLevelAutoEnum])
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *MoveToRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "MoveTo",
		spec.Bind(0, "Position", false, &v.Position, spec.DecodeOptional(spec.DecodeUint[TargetPositionEnum](8))),
		spec.Bind(1, "Latch", false, &v.Latch, spec.DecodeOptional(spec.DecodeBool)),
		spec.Bind(2, "Speed", false, &v.Speed, spec.DecodeOptional(spec.DecodeUint[ThreeLevelAutoEnum](8))),
	)
}

// CalibrateRequest is the Calibrate command payload.
type CalibrateRequest struct{}

// EncodeTLV implements spec.Encodable.
func (v CalibrateRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *CalibrateRequest) DecodeTLV(n spec.Node) error { return spec.DecodeFields(n, "Calibrate") }

// OperationalErrorEvent is the OperationalError event payload.
type OperationalErrorEvent struct {
	ErrorState []ClosureErrorEnum // 0: list[ClosureErrorEnum], M, 1 to 10[all]
}

// EncodeTLV implements spec.Encodable.
func (v OperationalErrorEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutList(spec.PutUint[ClosureErrorEnum])(enc, tlv.ContextTag(0), v.ErrorState)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *OperationalErrorEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "OperationalError",
		spec.Bind(0, "ErrorState", true, &v.ErrorState, spec.DecodeListIn(spec.DecodeUint[ClosureErrorEnum](8), 1, 10)),
	)
}

// MovementCompletedEvent is the MovementCompleted event payload.
type MovementCompletedEvent struct{}

// EncodeTLV implements spec.Encodable.
func (v MovementCompletedEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *MovementCompletedEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "MovementCompleted")
}

// EngageStateChangedEvent is the EngageStateChanged event payload.
type EngageStateChangedEvent struct {
	EngageValue bool // 0: bool, M
}

// EncodeTLV implements spec.Encodable.
func (v EngageStateChangedEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutBool(enc, tlv.ContextTag(0), v.EngageValue)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *EngageStateChangedEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "EngageStateChanged",
		spec.Bind(0, "EngageValue", true, &v.EngageValue, spec.DecodeBool),
	)
}

// SecureStateChangedEvent is the SecureStateChanged event payload.
type SecureStateChangedEvent struct {
	SecureValue bool // 0: bool, M
}

// EncodeTLV implements spec.Encodable.
func (v SecureStateChangedEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutBool(enc, tlv.ContextTag(0), v.SecureValue)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *SecureStateChangedEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "SecureStateChanged",
		spec.Bind(0, "SecureValue", true, &v.SecureValue, spec.DecodeBool),
	)
}

func decodeStopRequest(n spec.Node) (any, error) { return spec.DecodeStruct[StopRequest](n) }

func decodeMoveToRequest(n spec.Node) (any, error) { return spec.DecodeStruct[MoveToRequest](n) }

func decodeCalibrateRequest(n spec.Node) (any, error) { return spec.DecodeStruct[CalibrateRequest](n) }

func decodeOperationalErrorEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[OperationalErrorEvent](n)
}

func decodeMovementCompletedEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[MovementCompletedEvent](n)
}

func decodeEngageStateChangedEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[EngageStateChangedEvent](n)
}

func decodeSecureStateChangedEvent(n spec.Node) (any, error) {
	return spec.DecodeStruct[SecureStateChangedEvent](n)
}

// Definition is the ClosureControl cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Features: []spec.Feature{
		{Name: "PS", Title: "Positioning", Bit: 0, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "LT", Title: "MotionLatching", Bit: 1, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
		{Name: "IS", Title: "Instantaneous", Bit: 2, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
		{Name: "SP", Title: "Speed", Bit: 3, Conformance: spec.Conformance{Text: "[PS & !IS]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PS"}, {Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "IS"}}}}}}}},
		{Name: "VT", Title: "Ventilation", Bit: 4, Conformance: spec.Conformance{Text: "[PS]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PS"}}}},
		{Name: "PD", Title: "Pedestrian", Bit: 5, Conformance: spec.Conformance{Text: "[PS]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PS"}}}},
		{Name: "CL", Title: "Calibration", Bit: 6, Conformance: spec.Conformance{Text: "[PS]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PS"}}}},
		{Name: "PT", Title: "Protection", Bit: 7, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
		{Name: "MO", Title: "ManuallyOperable", Bit: 8, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrCountdownTime, Name: "CountdownTime",
			Type:        spec.Type{Name: "elapsed-s", Kind: spec.KindUint, Bits: 32},
			Conformance: spec.Conformance{Text: "[PS & !IS]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfAnd, Args: []spec.Conformance{{Op: spec.ConfName, Name: "PS"}, {Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "IS"}}}}}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true, Quieter: true},
			Constraint:  spec.Constraint{Text: "max 259200", Max: &spec.Bound{Int: 259200}},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrMainState, Name: "MainState",
			Type:        spec.Type{Name: "MainStateEnum", Kind: spec.KindEnum, Bits: 8, Enum: MainStateEnumDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
		},
		{
			ID: AttrCurrentErrorList, Name: "CurrentErrorList",
			Type:        spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "ClosureErrorEnum", Kind: spec.KindEnum, Bits: 8, Enum: ClosureErrorEnumDef}}},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Constraint:  spec.Constraint{Text: "max 10[all]", Max: &spec.Bound{Int: 10}},
		},
		{
			ID: AttrOverallCurrentState, Name: "OverallCurrentState",
			Type:        spec.Type{Name: "OverallCurrentStateStruct", Kind: spec.KindStruct, Struct: OverallCurrentStateStructDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrOverallTargetState, Name: "OverallTargetState",
			Type:        spec.Type{Name: "OverallTargetStateStruct", Kind: spec.KindStruct, Struct: OverallTargetStateStructDef},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Nullable: true},
			Default:     spec.NullDefault{},
		},
		{
			ID: AttrLatchControlModes, Name: "LatchControlModes",
			Type:        spec.Type{Name: "LatchControlModesBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: LatchControlModesBitmapDef},
			Conformance: spec.Conformance{Text: "LT", Op: spec.ConfName, Name: "LT"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
		},
	},
	Commands: []spec.Command{
		{
			ID: CmdStop, Name: "Stop", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "!IS", Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "IS"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate},
			Decode:      decodeStopRequest,
		},
		{
			ID: CmdMoveTo, Name: "MoveTo", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate, Timed: true},
			Fields: []spec.Field{
				{ID: 0, Name: "Position", Type: spec.Type{Name: "TargetPositionEnum", Kind: spec.KindEnum, Bits: 8, Enum: TargetPositionEnumDef}, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
				{ID: 1, Name: "Latch", Type: spec.Type{Name: "bool", Kind: spec.KindBool}, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
				{ID: 2, Name: "Speed", Type: spec.Type{Name: "ThreeLevelAutoEnum", Kind: spec.KindEnum, Bits: 8, Enum: ThreeLevelAutoEnumDef}, Conformance: spec.Conformance{Text: "O.a+", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: true, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}, Default: float64(0)},
			},
			Decode: decodeMoveToRequest,
		},
		{
			ID: CmdCalibrate, Name: "Calibrate", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "CL", Op: spec.ConfName, Name: "CL"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage, Timed: true},
			Decode:      decodeCalibrateRequest,
		},
	},
	Events: []spec.Event{
		{
			ID: EventOperationalError, Name: "OperationalError", Priority: spec.PriorityCritical,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "ErrorState", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "ClosureErrorEnum", Kind: spec.KindEnum, Bits: 8, Enum: ClosureErrorEnumDef}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "1 to 10[all]", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 10}}},
			},
			Decode: decodeOperationalErrorEvent,
		},
		{
			ID: EventMovementCompleted, Name: "MovementCompleted", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "!IS", Op: spec.ConfNot, Args: []spec.Conformance{{Op: spec.ConfName, Name: "IS"}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Decode:      decodeMovementCompletedEvent,
		},
		{
			ID: EventEngageStateChanged, Name: "EngageStateChanged", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "MO", Op: spec.ConfName, Name: "MO"},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "EngageValue", Type: spec.Type{Name: "bool", Kind: spec.KindBool}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeEngageStateChangedEvent,
		},
		{
			ID: EventSecureStateChanged, Name: "SecureStateChanged", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "SecureValue", Type: spec.Type{Name: "bool", Kind: spec.KindBool}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeSecureStateChangedEvent,
		},
	},
}

func init() { spec.Register(Definition) }
