// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package scenesmanagement is the generated definition of the Matter ScenesManagement cluster
// (0x0062, revision 1), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package scenesmanagement

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0062
	Name             = "ScenesManagement"
	Revision  uint16 = 1
)

// Attribute ids.
const (
	AttrDoNotUse        uint32 = 0x0000 // untyped, X, R V
	AttrSceneTableSize  uint32 = 0x0001 // uint16, M, R V, F
	AttrFabricSceneInfo uint32 = 0x0002 // list[SceneInfoStruct], M, R F V
)

// Command ids.
const (
	CmdAddScene                   uint32 = 0x00 // request → AddSceneResponse, M
	CmdAddSceneResponse           uint32 = 0x00 // response, M
	CmdViewScene                  uint32 = 0x01 // request → ViewSceneResponse, M
	CmdViewSceneResponse          uint32 = 0x01 // response, M
	CmdRemoveScene                uint32 = 0x02 // request → RemoveSceneResponse, M
	CmdRemoveSceneResponse        uint32 = 0x02 // response, M
	CmdRemoveAllScenes            uint32 = 0x03 // request → RemoveAllScenesResponse, M
	CmdRemoveAllScenesResponse    uint32 = 0x03 // response, M
	CmdStoreScene                 uint32 = 0x04 // request → StoreSceneResponse, M
	CmdStoreSceneResponse         uint32 = 0x04 // response, M
	CmdRecallScene                uint32 = 0x05 // request → status, M
	CmdGetSceneMembership         uint32 = 0x06 // request → GetSceneMembershipResponse, M
	CmdGetSceneMembershipResponse uint32 = 0x06 // response, M
	CmdCopyScene                  uint32 = 0x40 // request → CopySceneResponse, O
	CmdCopySceneResponse          uint32 = 0x40 // response, CopyScene
)

// Feature is a ScenesManagement FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// FeatureMap bits.
const (
	FeatureSceneNames Feature = 1 << 0 // SN, O
)

// AttributeValuePairStruct is the AttributeValuePairStruct struct.
type AttributeValuePairStruct struct {
	AttributeId     uint32  // 0: attrib-id, M
	ValueUnsigned8  *uint8  // 1: uint8, O.a
	ValueSigned8    *int8   // 2: int8, O.a
	ValueUnsigned16 *uint16 // 3: uint16, O.a
	ValueSigned16   *int16  // 4: int16, O.a
	ValueUnsigned32 *uint32 // 5: uint32, O.a
	ValueSigned32   *int32  // 6: int32, O.a
	ValueUnsigned64 *uint64 // 7: uint64, O.a
	ValueSigned64   *int64  // 8: int64, O.a
}

// EncodeTLV implements spec.Encodable.
func (v AttributeValuePairStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint32](enc, tlv.ContextTag(0), v.AttributeId)
	spec.PutOptional(enc, tlv.ContextTag(1), v.ValueUnsigned8, spec.PutUint[uint8])
	spec.PutOptional(enc, tlv.ContextTag(2), v.ValueSigned8, spec.PutInt[int8])
	spec.PutOptional(enc, tlv.ContextTag(3), v.ValueUnsigned16, spec.PutUint[uint16])
	spec.PutOptional(enc, tlv.ContextTag(4), v.ValueSigned16, spec.PutInt[int16])
	spec.PutOptional(enc, tlv.ContextTag(5), v.ValueUnsigned32, spec.PutUint[uint32])
	spec.PutOptional(enc, tlv.ContextTag(6), v.ValueSigned32, spec.PutInt[int32])
	spec.PutOptional(enc, tlv.ContextTag(7), v.ValueUnsigned64, spec.PutUint[uint64])
	spec.PutOptional(enc, tlv.ContextTag(8), v.ValueSigned64, spec.PutInt[int64])
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *AttributeValuePairStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "AttributeValuePairStruct",
		spec.Bind(0, "AttributeId", true, &v.AttributeId, spec.DecodeUint[uint32](32)),
		spec.Bind(1, "ValueUnsigned8", false, &v.ValueUnsigned8, spec.DecodeOptional(spec.DecodeUint[uint8](8))),
		spec.Bind(2, "ValueSigned8", false, &v.ValueSigned8, spec.DecodeOptional(spec.DecodeInt[int8](8))),
		spec.Bind(3, "ValueUnsigned16", false, &v.ValueUnsigned16, spec.DecodeOptional(spec.DecodeUint[uint16](16))),
		spec.Bind(4, "ValueSigned16", false, &v.ValueSigned16, spec.DecodeOptional(spec.DecodeInt[int16](16))),
		spec.Bind(5, "ValueUnsigned32", false, &v.ValueUnsigned32, spec.DecodeOptional(spec.DecodeUint[uint32](32))),
		spec.Bind(6, "ValueSigned32", false, &v.ValueSigned32, spec.DecodeOptional(spec.DecodeInt[int32](32))),
		spec.Bind(7, "ValueUnsigned64", false, &v.ValueUnsigned64, spec.DecodeOptional(spec.DecodeUint[uint64](64))),
		spec.Bind(8, "ValueSigned64", false, &v.ValueSigned64, spec.DecodeOptional(spec.DecodeInt[int64](64))),
	)
}

// AttributeValuePairStructDef describes AttributeValuePairStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var AttributeValuePairStructDef = &spec.Struct{Name: "AttributeValuePairStruct", Fields: []spec.Field{
	{ID: 0, Name: "AttributeId", Type: spec.Type{Name: "attrib-id", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{ID: 1, Name: "ValueUnsigned8", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "O.a", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: false, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
	{ID: 2, Name: "ValueSigned8", Type: spec.Type{Name: "int8", Kind: spec.KindInt, Bits: 8}, Conformance: spec.Conformance{Text: "O.a", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: false, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
	{ID: 3, Name: "ValueUnsigned16", Type: spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "O.a", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: false, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
	{ID: 4, Name: "ValueSigned16", Type: spec.Type{Name: "int16", Kind: spec.KindInt, Bits: 16}, Conformance: spec.Conformance{Text: "O.a", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: false, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
	{ID: 5, Name: "ValueUnsigned32", Type: spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "O.a", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: false, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
	{ID: 6, Name: "ValueSigned32", Type: spec.Type{Name: "int32", Kind: spec.KindInt, Bits: 32}, Conformance: spec.Conformance{Text: "O.a", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: false, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
	{ID: 7, Name: "ValueUnsigned64", Type: spec.Type{Name: "uint64", Kind: spec.KindUint, Bits: 64}, Conformance: spec.Conformance{Text: "O.a", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: false, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
	{ID: 8, Name: "ValueSigned64", Type: spec.Type{Name: "int64", Kind: spec.KindInt, Bits: 64}, Conformance: spec.Conformance{Text: "O.a", Op: spec.ConfChoice, Choice: &spec.Choice{Name: "a", Num: 1, OrMore: false, OrLess: false}, Args: []spec.Conformance{{Op: spec.ConfOptional}}}},
}}

// CopyModeBitmap is the CopyModeBitmap map8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type CopyModeBitmap uint8

// CopyModeBitmap bits; a member wider than one bit is its mask.
const (
	CopyModeCopyAllScenes CopyModeBitmap = 1 << 0 // M
)

// CopyModeBitmapDef describes CopyModeBitmap.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var CopyModeBitmapDef = &spec.Bitmap{Name: "CopyModeBitmap", Bits: 8, Members: []spec.BitmapMember{
	{Name: "CopyAllScenes", Bit: 0, Width: 1, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// ExtensionFieldSetStruct is the ExtensionFieldSetStruct struct.
type ExtensionFieldSetStruct struct {
	ClusterId          uint32                     // 0: cluster-id, M
	AttributeValueList []AttributeValuePairStruct // 1: list[AttributeValuePairStruct], M, desc
}

// EncodeTLV implements spec.Encodable.
func (v ExtensionFieldSetStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint32](enc, tlv.ContextTag(0), v.ClusterId)
	spec.PutList(spec.PutStruct[AttributeValuePairStruct])(enc, tlv.ContextTag(1), v.AttributeValueList)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ExtensionFieldSetStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ExtensionFieldSetStruct",
		spec.Bind(0, "ClusterId", true, &v.ClusterId, spec.DecodeUint[uint32](32)),
		spec.Bind(1, "AttributeValueList", true, &v.AttributeValueList, spec.DecodeList(spec.DecodeStruct[AttributeValuePairStruct])),
	)
}

// ExtensionFieldSetStructDef describes ExtensionFieldSetStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var ExtensionFieldSetStructDef = &spec.Struct{Name: "ExtensionFieldSetStruct", Fields: []spec.Field{
	{ID: 0, Name: "ClusterId", Type: spec.Type{Name: "cluster-id", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{ID: 1, Name: "AttributeValueList", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "AttributeValuePairStruct", Kind: spec.KindStruct, Struct: AttributeValuePairStructDef}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
}}

// LogicalSceneTable is the LogicalSceneTable struct.
type LogicalSceneTable struct {
	SceneGroupId        uint16                    // 0: group-id, M
	SceneId             uint8                     // 1: uint8, M, max 254
	SceneName           *string                   // 2: string, SN, max 16
	SceneTransitionTime uint32                    // 3: uint32, M, max 60000000
	ExtensionFields     []ExtensionFieldSetStruct // 4: list[ExtensionFieldSetStruct], M
}

// EncodeTLV implements spec.Encodable.
func (v LogicalSceneTable) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.SceneGroupId)
	spec.PutUint[uint8](enc, tlv.ContextTag(1), v.SceneId)
	spec.PutOptional(enc, tlv.ContextTag(2), v.SceneName, spec.PutString)
	spec.PutUint[uint32](enc, tlv.ContextTag(3), v.SceneTransitionTime)
	spec.PutList(spec.PutStruct[ExtensionFieldSetStruct])(enc, tlv.ContextTag(4), v.ExtensionFields)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *LogicalSceneTable) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "LogicalSceneTable",
		spec.Bind(0, "SceneGroupId", true, &v.SceneGroupId, spec.DecodeUint[uint16](16)),
		spec.Bind(1, "SceneId", true, &v.SceneId, spec.DecodeUintIn[uint8](8, 0, 254)),
		spec.Bind(2, "SceneName", false, &v.SceneName, spec.DecodeOptional(spec.DecodeStringIn(0, 16))),
		spec.Bind(3, "SceneTransitionTime", true, &v.SceneTransitionTime, spec.DecodeUintIn[uint32](32, 0, 60000000)),
		spec.Bind(4, "ExtensionFields", true, &v.ExtensionFields, spec.DecodeList(spec.DecodeStruct[ExtensionFieldSetStruct])),
	)
}

// LogicalSceneTableDef describes LogicalSceneTable.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var LogicalSceneTableDef = &spec.Struct{Name: "LogicalSceneTable", Fields: []spec.Field{
	{ID: 0, Name: "SceneGroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{ID: 1, Name: "SceneId", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 254", Max: &spec.Bound{Int: 254}}},
	{ID: 2, Name: "SceneName", Type: spec.Type{Name: "string", Kind: spec.KindString}, Conformance: spec.Conformance{Text: "SN", Op: spec.ConfName, Name: "SN"}, Constraint: spec.Constraint{Text: "max 16", Max: &spec.Bound{Int: 16}}},
	{ID: 3, Name: "SceneTransitionTime", Type: spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 60000000", Max: &spec.Bound{Int: 60000000}}, Default: float64(0)},
	{ID: 4, Name: "ExtensionFields", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "ExtensionFieldSetStruct", Kind: spec.KindStruct, Struct: ExtensionFieldSetStructDef}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
}}

// SceneInfoStruct is the SceneInfoStruct struct.
type SceneInfoStruct struct {
	SceneCount        uint8  // 0: uint8, M
	CurrentScene      uint8  // 1: uint8, M, desc
	CurrentGroup      uint16 // 2: group-id, M
	SceneValid        bool   // 3: bool, M
	RemainingCapacity uint8  // 4: uint8, M, max 253
	FabricIndex       uint8  // 254: FabricIndex, M, 1 to 254
}

// EncodeTLV implements spec.Encodable.
func (v SceneInfoStruct) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint8](enc, tlv.ContextTag(0), v.SceneCount)
	spec.PutUint[uint8](enc, tlv.ContextTag(1), v.CurrentScene)
	spec.PutUint[uint16](enc, tlv.ContextTag(2), v.CurrentGroup)
	spec.PutBool(enc, tlv.ContextTag(3), v.SceneValid)
	spec.PutUint[uint8](enc, tlv.ContextTag(4), v.RemainingCapacity)
	spec.PutUint[uint8](enc, tlv.ContextTag(254), v.FabricIndex)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *SceneInfoStruct) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "SceneInfoStruct",
		spec.Bind(0, "SceneCount", true, &v.SceneCount, spec.DecodeUint[uint8](8)),
		spec.Bind(1, "CurrentScene", true, &v.CurrentScene, spec.DecodeUint[uint8](8)),
		spec.Bind(2, "CurrentGroup", true, &v.CurrentGroup, spec.DecodeUint[uint16](16)),
		spec.Bind(3, "SceneValid", true, &v.SceneValid, spec.DecodeBool),
		spec.Bind(4, "RemainingCapacity", true, &v.RemainingCapacity, spec.DecodeUintIn[uint8](8, 0, 253)),
		spec.Bind(254, "FabricIndex", true, &v.FabricIndex, spec.DecodeUintIn[uint8](8, 1, 254)),
	)
}

// SceneInfoStructDef describes SceneInfoStruct.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var SceneInfoStructDef = &spec.Struct{Name: "SceneInfoStruct", Fields: []spec.Field{
	{ID: 0, Name: "SceneCount", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
	{ID: 1, Name: "CurrentScene", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}, FabricSensitive: true},
	{ID: 2, Name: "CurrentGroup", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, FabricSensitive: true},
	{ID: 3, Name: "SceneValid", Type: spec.Type{Name: "bool", Kind: spec.KindBool}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, FabricSensitive: true},
	{ID: 4, Name: "RemainingCapacity", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 253", Max: &spec.Bound{Int: 253}}},
	{ID: 254, Name: "FabricIndex", Type: spec.Type{Name: "FabricIndex", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "1 to 254", Min: &spec.Bound{Int: 1}, Max: &spec.Bound{Int: 254}}},
}}

// Status is the status enum8.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Status uint8

// Status values.
const (
	StatusSuccess                   Status = 0
	StatusFailure                   Status = 1
	StatusInvalidSubscription       Status = 125
	StatusUnsupportedAccess         Status = 126
	StatusUnsupportedEndpoint       Status = 127
	StatusInvalidAction             Status = 128
	StatusUnsupportedCommand        Status = 129
	StatusInvalidCommand            Status = 133
	StatusUnsupportedAttribute      Status = 134
	StatusConstraintError           Status = 135
	StatusUnsupportedWrite          Status = 136
	StatusResourceExhausted         Status = 137
	StatusNotFound                  Status = 139
	StatusInvalidDataType           Status = 141
	StatusUnsupportedRead           Status = 143
	StatusDataVersionMismatch       Status = 146
	StatusTimeout                   Status = 148
	StatusUnsupportedNode           Status = 155
	StatusBusy                      Status = 156
	StatusAccessRestricted          Status = 157
	StatusUnsupportedCluster        Status = 195
	StatusNeedsTimedInteraction     Status = 198
	StatusUnsupportedEvent          Status = 199
	StatusPathsExhausted            Status = 200
	StatusTimedRequestMismatch      Status = 201
	StatusFailsafeRequired          Status = 202
	StatusInvalidInState            Status = 203
	StatusNoCommandResponse         Status = 204
	StatusTermsAndConditionsChanged Status = 205
	StatusMaintenanceRequired       Status = 206
	StatusDynamicConstraintError    Status = 207
	StatusAlreadyExists             Status = 208
	StatusInvalidTransportType      Status = 209
)

// StatusDef describes status.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
var StatusDef = &spec.Enum{Name: "status", Bits: 8, Values: []spec.EnumValue{
	{Value: 0, Name: "Success"},
	{Value: 1, Name: "Failure"},
	{Value: 125, Name: "InvalidSubscription"},
	{Value: 126, Name: "UnsupportedAccess"},
	{Value: 127, Name: "UnsupportedEndpoint"},
	{Value: 128, Name: "InvalidAction"},
	{Value: 129, Name: "UnsupportedCommand"},
	{Value: 133, Name: "InvalidCommand"},
	{Value: 134, Name: "UnsupportedAttribute"},
	{Value: 135, Name: "ConstraintError"},
	{Value: 136, Name: "UnsupportedWrite"},
	{Value: 137, Name: "ResourceExhausted"},
	{Value: 139, Name: "NotFound"},
	{Value: 141, Name: "InvalidDataType"},
	{Value: 143, Name: "UnsupportedRead"},
	{Value: 146, Name: "DataVersionMismatch"},
	{Value: 148, Name: "Timeout"},
	{Value: 155, Name: "UnsupportedNode"},
	{Value: 156, Name: "Busy"},
	{Value: 157, Name: "AccessRestricted"},
	{Value: 195, Name: "UnsupportedCluster"},
	{Value: 198, Name: "NeedsTimedInteraction"},
	{Value: 199, Name: "UnsupportedEvent"},
	{Value: 200, Name: "PathsExhausted"},
	{Value: 201, Name: "TimedRequestMismatch"},
	{Value: 202, Name: "FailsafeRequired"},
	{Value: 203, Name: "InvalidInState"},
	{Value: 204, Name: "NoCommandResponse"},
	{Value: 205, Name: "TermsAndConditionsChanged"},
	{Value: 206, Name: "MaintenanceRequired"},
	{Value: 207, Name: "DynamicConstraintError"},
	{Value: 208, Name: "AlreadyExists"},
	{Value: 209, Name: "InvalidTransportType"},
}}

// AddSceneRequest is the AddScene command payload.
type AddSceneRequest struct {
	GroupId                  uint16                    // 0: group-id, M
	SceneId                  uint8                     // 1: uint8, M, max 254
	TransitionTime           uint32                    // 2: uint32, M, max 60000000
	SceneName                string                    // 3: string, M, max 16
	ExtensionFieldSetStructs []ExtensionFieldSetStruct // 4: list[ExtensionFieldSetStruct], M, desc
}

// EncodeTLV implements spec.Encodable.
func (v AddSceneRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.GroupId)
	spec.PutUint[uint8](enc, tlv.ContextTag(1), v.SceneId)
	spec.PutUint[uint32](enc, tlv.ContextTag(2), v.TransitionTime)
	spec.PutString(enc, tlv.ContextTag(3), v.SceneName)
	spec.PutList(spec.PutStruct[ExtensionFieldSetStruct])(enc, tlv.ContextTag(4), v.ExtensionFieldSetStructs)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *AddSceneRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "AddScene",
		spec.Bind(0, "GroupId", true, &v.GroupId, spec.DecodeUint[uint16](16)),
		spec.Bind(1, "SceneId", true, &v.SceneId, spec.DecodeUintIn[uint8](8, 0, 254)),
		spec.Bind(2, "TransitionTime", true, &v.TransitionTime, spec.DecodeUintIn[uint32](32, 0, 60000000)),
		spec.Bind(3, "SceneName", true, &v.SceneName, spec.DecodeStringIn(0, 16)),
		spec.Bind(4, "ExtensionFieldSetStructs", true, &v.ExtensionFieldSetStructs, spec.DecodeList(spec.DecodeStruct[ExtensionFieldSetStruct])),
	)
}

// AddSceneResponse is the AddSceneResponse command payload.
type AddSceneResponse struct {
	Status  Status // 0: status, M, desc
	GroupId uint16 // 1: group-id, M
	SceneId uint8  // 2: uint8, M, max 254
}

// EncodeTLV implements spec.Encodable.
func (v AddSceneResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[Status](enc, tlv.ContextTag(0), v.Status)
	spec.PutUint[uint16](enc, tlv.ContextTag(1), v.GroupId)
	spec.PutUint[uint8](enc, tlv.ContextTag(2), v.SceneId)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *AddSceneResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "AddSceneResponse",
		spec.Bind(0, "Status", true, &v.Status, spec.DecodeUint[Status](8)),
		spec.Bind(1, "GroupId", true, &v.GroupId, spec.DecodeUint[uint16](16)),
		spec.Bind(2, "SceneId", true, &v.SceneId, spec.DecodeUintIn[uint8](8, 0, 254)),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (AddSceneResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdAddSceneResponse
}

// ViewSceneRequest is the ViewScene command payload.
type ViewSceneRequest struct {
	GroupId uint16 // 0: group-id, M
	SceneId uint8  // 1: uint8, M, max 254
}

// EncodeTLV implements spec.Encodable.
func (v ViewSceneRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.GroupId)
	spec.PutUint[uint8](enc, tlv.ContextTag(1), v.SceneId)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ViewSceneRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ViewScene",
		spec.Bind(0, "GroupId", true, &v.GroupId, spec.DecodeUint[uint16](16)),
		spec.Bind(1, "SceneId", true, &v.SceneId, spec.DecodeUintIn[uint8](8, 0, 254)),
	)
}

// ViewSceneResponse is the ViewSceneResponse command payload.
type ViewSceneResponse struct {
	Status                   Status                     // 0: status, M, desc
	GroupId                  uint16                     // 1: group-id, M
	SceneId                  uint8                      // 2: uint8, M, max 254
	TransitionTime           *uint32                    // 3: uint32, Status == Success, max 60000000
	SceneName                *string                    // 4: string, Status == Success, max 16
	ExtensionFieldSetStructs *[]ExtensionFieldSetStruct // 5: list[ExtensionFieldSetStruct], Status == Success
}

// EncodeTLV implements spec.Encodable.
func (v ViewSceneResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[Status](enc, tlv.ContextTag(0), v.Status)
	spec.PutUint[uint16](enc, tlv.ContextTag(1), v.GroupId)
	spec.PutUint[uint8](enc, tlv.ContextTag(2), v.SceneId)
	spec.PutOptional(enc, tlv.ContextTag(3), v.TransitionTime, spec.PutUint[uint32])
	spec.PutOptional(enc, tlv.ContextTag(4), v.SceneName, spec.PutString)
	spec.PutOptional(enc, tlv.ContextTag(5), v.ExtensionFieldSetStructs, spec.PutList(spec.PutStruct[ExtensionFieldSetStruct]))
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *ViewSceneResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "ViewSceneResponse",
		spec.Bind(0, "Status", true, &v.Status, spec.DecodeUint[Status](8)),
		spec.Bind(1, "GroupId", true, &v.GroupId, spec.DecodeUint[uint16](16)),
		spec.Bind(2, "SceneId", true, &v.SceneId, spec.DecodeUintIn[uint8](8, 0, 254)),
		spec.Bind(3, "TransitionTime", false, &v.TransitionTime, spec.DecodeOptional(spec.DecodeUintIn[uint32](32, 0, 60000000))),
		spec.Bind(4, "SceneName", false, &v.SceneName, spec.DecodeOptional(spec.DecodeStringIn(0, 16))),
		spec.Bind(5, "ExtensionFieldSetStructs", false, &v.ExtensionFieldSetStructs, spec.DecodeOptional(spec.DecodeList(spec.DecodeStruct[ExtensionFieldSetStruct]))),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (ViewSceneResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdViewSceneResponse
}

// RemoveSceneRequest is the RemoveScene command payload.
type RemoveSceneRequest struct {
	GroupId uint16 // 0: group-id, M
	SceneId uint8  // 1: uint8, M, max 254
}

// EncodeTLV implements spec.Encodable.
func (v RemoveSceneRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.GroupId)
	spec.PutUint[uint8](enc, tlv.ContextTag(1), v.SceneId)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *RemoveSceneRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "RemoveScene",
		spec.Bind(0, "GroupId", true, &v.GroupId, spec.DecodeUint[uint16](16)),
		spec.Bind(1, "SceneId", true, &v.SceneId, spec.DecodeUintIn[uint8](8, 0, 254)),
	)
}

// RemoveSceneResponse is the RemoveSceneResponse command payload.
type RemoveSceneResponse struct {
	Status  Status // 0: status, M, desc
	GroupId uint16 // 1: group-id, M
	SceneId uint8  // 2: uint8, M, max 254
}

// EncodeTLV implements spec.Encodable.
func (v RemoveSceneResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[Status](enc, tlv.ContextTag(0), v.Status)
	spec.PutUint[uint16](enc, tlv.ContextTag(1), v.GroupId)
	spec.PutUint[uint8](enc, tlv.ContextTag(2), v.SceneId)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *RemoveSceneResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "RemoveSceneResponse",
		spec.Bind(0, "Status", true, &v.Status, spec.DecodeUint[Status](8)),
		spec.Bind(1, "GroupId", true, &v.GroupId, spec.DecodeUint[uint16](16)),
		spec.Bind(2, "SceneId", true, &v.SceneId, spec.DecodeUintIn[uint8](8, 0, 254)),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (RemoveSceneResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdRemoveSceneResponse
}

// RemoveAllScenesRequest is the RemoveAllScenes command payload.
type RemoveAllScenesRequest struct {
	GroupId uint16 // 0: group-id, M
}

// EncodeTLV implements spec.Encodable.
func (v RemoveAllScenesRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.GroupId)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *RemoveAllScenesRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "RemoveAllScenes",
		spec.Bind(0, "GroupId", true, &v.GroupId, spec.DecodeUint[uint16](16)),
	)
}

// RemoveAllScenesResponse is the RemoveAllScenesResponse command payload.
type RemoveAllScenesResponse struct {
	Status  Status // 0: status, M, desc
	GroupId uint16 // 1: group-id, M
}

// EncodeTLV implements spec.Encodable.
func (v RemoveAllScenesResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[Status](enc, tlv.ContextTag(0), v.Status)
	spec.PutUint[uint16](enc, tlv.ContextTag(1), v.GroupId)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *RemoveAllScenesResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "RemoveAllScenesResponse",
		spec.Bind(0, "Status", true, &v.Status, spec.DecodeUint[Status](8)),
		spec.Bind(1, "GroupId", true, &v.GroupId, spec.DecodeUint[uint16](16)),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (RemoveAllScenesResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdRemoveAllScenesResponse
}

// StoreSceneRequest is the StoreScene command payload.
type StoreSceneRequest struct {
	GroupId uint16 // 0: group-id, M
	SceneId uint8  // 1: uint8, M, max 254
}

// EncodeTLV implements spec.Encodable.
func (v StoreSceneRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.GroupId)
	spec.PutUint[uint8](enc, tlv.ContextTag(1), v.SceneId)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *StoreSceneRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "StoreScene",
		spec.Bind(0, "GroupId", true, &v.GroupId, spec.DecodeUint[uint16](16)),
		spec.Bind(1, "SceneId", true, &v.SceneId, spec.DecodeUintIn[uint8](8, 0, 254)),
	)
}

// StoreSceneResponse is the StoreSceneResponse command payload.
type StoreSceneResponse struct {
	Status  Status // 0: status, M, desc
	GroupId uint16 // 1: group-id, M
	SceneId uint8  // 2: uint8, M, max 254
}

// EncodeTLV implements spec.Encodable.
func (v StoreSceneResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[Status](enc, tlv.ContextTag(0), v.Status)
	spec.PutUint[uint16](enc, tlv.ContextTag(1), v.GroupId)
	spec.PutUint[uint8](enc, tlv.ContextTag(2), v.SceneId)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *StoreSceneResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "StoreSceneResponse",
		spec.Bind(0, "Status", true, &v.Status, spec.DecodeUint[Status](8)),
		spec.Bind(1, "GroupId", true, &v.GroupId, spec.DecodeUint[uint16](16)),
		spec.Bind(2, "SceneId", true, &v.SceneId, spec.DecodeUintIn[uint8](8, 0, 254)),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (StoreSceneResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdStoreSceneResponse
}

// RecallSceneRequest is the RecallScene command payload.
type RecallSceneRequest struct {
	GroupId        uint16                 // 0: group-id, M
	SceneId        uint8                  // 1: uint8, M, max 254
	TransitionTime *spec.Nullable[uint32] // 2: uint32, O, max 60000000, X
}

// EncodeTLV implements spec.Encodable.
func (v RecallSceneRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.GroupId)
	spec.PutUint[uint8](enc, tlv.ContextTag(1), v.SceneId)
	spec.PutOptional(enc, tlv.ContextTag(2), v.TransitionTime, spec.PutNullable(spec.PutUint[uint32]))
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *RecallSceneRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "RecallScene",
		spec.Bind(0, "GroupId", true, &v.GroupId, spec.DecodeUint[uint16](16)),
		spec.Bind(1, "SceneId", true, &v.SceneId, spec.DecodeUintIn[uint8](8, 0, 254)),
		spec.Bind(2, "TransitionTime", false, &v.TransitionTime, spec.DecodeOptional(spec.DecodeNullable(spec.DecodeUintIn[uint32](32, 0, 60000000)))),
	)
}

// GetSceneMembershipRequest is the GetSceneMembership command payload.
type GetSceneMembershipRequest struct {
	GroupId uint16 // 0: group-id, M
}

// EncodeTLV implements spec.Encodable.
func (v GetSceneMembershipRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[uint16](enc, tlv.ContextTag(0), v.GroupId)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *GetSceneMembershipRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "GetSceneMembership",
		spec.Bind(0, "GroupId", true, &v.GroupId, spec.DecodeUint[uint16](16)),
	)
}

// GetSceneMembershipResponse is the GetSceneMembershipResponse command payload.
type GetSceneMembershipResponse struct {
	Status    Status               // 0: status, M, desc
	Capacity  spec.Nullable[uint8] // 1: uint8, M, X
	GroupId   uint16               // 2: group-id, M
	SceneList *[]uint8             // 3: list[uint8], Status == Success
}

// EncodeTLV implements spec.Encodable.
func (v GetSceneMembershipResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[Status](enc, tlv.ContextTag(0), v.Status)
	spec.PutNullable(spec.PutUint[uint8])(enc, tlv.ContextTag(1), v.Capacity)
	spec.PutUint[uint16](enc, tlv.ContextTag(2), v.GroupId)
	spec.PutOptional(enc, tlv.ContextTag(3), v.SceneList, spec.PutList(spec.PutUint[uint8]))
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *GetSceneMembershipResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "GetSceneMembershipResponse",
		spec.Bind(0, "Status", true, &v.Status, spec.DecodeUint[Status](8)),
		spec.Bind(1, "Capacity", true, &v.Capacity, spec.DecodeNullable(spec.DecodeUint[uint8](8))),
		spec.Bind(2, "GroupId", true, &v.GroupId, spec.DecodeUint[uint16](16)),
		spec.Bind(3, "SceneList", false, &v.SceneList, spec.DecodeOptional(spec.DecodeList(spec.DecodeUint[uint8](8)))),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (GetSceneMembershipResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdGetSceneMembershipResponse
}

// CopySceneRequest is the CopyScene command payload.
type CopySceneRequest struct {
	Mode                CopyModeBitmap // 0: CopyModeBitmap, M, desc
	GroupIdentifierFrom uint16         // 1: group-id, M
	SceneIdentifierFrom uint8          // 2: uint8, M, max 254
	GroupIdentifierTo   uint16         // 3: group-id, M
	SceneIdentifierTo   uint8          // 4: uint8, M, max 254
}

// EncodeTLV implements spec.Encodable.
func (v CopySceneRequest) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[CopyModeBitmap](enc, tlv.ContextTag(0), v.Mode)
	spec.PutUint[uint16](enc, tlv.ContextTag(1), v.GroupIdentifierFrom)
	spec.PutUint[uint8](enc, tlv.ContextTag(2), v.SceneIdentifierFrom)
	spec.PutUint[uint16](enc, tlv.ContextTag(3), v.GroupIdentifierTo)
	spec.PutUint[uint8](enc, tlv.ContextTag(4), v.SceneIdentifierTo)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *CopySceneRequest) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "CopyScene",
		spec.Bind(0, "Mode", true, &v.Mode, spec.DecodeUint[CopyModeBitmap](8)),
		spec.Bind(1, "GroupIdentifierFrom", true, &v.GroupIdentifierFrom, spec.DecodeUint[uint16](16)),
		spec.Bind(2, "SceneIdentifierFrom", true, &v.SceneIdentifierFrom, spec.DecodeUintIn[uint8](8, 0, 254)),
		spec.Bind(3, "GroupIdentifierTo", true, &v.GroupIdentifierTo, spec.DecodeUint[uint16](16)),
		spec.Bind(4, "SceneIdentifierTo", true, &v.SceneIdentifierTo, spec.DecodeUintIn[uint8](8, 0, 254)),
	)
}

// CopySceneResponse is the CopySceneResponse command payload.
type CopySceneResponse struct {
	Status              Status // 0: status, M, desc
	GroupIdentifierFrom uint16 // 1: group-id, M
	SceneIdentifierFrom uint8  // 2: uint8, M, max 254
}

// EncodeTLV implements spec.Encodable.
func (v CopySceneResponse) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutUint[Status](enc, tlv.ContextTag(0), v.Status)
	spec.PutUint[uint16](enc, tlv.ContextTag(1), v.GroupIdentifierFrom)
	spec.PutUint[uint8](enc, tlv.ContextTag(2), v.SceneIdentifierFrom)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *CopySceneResponse) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "CopySceneResponse",
		spec.Bind(0, "Status", true, &v.Status, spec.DecodeUint[Status](8)),
		spec.Bind(1, "GroupIdentifierFrom", true, &v.GroupIdentifierFrom, spec.DecodeUint[uint16](16)),
		spec.Bind(2, "SceneIdentifierFrom", true, &v.SceneIdentifierFrom, spec.DecodeUintIn[uint8](8, 0, 254)),
	)
}

// ResponseCommand implements spec.ResponsePayload.
func (CopySceneResponse) ResponseCommand() (clusterID, commandID uint32) {
	return ClusterID, CmdCopySceneResponse
}

func decodeAddSceneRequest(n spec.Node) (any, error) { return spec.DecodeStruct[AddSceneRequest](n) }

func decodeAddSceneResponse(n spec.Node) (any, error) { return spec.DecodeStruct[AddSceneResponse](n) }

func decodeViewSceneRequest(n spec.Node) (any, error) { return spec.DecodeStruct[ViewSceneRequest](n) }

func decodeViewSceneResponse(n spec.Node) (any, error) {
	return spec.DecodeStruct[ViewSceneResponse](n)
}

func decodeRemoveSceneRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[RemoveSceneRequest](n)
}

func decodeRemoveSceneResponse(n spec.Node) (any, error) {
	return spec.DecodeStruct[RemoveSceneResponse](n)
}

func decodeRemoveAllScenesRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[RemoveAllScenesRequest](n)
}

func decodeRemoveAllScenesResponse(n spec.Node) (any, error) {
	return spec.DecodeStruct[RemoveAllScenesResponse](n)
}

func decodeStoreSceneRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[StoreSceneRequest](n)
}

func decodeStoreSceneResponse(n spec.Node) (any, error) {
	return spec.DecodeStruct[StoreSceneResponse](n)
}

func decodeRecallSceneRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[RecallSceneRequest](n)
}

func decodeGetSceneMembershipRequest(n spec.Node) (any, error) {
	return spec.DecodeStruct[GetSceneMembershipRequest](n)
}

func decodeGetSceneMembershipResponse(n spec.Node) (any, error) {
	return spec.DecodeStruct[GetSceneMembershipResponse](n)
}

func decodeCopySceneRequest(n spec.Node) (any, error) { return spec.DecodeStruct[CopySceneRequest](n) }

func decodeCopySceneResponse(n spec.Node) (any, error) {
	return spec.DecodeStruct[CopySceneResponse](n)
}

func decodeAttrFabricSceneInfo(n spec.Node) (any, error) {
	v, err := spec.DecodeList(spec.DecodeStruct[SceneInfoStruct])(n)
	return spec.List[SceneInfoStruct](v), err
}

// Definition is the ScenesManagement cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Features: []spec.Feature{
		{Name: "SN", Title: "SceneNames", Bit: 0, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrDoNotUse, Name: "DoNotUse",
			Type:        spec.Type{Name: "", Kind: spec.KindAny},
			Conformance: spec.Conformance{Text: "X", Op: spec.ConfDisallowed},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
		},
		{
			ID: AttrSceneTableSize, Name: "SceneTableSize",
			Type:        spec.Type{Name: "uint16", Kind: spec.KindUint, Bits: 16},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Quality:     spec.Quality{Fixed: true},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
		},
		{
			ID: AttrFabricSceneInfo, Name: "FabricSceneInfo",
			Type:        spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "SceneInfoStruct", Kind: spec.KindStruct, Struct: SceneInfoStructDef}}},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView, Fabric: "F"},
			Constraint:  spec.Constraint{Text: "desc", Desc: true},
			Decode:      decodeAttrFabricSceneInfo,
		},
	},
	Commands: []spec.Command{
		{
			ID: CmdAddScene, Name: "AddScene", Direction: spec.Request,
			Response:    "AddSceneResponse",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage, Fabric: "F"},
			Fields: []spec.Field{
				{ID: 0, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 1, Name: "SceneId", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 254", Max: &spec.Bound{Int: 254}}},
				{ID: 2, Name: "TransitionTime", Type: spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 60000000", Max: &spec.Bound{Int: 60000000}}},
				{ID: 3, Name: "SceneName", Type: spec.Type{Name: "string", Kind: spec.KindString}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 16", Max: &spec.Bound{Int: 16}}},
				{ID: 4, Name: "ExtensionFieldSetStructs", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "ExtensionFieldSetStruct", Kind: spec.KindStruct, Struct: ExtensionFieldSetStructDef}}}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
			},
			Decode: decodeAddSceneRequest,
		},
		{
			ID: CmdAddSceneResponse, Name: "AddSceneResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "Status", Type: spec.Type{Name: "status", Kind: spec.KindEnum, Bits: 8, Enum: StatusDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 2, Name: "SceneId", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 254", Max: &spec.Bound{Int: 254}}},
			},
			Decode: decodeAddSceneResponse,
		},
		{
			ID: CmdViewScene, Name: "ViewScene", Direction: spec.Request,
			Response:    "ViewSceneResponse",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate, Fabric: "F"},
			Fields: []spec.Field{
				{ID: 0, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 1, Name: "SceneId", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 254", Max: &spec.Bound{Int: 254}}},
			},
			Decode: decodeViewSceneRequest,
		},
		{
			ID: CmdViewSceneResponse, Name: "ViewSceneResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "Status", Type: spec.Type{Name: "status", Kind: spec.KindEnum, Bits: 8, Enum: StatusDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 2, Name: "SceneId", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 254", Max: &spec.Bound{Int: 254}}},
				{ID: 3, Name: "TransitionTime", Type: spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "Status == Success", Op: spec.ConfEq, Args: []spec.Conformance{{Op: spec.ConfName, Name: "Status"}, {Op: spec.ConfName, Name: "Success"}}}, Constraint: spec.Constraint{Text: "max 60000000", Max: &spec.Bound{Int: 60000000}}},
				{ID: 4, Name: "SceneName", Type: spec.Type{Name: "string", Kind: spec.KindString}, Conformance: spec.Conformance{Text: "Status == Success", Op: spec.ConfEq, Args: []spec.Conformance{{Op: spec.ConfName, Name: "Status"}, {Op: spec.ConfName, Name: "Success"}}}, Constraint: spec.Constraint{Text: "max 16", Max: &spec.Bound{Int: 16}}},
				{ID: 5, Name: "ExtensionFieldSetStructs", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "ExtensionFieldSetStruct", Kind: spec.KindStruct, Struct: ExtensionFieldSetStructDef}}}, Conformance: spec.Conformance{Text: "Status == Success", Op: spec.ConfEq, Args: []spec.Conformance{{Op: spec.ConfName, Name: "Status"}, {Op: spec.ConfName, Name: "Success"}}}},
			},
			Decode: decodeViewSceneResponse,
		},
		{
			ID: CmdRemoveScene, Name: "RemoveScene", Direction: spec.Request,
			Response:    "RemoveSceneResponse",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage, Fabric: "F"},
			Fields: []spec.Field{
				{ID: 0, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 1, Name: "SceneId", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 254", Max: &spec.Bound{Int: 254}}},
			},
			Decode: decodeRemoveSceneRequest,
		},
		{
			ID: CmdRemoveSceneResponse, Name: "RemoveSceneResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "Status", Type: spec.Type{Name: "status", Kind: spec.KindEnum, Bits: 8, Enum: StatusDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 2, Name: "SceneId", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 254", Max: &spec.Bound{Int: 254}}},
			},
			Decode: decodeRemoveSceneResponse,
		},
		{
			ID: CmdRemoveAllScenes, Name: "RemoveAllScenes", Direction: spec.Request,
			Response:    "RemoveAllScenesResponse",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage, Fabric: "F"},
			Fields: []spec.Field{
				{ID: 0, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeRemoveAllScenesRequest,
		},
		{
			ID: CmdRemoveAllScenesResponse, Name: "RemoveAllScenesResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "Status", Type: spec.Type{Name: "status", Kind: spec.KindEnum, Bits: 8, Enum: StatusDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeRemoveAllScenesResponse,
		},
		{
			ID: CmdStoreScene, Name: "StoreScene", Direction: spec.Request,
			Response:    "StoreSceneResponse",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage, Fabric: "F"},
			Fields: []spec.Field{
				{ID: 0, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 1, Name: "SceneId", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 254", Max: &spec.Bound{Int: 254}}},
			},
			Decode: decodeStoreSceneRequest,
		},
		{
			ID: CmdStoreSceneResponse, Name: "StoreSceneResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "Status", Type: spec.Type{Name: "status", Kind: spec.KindEnum, Bits: 8, Enum: StatusDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 2, Name: "SceneId", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 254", Max: &spec.Bound{Int: 254}}},
			},
			Decode: decodeStoreSceneResponse,
		},
		{
			ID: CmdRecallScene, Name: "RecallScene", Direction: spec.Request,
			Response:    "status",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate, Fabric: "F"},
			Fields: []spec.Field{
				{ID: 0, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 1, Name: "SceneId", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 254", Max: &spec.Bound{Int: 254}}},
				{ID: 2, Name: "TransitionTime", Type: spec.Type{Name: "uint32", Kind: spec.KindUint, Bits: 32}, Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional}, Quality: spec.Quality{Nullable: true}, Constraint: spec.Constraint{Text: "max 60000000", Max: &spec.Bound{Int: 60000000}}},
			},
			Decode: decodeRecallSceneRequest,
		},
		{
			ID: CmdGetSceneMembership, Name: "GetSceneMembership", Direction: spec.Request,
			Response:    "GetSceneMembershipResponse",
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeOperate, Write: spec.PrivilegeOperate, Fabric: "F"},
			Fields: []spec.Field{
				{ID: 0, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeGetSceneMembershipRequest,
		},
		{
			ID: CmdGetSceneMembershipResponse, Name: "GetSceneMembershipResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "Status", Type: spec.Type{Name: "status", Kind: spec.KindEnum, Bits: 8, Enum: StatusDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "Capacity", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Quality: spec.Quality{Nullable: true}},
				{ID: 2, Name: "GroupId", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 3, Name: "SceneList", Type: spec.Type{Name: "list", Kind: spec.KindList, Entry: &spec.Field{Name: "entry", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}}}, Conformance: spec.Conformance{Text: "Status == Success", Op: spec.ConfEq, Args: []spec.Conformance{{Op: spec.ConfName, Name: "Status"}, {Op: spec.ConfName, Name: "Success"}}}},
			},
			Decode: decodeGetSceneMembershipResponse,
		},
		{
			ID: CmdCopyScene, Name: "CopyScene", Direction: spec.Request,
			Response:    "CopySceneResponse",
			Conformance: spec.Conformance{Text: "O", Op: spec.ConfOptional},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeManage, Write: spec.PrivilegeManage, Fabric: "F"},
			Fields: []spec.Field{
				{ID: 0, Name: "Mode", Type: spec.Type{Name: "CopyModeBitmap", Kind: spec.KindBitmap, Bits: 8, Bitmap: CopyModeBitmapDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "GroupIdentifierFrom", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 2, Name: "SceneIdentifierFrom", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 254", Max: &spec.Bound{Int: 254}}},
				{ID: 3, Name: "GroupIdentifierTo", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 4, Name: "SceneIdentifierTo", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 254", Max: &spec.Bound{Int: 254}}},
			},
			Decode: decodeCopySceneRequest,
		},
		{
			ID: CmdCopySceneResponse, Name: "CopySceneResponse", Direction: spec.Response,
			Conformance: spec.Conformance{Text: "CopyScene", Op: spec.ConfName, Name: "CopyScene"},
			Access:      spec.Access{RW: "RW", Read: spec.PrivilegeView, Write: spec.PrivilegeOperate},
			Fields: []spec.Field{
				{ID: 0, Name: "Status", Type: spec.Type{Name: "status", Kind: spec.KindEnum, Bits: 8, Enum: StatusDef}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "desc", Desc: true}},
				{ID: 1, Name: "GroupIdentifierFrom", Type: spec.Type{Name: "group-id", Kind: spec.KindUint, Bits: 16}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
				{ID: 2, Name: "SceneIdentifierFrom", Type: spec.Type{Name: "uint8", Kind: spec.KindUint, Bits: 8}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}, Constraint: spec.Constraint{Text: "max 254", Max: &spec.Bound{Int: 254}}},
			},
			Decode: decodeCopySceneResponse,
		},
	},
}

func init() { spec.Register(Definition) }
