// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package descriptor

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, DeviceTypeStruct{DeviceType: uint32(1), Revision: uint16(1)}, spec.DecodeStruct[DeviceTypeStruct])
	spectest.RoundTrip(t, Semtag{MfgCode: spec.ValueOf(uint16(1)), NamespaceId: Namespace(1), Tag: uint8(1), Label: spectest.Ptr(spec.ValueOf("x"))}, spec.DecodeStruct[Semtag])
	spectest.RoundTripAttribute(t, Definition, AttrDeviceTypeList, spec.List[DeviceTypeStruct]([]DeviceTypeStruct{DeviceTypeStruct{DeviceType: uint32(1), Revision: uint16(1)}}))
	spectest.RoundTripAttribute(t, Definition, AttrTagList, spec.List[Semtag]([]Semtag{Semtag{MfgCode: spec.ValueOf(uint16(1)), NamespaceId: Namespace(1), Tag: uint8(1), Label: spectest.Ptr(spec.ValueOf("x"))}}))
}
