// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

// Package booleanstate is the generated definition of the Matter BooleanState cluster
// (0x0045, revision 3), from the matter.js model at 85cf664 (Matter 1.6.1).
//
// It declares the cluster's ids, typed enums, bitmaps and structs with their
// TLV codecs, the command and event payloads, and [Definition], the metadata
// the cluster/spec runtime derives lists, privileges and write checks from.
// Importing the package registers the definition with spec.Register, so the
// bridge decodes the cluster's request payloads.
package booleanstate

import (
	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/tlv"
)

// Cluster identity.
const (
	ClusterID uint32 = 0x0045
	Name             = "BooleanState"
	Revision  uint16 = 3
)

// Attribute ids.
const (
	AttrStateValue uint32 = 0x0000 // bool, M, R V
)

// Event ids.
const (
	EventStateChange uint32 = 0x00 // info, CHGEVENT, O
)

// Feature is a BooleanState FeatureMap bit.
//
// fabric:reachable:reason="generated: referenced from Definition and the generated test; a package-level initializer, which RTA does not follow"
type Feature uint32

// FeatureMap bits.
const (
	FeatureChangeEvent Feature = 1 << 0 // CHGEVENT, [Rev >= v3]
)

// StateChangeEvent is the StateChange event payload.
type StateChangeEvent struct {
	StateValue bool // 0: bool, M
}

// EncodeTLV implements spec.Encodable.
func (v StateChangeEvent) EncodeTLV(enc *tlv.Encoder, tag tlv.Tag) {
	enc.StartStruct(tag)
	spec.PutBool(enc, tlv.ContextTag(0), v.StateValue)
	_ = enc.EndContainer()
}

// DecodeTLV decodes the structure n into v.
func (v *StateChangeEvent) DecodeTLV(n spec.Node) error {
	return spec.DecodeFields(n, "StateChange",
		spec.Bind(0, "StateValue", true, &v.StateValue, spec.DecodeBool),
	)
}

func decodeStateChangeEvent(n spec.Node) (any, error) { return spec.DecodeStruct[StateChangeEvent](n) }

// Definition is the BooleanState cluster definition.
var Definition = &spec.Cluster{
	ID: ClusterID, Name: Name, Revision: Revision,
	Features: []spec.Feature{
		{Name: "CHGEVENT", Title: "ChangeEvent", Bit: 0, Conformance: spec.Conformance{Text: "[Rev >= v3]", Op: spec.ConfOptionalIf, Args: []spec.Conformance{{Op: spec.ConfRevision, Rev: 3}}}},
	},
	Attributes: []spec.Attribute{
		{
			ID: AttrStateValue, Name: "StateValue",
			Type:        spec.Type{Name: "bool", Kind: spec.KindBool},
			Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
		},
	},
	Events: []spec.Event{
		{
			ID: EventStateChange, Name: "StateChange", Priority: spec.PriorityInfo,
			Conformance: spec.Conformance{Text: "CHGEVENT, O", Op: spec.ConfOtherwise, Args: []spec.Conformance{{Op: spec.ConfName, Name: "CHGEVENT"}, {Op: spec.ConfOptional}}},
			Access:      spec.Access{RW: "R", Read: spec.PrivilegeView},
			Fields: []spec.Field{
				{ID: 0, Name: "StateValue", Type: spec.Type{Name: "bool", Kind: spec.KindBool}, Conformance: spec.Conformance{Text: "M", Op: spec.ConfMandatory}},
			},
			Decode: decodeStateChangeEvent,
		},
	},
}

func init() { spec.Register(Definition) }
