// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package rvcoperationalstate

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, ErrorStateStruct{ErrorStateId: ErrorStateEnum(0), ErrorStateLabel: spectest.Ptr("x"), ErrorStateDetails: spectest.Ptr("x")}, spec.DecodeStruct[ErrorStateStruct])
	spectest.RoundTrip(t, OperationalStateStruct{OperationalStateId: OperationalStateEnum(0), OperationalStateLabel: spectest.Ptr("x")}, spec.DecodeStruct[OperationalStateStruct])
	spectest.RoundTripCommand(t, Definition, CmdPause, spec.Request, PauseRequest{})
	spectest.RoundTripCommand(t, Definition, CmdStop, spec.Request, StopRequest{})
	spectest.RoundTripCommand(t, Definition, CmdStart, spec.Request, StartRequest{})
	spectest.RoundTripCommand(t, Definition, CmdResume, spec.Request, ResumeRequest{})
	spectest.RoundTripCommand(t, Definition, CmdOperationalCommandResponse, spec.Response, OperationalCommandResponse{CommandResponseState: ErrorStateStruct{ErrorStateId: ErrorStateEnum(0), ErrorStateLabel: spectest.Ptr("x"), ErrorStateDetails: spectest.Ptr("x")}})
	spectest.RoundTripCommand(t, Definition, CmdGoHome, spec.Request, GoHomeRequest{})
	spectest.RoundTripEvent(t, Definition, EventOperationalError, OperationalErrorEvent{ErrorState: ErrorStateStruct{ErrorStateId: ErrorStateEnum(0), ErrorStateLabel: spectest.Ptr("x"), ErrorStateDetails: spectest.Ptr("x")}})
	spectest.RoundTripEvent(t, Definition, EventOperationCompletion, OperationCompletionEvent{CompletionErrorCode: uint8(1), TotalOperationalTime: spectest.Ptr(spec.ValueOf(uint32(1))), PausedTime: spectest.Ptr(spec.ValueOf(uint32(1)))})
	spectest.RoundTripAttribute(t, Definition, AttrOperationalStateList, spec.List[OperationalStateStruct]([]OperationalStateStruct{OperationalStateStruct{OperationalStateId: OperationalStateEnum(0), OperationalStateLabel: spectest.Ptr("x")}}))
	spectest.RoundTripAttribute(t, Definition, AttrOperationalError, ErrorStateStruct{ErrorStateId: ErrorStateEnum(0), ErrorStateLabel: spectest.Ptr("x"), ErrorStateDetails: spectest.Ptr("x")})
}
