// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/clustergen from parity/schema.json. DO NOT EDIT.

package energyevse

import (
	"testing"

	"github.com/SukramJ/go-fabric/cluster/spec"
	"github.com/SukramJ/go-fabric/cluster/spec/spectest"
)

var _ = spec.Register

// TestDefinitionMatchesSnapshot holds the generated definition against
// the matter.js snapshot it was generated from.
func TestDefinitionMatchesSnapshot(t *testing.T) {
	t.Parallel()
	spectest.CheckDefinition(t, Definition)
}

// TestCodecsRoundTrip encodes a populated value of every generated
// struct and payload and decodes it back.
func TestCodecsRoundTrip(t *testing.T) {
	t.Parallel()
	spectest.RoundTrip(t, ChargingTargetScheduleStruct{DayOfWeekForSequence: TargetDayOfWeekBitmap(1 << 0), ChargingTargets: []ChargingTargetStruct{ChargingTargetStruct{TargetTimeMinutesPastMidnight: uint16(1), TargetSoC: spectest.Ptr(uint8(1)), AddedEnergy: spectest.Ptr(int64(1))}}}, spec.DecodeStruct[ChargingTargetScheduleStruct])
	spectest.RoundTrip(t, ChargingTargetStruct{TargetTimeMinutesPastMidnight: uint16(1), TargetSoC: spectest.Ptr(uint8(1)), AddedEnergy: spectest.Ptr(int64(1))}, spec.DecodeStruct[ChargingTargetStruct])
	spectest.RoundTripCommand(t, Definition, CmdGetTargetsResponse, spec.Response, GetTargetsResponse{ChargingTargetSchedules: []ChargingTargetScheduleStruct{ChargingTargetScheduleStruct{DayOfWeekForSequence: TargetDayOfWeekBitmap(1 << 0), ChargingTargets: []ChargingTargetStruct{ChargingTargetStruct{TargetTimeMinutesPastMidnight: uint16(1), TargetSoC: spectest.Ptr(uint8(1)), AddedEnergy: spectest.Ptr(int64(1))}}}}})
	spectest.RoundTripCommand(t, Definition, CmdDisable, spec.Request, DisableRequest{})
	spectest.RoundTripCommand(t, Definition, CmdEnableCharging, spec.Request, EnableChargingRequest{ChargingEnabledUntil: spec.ValueOf(uint32(1)), MinimumChargeCurrent: int64(1), MaximumChargeCurrent: int64(1)})
	spectest.RoundTripCommand(t, Definition, CmdEnableDischarging, spec.Request, EnableDischargingRequest{DischargingEnabledUntil: spec.ValueOf(uint32(1)), MaximumDischargeCurrent: int64(1)})
	spectest.RoundTripCommand(t, Definition, CmdStartDiagnostics, spec.Request, StartDiagnosticsRequest{})
	spectest.RoundTripCommand(t, Definition, CmdSetTargets, spec.Request, SetTargetsRequest{ChargingTargetSchedules: []ChargingTargetScheduleStruct{ChargingTargetScheduleStruct{DayOfWeekForSequence: TargetDayOfWeekBitmap(1 << 0), ChargingTargets: []ChargingTargetStruct{ChargingTargetStruct{TargetTimeMinutesPastMidnight: uint16(1), TargetSoC: spectest.Ptr(uint8(1)), AddedEnergy: spectest.Ptr(int64(1))}}}}})
	spectest.RoundTripCommand(t, Definition, CmdGetTargets, spec.Request, GetTargetsRequest{})
	spectest.RoundTripCommand(t, Definition, CmdClearTargets, spec.Request, ClearTargetsRequest{})
	spectest.RoundTripEvent(t, Definition, EventEvConnected, EvConnectedEvent{SessionId: uint32(1)})
	spectest.RoundTripEvent(t, Definition, EventEvNotDetected, EvNotDetectedEvent{SessionId: uint32(1), State: StateEnum(0), SessionDuration: uint32(1), SessionEnergyCharged: int64(1), SessionEnergyDischarged: spectest.Ptr(int64(1))})
	spectest.RoundTripEvent(t, Definition, EventEnergyTransferStarted, EnergyTransferStartedEvent{SessionId: uint32(1), State: StateEnum(0), MaximumCurrent: int64(1), MaximumDischargeCurrent: spectest.Ptr(int64(1))})
	spectest.RoundTripEvent(t, Definition, EventEnergyTransferStopped, EnergyTransferStoppedEvent{SessionId: uint32(1), State: StateEnum(0), Reason: EnergyTransferStoppedReasonEnum(0), EnergyTransferred: int64(1), EnergyDischarged: spectest.Ptr(int64(1))})
	spectest.RoundTripEvent(t, Definition, EventFault, FaultEvent{SessionId: spec.ValueOf(uint32(1)), State: StateEnum(0), FaultStatePreviousState: FaultStateEnum(0), FaultStateCurrentState: FaultStateEnum(0)})
	spectest.RoundTripEvent(t, Definition, EventRfid, RfidEvent{Uid: []byte{1}})
}
